{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "plumber-android-core",
    "version": "2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-utils",
          "version": {
            "requires": "2.14"
          }
        }
      ],
      "files": [
        {
          "name": "plumber-android-core-2.14.aar",
          "url": "plumber-android-core-2.14.aar",
          "size": 87195,
          "sha512": "484e0e3d92ad3a58e4203f61ee426c7ee664be539ae0226c0ae3ab8b828877b488e75e2423bcd390d97478ac387af11c69b6b696cb7ab3bf8102576385bfd727",
          "sha256": "eb595ab5d7e4b1e9d9f8a7a654e8aed42e2cdec6a6ec69acfdc6d8f3b08967a6",
          "sha1": "badb89266556fceb27bdd3d3e2602551aed5540c",
          "md5": "6f1cebcd8854bef243d9866ced7bdc04"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-utils",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.curtains",
          "module": "curtains",
          "version": {
            "requires": "1.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "plumber-android-core-2.14.aar",
          "url": "plumber-android-core-2.14.aar",
          "size": 87195,
          "sha512": "484e0e3d92ad3a58e4203f61ee426c7ee664be539ae0226c0ae3ab8b828877b488e75e2423bcd390d97478ac387af11c69b6b696cb7ab3bf8102576385bfd727",
          "sha256": "eb595ab5d7e4b1e9d9f8a7a654e8aed42e2cdec6a6ec69acfdc6d8f3b08967a6",
          "sha1": "badb89266556fceb27bdd3d3e2602551aed5540c",
          "md5": "6f1cebcd8854bef243d9866ced7bdc04"
        }
      ]
    }
  ]
}
