{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-metrics",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-metrics-1.23.7.jar",
          "url": "detekt-metrics-1.23.7.jar",
          "size": 95767,
          "sha512": "83a36e06239d5ebbb60411f77ce5669616b1e3026bf63f8dce6ce6a4cd4c3b93667e0dcda4b2421c9f692bf425ff6f0cd004b108085f8fb1c5408ecaf9cf5590",
          "sha256": "a3592ec4f927f4101b85782a47b94a19aec9c1c75a9054430d8898190d6d0065",
          "sha1": "8619bcd179d062ff55bb4cd8b0fb75a9fed0c6d7",
          "md5": "a883de4acaf75a4bd1f0bd4dd3461dd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-metrics-1.23.7.jar",
          "url": "detekt-metrics-1.23.7.jar",
          "size": 95767,
          "sha512": "83a36e06239d5ebbb60411f77ce5669616b1e3026bf63f8dce6ce6a4cd4c3b93667e0dcda4b2421c9f692bf425ff6f0cd004b108085f8fb1c5408ecaf9cf5590",
          "sha256": "a3592ec4f927f4101b85782a47b94a19aec9c1c75a9054430d8898190d6d0065",
          "sha1": "8619bcd179d062ff55bb4cd8b0fb75a9fed0c6d7",
          "md5": "a883de4acaf75a4bd1f0bd4dd3461dd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-metrics-1.23.7-sources.jar",
          "url": "detekt-metrics-1.23.7-sources.jar",
          "size": 14427,
          "sha512": "8ef50f3f043b463175cd856fce764cee75e7623098643818983e05c5db675d843acdd1d36520ee9ef2cea3ad3b1e512f8e82de2df40a057c42c2f0207d786cf7",
          "sha256": "2a1a80e1caeb6dc683ef8369f9f56c85063b074a76d915d8925b1fadc8ad173b",
          "sha1": "d3e9ba64045774e1c8eeb579d263718e5141143d",
          "md5": "fd83c045c61f3117e3927dde6d5d1796"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-metrics-1.23.7-javadoc.jar",
          "url": "detekt-metrics-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "890e3021d30859f7954055249f21b5880ddac3b13843d03b3fd2fc97ed3a596e881619934c03a7786c154965f885c292b6aebc2f0ff2c9d8f328dd39458c6750",
          "sha256": "000422088dab561ded3ca3b38f5d0787aaa42ce034a26330003bd3f082fa152b",
          "sha1": "87077aab9d24bbd2479bd12a83f7f639faf5710d",
          "md5": "c120a0ced59b54cd0c579b47b7ace0a3"
        }
      ]
    }
  ]
}
