{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.1.1-sources.jar",
          "url": "glance-appwidget-1.1.1-sources.jar",
          "size": 127041,
          "sha512": "e3f46dc2e02fccc57224837df04d3735b1a73301123a85773b83bd4e1890ca1dda418ce4d65629b0aeaeb284a1985fba3d2b62f8ea962cb07e3ca677534db958",
          "sha256": "c78f63ccf1781c593015efe46efc508d27a4c6e0b0569c40220385561f1ac87d",
          "sha1": "74e42a0f4b9eee561fd838ebb156fd7898cf5694",
          "md5": "3c96b13f40272a869af92390d1bb96c6"
        },
        {
          "name": "glance-appwidget-1.1.1-samples-sources.jar",
          "url": "glance-appwidget-1.1.1-samples-sources.jar",
          "size": 3081,
          "sha512": "2dd4a7b981b12cea3c9443eda48deb80d60263027b2bdecf6fb808b822750b92191a010b9470fc4844f68997fd3114b8f3e41afce93d13c30c884fb68a211ebc",
          "sha256": "d7a9d19ca2be17fa1601cf74c7143cb5928eab9b110b85fbf6ecee6e02df8c57",
          "sha1": "271cb664cb860b6014a11505b9dcbc5aad3af945",
          "md5": "f6fe0dcb726347fcc2fa48dee329b957"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.1.1.aar",
          "url": "glance-appwidget-1.1.1.aar",
          "size": 1270231,
          "sha512": "462bb0712be32a321b777a9ff1d84550aab18f02b5601783574e05d11df4f512f5034d9ff898a1afbe3ebe77f215ea77f8cccfae424a2a42fc171b38dd5fded1",
          "sha256": "81fc7dc88e444dc3aebb24b773e2846cc2bd62c71f4741f70d6e5ed7f548c59f",
          "sha1": "8f61d47d1c86ad056a32f758722ee13325b25ae7",
          "md5": "2378d0e20f232ebc1014645aafe7b3cd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-remoteviews",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.1.1.aar",
          "url": "glance-appwidget-1.1.1.aar",
          "size": 1270231,
          "sha512": "462bb0712be32a321b777a9ff1d84550aab18f02b5601783574e05d11df4f512f5034d9ff898a1afbe3ebe77f215ea77f8cccfae424a2a42fc171b38dd5fded1",
          "sha256": "81fc7dc88e444dc3aebb24b773e2846cc2bd62c71f4741f70d6e5ed7f548c59f",
          "sha1": "8f61d47d1c86ad056a32f758722ee13325b25ae7",
          "md5": "2378d0e20f232ebc1014645aafe7b3cd"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.1.1-versionMetadata.json",
          "url": "glance-appwidget-1.1.1-versionMetadata.json",
          "size": 22593,
          "sha512": "8d99662359f4b6b160ac53a44f7ffa2f940688bba9ac2f977feaf78b81e7f4af0301dc34c2919d4e944f411eedd3db9472f3097d92d5aacd2aa5cb43fef79346",
          "sha256": "1af257e1dd0ddfeb6bb64e8abff23fc2de3df0031b5bd39ff0516d0062babb4b",
          "sha1": "e7d1da8edee8f52c25a5dd17336e0d6445f07550",
          "md5": "07ac32ad60d238f189ba6c08a4f7ef6c"
        }
      ]
    }
  ]
}