{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.takahirom.roborazzi",
    "module": "roborazzi-gradle-plugin",
    "version": "1.39.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "roborazzi-gradle-plugin-1.39.0.jar",
          "url": "roborazzi-gradle-plugin-1.39.0.jar",
          "size": 151299,
          "sha512": "d07b4a03c8eb843633f3999b4fe64714335766386fe79b6fadafd1db4e399e1e5e0836248a5d994ea81471e1cee85ae30be046e47bd8ccd6092b47e202e5a7f3",
          "sha256": "04ba777cc4f272d0126c05487baad4bd951cdbbca84dc5be586b9b5bfcf83c3c",
          "sha1": "1eb4bea881f728278e6b63c742ca81b2d0ff5985",
          "md5": "57f7627c54dcd350419201d06614a098"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.takahirom.roborazzi",
          "module": "roborazzi-core",
          "version": {
            "requires": "1.39.0"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.webjars",
          "module": "webjars-locator-lite",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.webjars",
          "module": "materializecss",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.webjars",
          "module": "material-design-icons",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "roborazzi-gradle-plugin-1.39.0.jar",
          "url": "roborazzi-gradle-plugin-1.39.0.jar",
          "size": 151299,
          "sha512": "d07b4a03c8eb843633f3999b4fe64714335766386fe79b6fadafd1db4e399e1e5e0836248a5d994ea81471e1cee85ae30be046e47bd8ccd6092b47e202e5a7f3",
          "sha256": "04ba777cc4f272d0126c05487baad4bd951cdbbca84dc5be586b9b5bfcf83c3c",
          "sha1": "1eb4bea881f728278e6b63c742ca81b2d0ff5985",
          "md5": "57f7627c54dcd350419201d06614a098"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "roborazzi-gradle-plugin-1.39.0-sources.jar",
          "url": "roborazzi-gradle-plugin-1.39.0-sources.jar",
          "size": 13269,
          "sha512": "e0c9de0b5bf7c4246d76f14f368a68eb3c4cbbd0cc1293742694572fac4b64efcf65f9475a0731c27fd58ca874284ebd9eaf11c71c8bfc796dfaf80319119f90",
          "sha256": "bd6ef72619bc34b7e2053ae83629f84319b90b5cb63dccd4b4df11da88f55915",
          "sha1": "b5d1cb03eabef5d7ca93b20b8da1b6c16bd8cee0",
          "md5": "a2f6c7cf85bd739cd1f6868004fc393d"
        }
      ]
    }
  ]
}
