{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-object-watcher",
    "version": "2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.14"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-2.14.jar",
          "url": "leakcanary-object-watcher-2.14.jar",
          "size": 16911,
          "sha512": "6f084508fe137077095ee62d256d9fb5ae6222763d1e91a4231c3f82a137bf566a73a3a435236d0dfc92b8041efd12d77a59153e7cfcf5f5d4681f76e8831f44",
          "sha256": "575a046bcc362916fa6f106373f393bacf5578f13640419a464b4c81d89e646e",
          "sha1": "0004e9e9ea14da4e86321b1369c7aea6528f0ef2",
          "md5": "4e42a497f3966785c616f1905bf3bb9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.14"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-2.14.jar",
          "url": "leakcanary-object-watcher-2.14.jar",
          "size": 16911,
          "sha512": "6f084508fe137077095ee62d256d9fb5ae6222763d1e91a4231c3f82a137bf566a73a3a435236d0dfc92b8041efd12d77a59153e7cfcf5f5d4681f76e8831f44",
          "sha256": "575a046bcc362916fa6f106373f393bacf5578f13640419a464b4c81d89e646e",
          "sha1": "0004e9e9ea14da4e86321b1369c7aea6528f0ef2",
          "md5": "4e42a497f3966785c616f1905bf3bb9f"
        }
      ]
    }
  ]
}
