{
  "formatVersion": "1.1",
  "component": {
    "url": "../../clikt/4.4.0/clikt-4.4.0.module",
    "group": "com.github.ajalt.clikt",
    "module": "clikt",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "clikt-jvm.jar",
          "url": "clikt-jvm-4.4.0.jar",
          "size": 622185,
          "sha512": "46f68d8996e3385c3bb152eef7d196efccd703a27b92cc9fc7aa0cc0f3f3e3feab033cefb031c18d686e35de4dbe2b87e6fe4545d16f220d0c7de8dc017fe822",
          "sha256": "dd424c7c4113c114efc103da3fab82ccbee7484970129c0764a4578b58677371",
          "sha1": "df1e97760c6d0d96033a96a820a4a6e1d0e2f267",
          "md5": "727e93b990f7cf6359e050ff1e602ee1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "clikt-jvm.jar",
          "url": "clikt-jvm-4.4.0.jar",
          "size": 622185,
          "sha512": "46f68d8996e3385c3bb152eef7d196efccd703a27b92cc9fc7aa0cc0f3f3e3feab033cefb031c18d686e35de4dbe2b87e6fe4545d16f220d0c7de8dc017fe822",
          "sha256": "dd424c7c4113c114efc103da3fab82ccbee7484970129c0764a4578b58677371",
          "sha1": "df1e97760c6d0d96033a96a820a4a6e1d0e2f267",
          "md5": "727e93b990f7cf6359e050ff1e602ee1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "clikt-jvm-sources.jar",
          "url": "clikt-jvm-4.4.0-sources.jar",
          "size": 96158,
          "sha512": "e30a20fda7103abc9a692db3898641ab13db60a50749fd4cdff9a8171a783f08015d9fbbd94769baad841b6fd2f9d7bd351c61f259d4f521e1b7946dff1e3296",
          "sha256": "2a4d56a0feb9d245bec80c94c4173995685e5a51bbb7528d89addc408c69c05f",
          "sha1": "ab6624d51f2a296b7afb9516fab0b24a8a59728c",
          "md5": "4149d683d6d8631ebc3209c3774c1ad2"
        }
      ]
    }
  ]
}
