{
  "formatVersion": "1.1",
  "component": {
    "url": "../../roborazzi-core/1.39.0/roborazzi-core-1.39.0.module",
    "group": "io.github.takahirom.roborazzi",
    "module": "roborazzi-core",
    "version": "1.39.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "com.dropbox.differ",
          "module": "differ",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "roborazzi-core-release.aar",
          "url": "roborazzi-core-android-1.39.0.aar",
          "size": 234077,
          "sha512": "c71d4fe68f7e61070db8900b1615373762b904d627679eee7ab92bc1e853bd771cbfadedd956b0f19a7f0ba8887b65f8240911a76cf01b90ac751ef3b6e66862",
          "sha256": "169fcd237896c2fc14f4e27d86a79c0c8d192306c8abd278917637f88349fff9",
          "sha1": "284599d1af0f3ceebe00595a7fc0f75f37ae7dc8",
          "md5": "7cc44e64fcbce873188d0d992d256968"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.dropbox.differ",
          "module": "differ",
          "version": {
            "requires": "0.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.3.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "roborazzi-core-release.aar",
          "url": "roborazzi-core-android-1.39.0.aar",
          "size": 234077,
          "sha512": "c71d4fe68f7e61070db8900b1615373762b904d627679eee7ab92bc1e853bd771cbfadedd956b0f19a7f0ba8887b65f8240911a76cf01b90ac751ef3b6e66862",
          "sha256": "169fcd237896c2fc14f4e27d86a79c0c8d192306c8abd278917637f88349fff9",
          "sha1": "284599d1af0f3ceebe00595a7fc0f75f37ae7dc8",
          "md5": "7cc44e64fcbce873188d0d992d256968"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "roborazzi-core-android-sources.jar",
          "url": "roborazzi-core-android-1.39.0-sources.jar",
          "size": 36826,
          "sha512": "ea624c6bea574c987a330d919a71e5030c7412de3c08bf1046f1b8c71be3e6f2057ac9bd06530198480accc173c730c91da2e88de485abcdb15ec5fd3fee4faf",
          "sha256": "768c3ed0f1d8ede9c5e8a978146456da10ed9f63e099deb359f46e35a67b05be",
          "sha1": "ddd78d3ef1ab4679bf2172097e122deee87679d4",
          "md5": "22aa3adf473bf842bcda751c064c0e4a"
        }
      ]
    }
  ]
}
