{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-compose-core/3.1.0/coil-compose-core-3.1.0.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-compose-core",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-core-release.aar",
          "url": "coil-compose-core-android-3.1.0.aar",
          "size": 127672,
          "sha512": "7c0162f7e6f68dc077a9cc1920614361e73039aa5df6bc087ea221727abe2109e89e04e8615dbaf0f9bcab7ee5a7d681dc17968d08c22bcc48dba7dea3d7d522",
          "sha256": "af07817a81f2d2a3608ddf2bc79bb5f0a6323620804094c9b6cc0b3496af04da",
          "sha1": "9760897b9e97cb9fb8953de9f8d05e634edca796",
          "md5": "d5e3c4fdd867485f5ff965d07e5a6af0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.accompanist",
          "module": "accompanist-drawablepainter",
          "version": {
            "requires": "0.36.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "coil-compose-core-release.aar",
          "url": "coil-compose-core-android-3.1.0.aar",
          "size": 127672,
          "sha512": "7c0162f7e6f68dc077a9cc1920614361e73039aa5df6bc087ea221727abe2109e89e04e8615dbaf0f9bcab7ee5a7d681dc17968d08c22bcc48dba7dea3d7d522",
          "sha256": "af07817a81f2d2a3608ddf2bc79bb5f0a6323620804094c9b6cc0b3496af04da",
          "sha1": "9760897b9e97cb9fb8953de9f8d05e634edca796",
          "md5": "d5e3c4fdd867485f5ff965d07e5a6af0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "coil-compose-core-android-3.1.0-sources.jar",
          "url": "coil-compose-core-android-3.1.0-sources.jar",
          "size": 24839,
          "sha512": "c3293e20e0ac67edbed3ee0069eb052ef4e3040c1b49592a67ecad21c6d83d29040e6566fa6921127ca3497fa6454eeb88a0c9f0b66f307f3ef11043ba1c6fac",
          "sha256": "99a4b7104ebbca179c4c0464a31a83fd10895a95543016a96cfdb463aee5a38e",
          "sha1": "c840684b499917a32d5c0aa8b51c84a8a8305550",
          "md5": "0ddaa736bea5067020d55a38a904000c"
        }
      ]
    }
  ]
}
