{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.paparazzi",
    "module": "paparazzi",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib",
          "version": {
            "requires": "14.0.11"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "ninepatch",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "kxml2",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "paparazzi-1.3.5.jar",
          "url": "paparazzi-1.3.5.jar",
          "size": 446032,
          "sha512": "241d67d317f4aa4d782913a9861bf91efa0de6129b648900e96c157c3a68acb6b84b0ef0d7ecc0648c29bc33572183b0d5a70e8c9e85b1a522a49beac4895e2e",
          "sha256": "b89c5c0ac0669ac6e045324effa56e816256e059eea5cf036558a35ae89736fc",
          "sha1": "dcaa130064b67a4e65a482a7937d9d6ca50b0a41",
          "md5": "0a4f7557fec1744b7731b7d8f29d4e71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.15.10"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.15.10"
          }
        },
        {
          "group": "org.jetbrains.intellij.deps",
          "module": "trove4j",
          "version": {
            "requires": "1.0.20200330"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib",
          "version": {
            "requires": "14.0.11"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "ninepatch",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "kxml2",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "paparazzi-1.3.5.jar",
          "url": "paparazzi-1.3.5.jar",
          "size": 446032,
          "sha512": "241d67d317f4aa4d782913a9861bf91efa0de6129b648900e96c157c3a68acb6b84b0ef0d7ecc0648c29bc33572183b0d5a70e8c9e85b1a522a49beac4895e2e",
          "sha256": "b89c5c0ac0669ac6e045324effa56e816256e059eea5cf036558a35ae89736fc",
          "sha1": "dcaa130064b67a4e65a482a7937d9d6ca50b0a41",
          "md5": "0a4f7557fec1744b7731b7d8f29d4e71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paparazzi-1.3.5-sources.jar",
          "url": "paparazzi-1.3.5-sources.jar",
          "size": 152855,
          "sha512": "1dedb74b990271fb2210b13c2275f00d5084031ae377dcc73c23b6b3e4d7fd0379607ae215bb2cf9a7ea19bc3947e98f13d5b83b5c45dec1d995d5b60118632c",
          "sha256": "ffa627a7a462de9384581238a69076ff15baf29f1ff7703d04db5059cc8742c2",
          "sha1": "a333b143e10fdbb348ea658e0b194d711eca20f2",
          "md5": "85d6fe30a6d4eb938e37ced01df44427"
        }
      ]
    }
  ]
}
