{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-1.1.1-sources.jar",
          "url": "glance-1.1.1-sources.jar",
          "size": 65993,
          "sha512": "3b41ebb576f903b400b660c6da582fe241907268fd032c4d1330cb9fea7f6e009954c0c0e43822b584336578f3fd3adb9ef99389bfe6d9feb5aa8783614c352d",
          "sha256": "626ed45cc1b637429fa87fb4dffdf424b70edabd6c6a9f7f8fa9016960dee076",
          "sha1": "a21d17e2e04526b6b055e013eb085f3229b4d5f7",
          "md5": "8031ed76612759c644c37e424731eb7f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-1.1.1.aar",
          "url": "glance-1.1.1.aar",
          "size": 353495,
          "sha512": "9c07964cd2bc394e660da1e3e97ef2630394ecaac41d6fca85cd7592b4f7212907ecf85e655c080e10b2e40b56cbeea3d67f59a113f667b3bfea7f674eea0d9d",
          "sha256": "fbd512725b341e36ec56bc01e99f7210d4ad3aab7a6419df2e8841862bd3a8dc",
          "sha1": "70123f8e0deab43dad272887d501261bbda1013e",
          "md5": "44d609432d0a0b7cdeda1acc2b67f7c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-1.1.1.aar",
          "url": "glance-1.1.1.aar",
          "size": 353495,
          "sha512": "9c07964cd2bc394e660da1e3e97ef2630394ecaac41d6fca85cd7592b4f7212907ecf85e655c080e10b2e40b56cbeea3d67f59a113f667b3bfea7f674eea0d9d",
          "sha256": "fbd512725b341e36ec56bc01e99f7210d4ad3aab7a6419df2e8841862bd3a8dc",
          "sha1": "70123f8e0deab43dad272887d501261bbda1013e",
          "md5": "44d609432d0a0b7cdeda1acc2b67f7c8"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-1.1.1-versionMetadata.json",
          "url": "glance-1.1.1-versionMetadata.json",
          "size": 26966,
          "sha512": "067ae2b15fafd005ae11341f10fc3070c4f226936e9101beea8707e5b446403b78f9718024f6eca30aaa6f1217842f1b209df0bd442b7bc254d2627127f9060f",
          "sha256": "b4112ce0512076a84bb147551f25a3ffeb9fd50572da16923f18fc61c5a83acd",
          "sha1": "db6c1f7fcce9ef1b5fae9e1e288e19cb668cd68b",
          "md5": "0b94e328048604cd3940064fa48b2274"
        }
      ]
    }
  ]
}