{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-cli-reporter-plain-summary",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-plain-summary-1.3.1.jar",
          "url": "ktlint-cli-reporter-plain-summary-1.3.1.jar",
          "size": 13158,
          "sha512": "c7f9843c37eed658d4d713e3b3ad3aea36aa367b5715f3de08b51de9e97133c541a8338797e1aa05d2a457902076dccdad659555a7d2dcda127b4c04b1c88e3b",
          "sha256": "f572957fd859e2d61013660ba189676735028f3a3543f67b931e5780596e42ee",
          "sha1": "ed3d93bbdc2eeab906b1a7b6246ce2f47a23dc38",
          "md5": "c89bad291e2a917fd7389a2883ab87db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-plain-summary-1.3.1.jar",
          "url": "ktlint-cli-reporter-plain-summary-1.3.1.jar",
          "size": 13158,
          "sha512": "c7f9843c37eed658d4d713e3b3ad3aea36aa367b5715f3de08b51de9e97133c541a8338797e1aa05d2a457902076dccdad659555a7d2dcda127b4c04b1c88e3b",
          "sha256": "f572957fd859e2d61013660ba189676735028f3a3543f67b931e5780596e42ee",
          "sha1": "ed3d93bbdc2eeab906b1a7b6246ce2f47a23dc38",
          "md5": "c89bad291e2a917fd7389a2883ab87db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-plain-summary-1.3.1-sources.jar",
          "url": "ktlint-cli-reporter-plain-summary-1.3.1-sources.jar",
          "size": 3027,
          "sha512": "9a7c829982461608906ab3e44928c7da254f828e07430126a7058dab77711189dac0475d165f5513b3c1ba3d2da49c718eb3c398d1d5840b287c76be5537f103",
          "sha256": "17d918c60b9711a90149a06c709418ca6e07ab4835c4b683f0642d7ab0286530",
          "sha1": "4e37472b83d6a4acecec716709e38652d72e4910",
          "md5": "f8f8b5e25bb00f5de90f7867e495fb9d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-plain-summary-1.3.1-javadoc.jar",
          "url": "ktlint-cli-reporter-plain-summary-1.3.1-javadoc.jar",
          "size": 414553,
          "sha512": "c3acd62d24b7469fc451673b6495c17fcc73953bf35de8b7ab1742d4fe2e07dcc3d3d70cf2d9a6f2065089dd223aedc4ab6adb2835a06a977191d85e043a8d67",
          "sha256": "5747bb4499a617474542a80e34d5bdc89140511b80e85bed3bac2ec9928169b5",
          "sha1": "4b9cb198c81a2be1b1980cfedf115a0327412431",
          "md5": "321a0902625e6c14f59d09f929b94e2e"
        }
      ]
    }
  ]
}
