{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt.coil3",
    "module": "coil-test",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "coil-test-metadata-3.1.0.jar",
          "url": "coil-test-3.1.0.jar",
          "size": 6720,
          "sha512": "5b99f20e67087d1f0e1870c38dc910d04182d43f8113012beb9f27d5dff91bb5aad11b26dee427005c86e85d4a5d3abd9b679fc8eaa735f7d7ba88a71c7c89c6",
          "sha256": "c7261eafbb33eb582a86c1fed945e8222ad8a519020cb19d227e62e5c7dc5d69",
          "sha1": "7bf929c97e90d5c9ce27a7a74f65513b1684bf91",
          "md5": "8a6cf8b2743dbaba04c628e6bb465206"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "coil-test-kotlin-3.1.0-sources.jar",
          "url": "coil-test-3.1.0-sources.jar",
          "size": 5114,
          "sha512": "d9c0e5ba6b0ad5e53dfcdb27b726cb37f0d1934be0bc78aae4036af3396c009b33206a08cae0ac218494416e73c6592c31958af8dbe29af07c0edfecb880954e",
          "sha256": "264deeed7c70087a07b1aec3d55e8204c43c5592f97eb6d0eda9a679460810e8",
          "sha1": "f085b4b6fd69f2aaee7961714fd4bfc897eabd92",
          "md5": "71402aad174d09ce37dc2e1dad1e1b57"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-test-android/3.1.0/coil-test-android-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-android",
        "version": "3.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-test-android/3.1.0/coil-test-android-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-android",
        "version": "3.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-test-android/3.1.0/coil-test-android-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-android",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-iosarm64/3.1.0/coil-test-iosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-iosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-iosarm64/3.1.0/coil-test-iosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-iosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-iosarm64/3.1.0/coil-test-iosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-iosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-iossimulatorarm64/3.1.0/coil-test-iossimulatorarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-iossimulatorarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-iossimulatorarm64/3.1.0/coil-test-iossimulatorarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-iossimulatorarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-iossimulatorarm64/3.1.0/coil-test-iossimulatorarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-iossimulatorarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-iosx64/3.1.0/coil-test-iosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-iosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-iosx64/3.1.0/coil-test-iosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-iosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-iosx64/3.1.0/coil-test-iosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-iosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-test-js/3.1.0/coil-test-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-test-js/3.1.0/coil-test-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-test-js/3.1.0/coil-test-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-test-jvm/3.1.0/coil-test-jvm-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-jvm",
        "version": "3.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-test-jvm/3.1.0/coil-test-jvm-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-jvm",
        "version": "3.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-test-jvm/3.1.0/coil-test-jvm-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-jvm",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-macosarm64/3.1.0/coil-test-macosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-macosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-macosarm64/3.1.0/coil-test-macosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-macosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-macosarm64/3.1.0/coil-test-macosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-macosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-macosx64/3.1.0/coil-test-macosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-macosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-macosx64/3.1.0/coil-test-macosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-macosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-test-macosx64/3.1.0/coil-test-macosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-macosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-test-wasm-js/3.1.0/coil-test-wasm-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-wasm-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-test-wasm-js/3.1.0/coil-test-wasm-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-wasm-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-test-wasm-js/3.1.0/coil-test-wasm-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-test-wasm-js",
        "version": "3.1.0"
      }
    }
  ]
}
