{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-cli-reporter-format",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-format-1.3.1.jar",
          "url": "ktlint-cli-reporter-format-1.3.1.jar",
          "size": 10244,
          "sha512": "a9c5d10c96efbd55a0041a4815485c76a85c5375fece5cd00ca35b3ab9b308c3e4044ba98631cfd1316f2d0f0837f0be4d8b5aa825cf4c3ea640ede93214679a",
          "sha256": "c7cd804f4b9af9afcd6bac78f8a444ba6735d593480b1dd60aa57e2c39a84fde",
          "sha1": "90a9210622b1666a6bd970875e267449b2769381",
          "md5": "45fdb2444cd9cf67d310ad2015bc60b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-format-1.3.1.jar",
          "url": "ktlint-cli-reporter-format-1.3.1.jar",
          "size": 10244,
          "sha512": "a9c5d10c96efbd55a0041a4815485c76a85c5375fece5cd00ca35b3ab9b308c3e4044ba98631cfd1316f2d0f0837f0be4d8b5aa825cf4c3ea640ede93214679a",
          "sha256": "c7cd804f4b9af9afcd6bac78f8a444ba6735d593480b1dd60aa57e2c39a84fde",
          "sha1": "90a9210622b1666a6bd970875e267449b2769381",
          "md5": "45fdb2444cd9cf67d310ad2015bc60b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-format-1.3.1-sources.jar",
          "url": "ktlint-cli-reporter-format-1.3.1-sources.jar",
          "size": 3606,
          "sha512": "14b151fed9d5f8800d6e0ea715356f941e4de23d395ed5575fa8c25bd8b3cc95b07fd986bda392459ee6b3234a54d2c156b0b439e8fe442cbd79eda0f6e15280",
          "sha256": "9d97e4ccd2aaaa8d211faf663e3e399464b066fac348cdb585873449a235f057",
          "sha1": "a22e5d1eb2da10a6f859069862502b96d6a216da",
          "md5": "05b84e362a38d2753bc015df16208169"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-format-1.3.1-javadoc.jar",
          "url": "ktlint-cli-reporter-format-1.3.1-javadoc.jar",
          "size": 431360,
          "sha512": "efb213438076b0ffbf5e1803de033ffef4d9443718800014a785c5bbb27069a1a8649fdac48811f027e8c246e7b6c740bdcfddc5f9b3b865035cf8d28fa5d94c",
          "sha256": "0c0c764dfbee14c9a22a49dd15e8bc82650a0436b36f586129b1809578d2aba8",
          "sha1": "be5f9c721a303717d337fefd27f1af54476c93d1",
          "md5": "6be16602ad9c590c00402294faaedb20"
        }
      ]
    }
  ]
}
