{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-core",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-parser",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-tooling",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-core-1.23.7.jar",
          "url": "detekt-core-1.23.7.jar",
          "size": 269503,
          "sha512": "cae5bcdd06ecd858fc1b3ad6b5c9cb03eae21ce2beabc92f8ea0d298b42fca51a7875f49ecd92b6c22ea0c9c402f1eca92b369562450b4878f0789056b514323",
          "sha256": "a100da3ff7cc41c9a4ee1cfb6baf875da04714359a518e369673f1896ccd1e01",
          "sha1": "73494c484262be3cb8289958690edcdf63e1094b",
          "md5": "ae8aa787a684f53ad066e861224b0f38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.snakeyaml",
          "module": "snakeyaml-engine",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-metrics",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-psi-utils",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-report-html",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-report-md",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-report-txt",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-report-xml",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-report-sarif",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-utils",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-parser",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-tooling",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-core-1.23.7.jar",
          "url": "detekt-core-1.23.7.jar",
          "size": 269503,
          "sha512": "cae5bcdd06ecd858fc1b3ad6b5c9cb03eae21ce2beabc92f8ea0d298b42fca51a7875f49ecd92b6c22ea0c9c402f1eca92b369562450b4878f0789056b514323",
          "sha256": "a100da3ff7cc41c9a4ee1cfb6baf875da04714359a518e369673f1896ccd1e01",
          "sha1": "73494c484262be3cb8289958690edcdf63e1094b",
          "md5": "ae8aa787a684f53ad066e861224b0f38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-core-1.23.7-sources.jar",
          "url": "detekt-core-1.23.7-sources.jar",
          "size": 62144,
          "sha512": "41a7b09b26366af33c6a65f10cc725837594778387df3f8c3e24306781f9d7b855f22156b292781f418b60e422c5118c15a60e0be931c79cf983582567d0cbe2",
          "sha256": "85bdd614ef5dbbbe68832d77290d3626a356ae5fb14b0e033dcc65d899481750",
          "sha1": "bbdc44ce8b0d59840531d85b8e55c58fb8530484",
          "md5": "755ca26e9e059f6618b7cedfaf8fd98d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-core-1.23.7-javadoc.jar",
          "url": "detekt-core-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "431e6cead14fc7e89fac0ea690136d7d79d81b9d5013036fa58e6ca687a1d5a4c1f8d387a33391009f1606eeb63993fe863952ced2be81c1705525652d4a86c4",
          "sha256": "ad4604708f3a05d27f80c40669203f1f94cf2ef0a7f6da50e9eb710f0e73f01a",
          "sha1": "b24a695db5fa6bba8a7382edb5b8c6416830f470",
          "md5": "5ce60b8dc25017fc78b227b282c04018"
        }
      ]
    }
  ]
}
