{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-android",
    "version": "2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-core",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android",
          "version": {
            "requires": "2.14"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-android-2.14.aar",
          "url": "leakcanary-android-2.14.aar",
          "size": 4257,
          "sha512": "aff787a6bcb406dcb2dcac192a8933804460c138a19a231aa93128dd6d8a0982aa9d2a1e43b27670bc3faba6b64bd512156b0e37f97601d07ee319b40cee82f4",
          "sha256": "f24b5072d8319e191481861658a5bc3a4aeacec9be5c0b91d25ae4c437149daf",
          "sha1": "30af8fcab85cc430dccf334b0d0bc0de98cdd5fa",
          "md5": "a00e037f40cf16636c1df42d6ab8cb09"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-core",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "plumber-android",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-android-2.14.aar",
          "url": "leakcanary-android-2.14.aar",
          "size": 4257,
          "sha512": "aff787a6bcb406dcb2dcac192a8933804460c138a19a231aa93128dd6d8a0982aa9d2a1e43b27670bc3faba6b64bd512156b0e37f97601d07ee319b40cee82f4",
          "sha256": "f24b5072d8319e191481861658a5bc3a4aeacec9be5c0b91d25ae4c437149daf",
          "sha1": "30af8fcab85cc430dccf334b0d0bc0de98cdd5fa",
          "md5": "a00e037f40cf16636c1df42d6ab8cb09"
        }
      ]
    }
  ]
}
