{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.ajalt.clikt",
    "module": "clikt",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "clikt-metadata.jar",
          "url": "clikt-4.4.0.jar",
          "size": 53440,
          "sha512": "ef48d592da1db4f4966f22035ce3ec840de388849ebce3e96ca030406ff5a1960d19037c6348c8cfdb78b9de2f517d18f21412ce8df8d311fcc923f279fac0ad",
          "sha256": "a46251421080a9ec340a6f7628785420ebb2c7d09cc3b055399fa3fbaefa7686",
          "sha1": "03037168e31599220eaa315b2fa568c72902b41a",
          "md5": "8c433ae111eddb2711117739a1d1b329"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "clikt-kotlin-sources.jar",
          "url": "clikt-4.4.0-sources.jar",
          "size": 92664,
          "sha512": "6c763fd0e65c2fafc7f545438959db33411ee4d03c91b76f3b05baa31f95102307d0910e2d80bebfcd9a9b6771d228b0d51a52da18e08682f4cf75519c0e6551",
          "sha256": "b08780cfc5a48ec56a9785470304a9572dbbeca50dfbfafc352d09eeb71ee0d9",
          "sha1": "3573b2e544e550838daad5ac4a975c9fc7e68ecb",
          "md5": "b9752cb9d1b7b661df6b97993ed3444b"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../clikt-js/4.4.0/clikt-js-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-js",
        "version": "4.4.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../clikt-js/4.4.0/clikt-js-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-js",
        "version": "4.4.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../clikt-js/4.4.0/clikt-js-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-js",
        "version": "4.4.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../clikt-jvm/4.4.0/clikt-jvm-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-jvm",
        "version": "4.4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../clikt-jvm/4.4.0/clikt-jvm-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-jvm",
        "version": "4.4.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../clikt-jvm/4.4.0/clikt-jvm-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-jvm",
        "version": "4.4.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-linuxarm64/4.4.0/clikt-linuxarm64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-linuxarm64",
        "version": "4.4.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-linuxarm64/4.4.0/clikt-linuxarm64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-linuxarm64",
        "version": "4.4.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-linuxx64/4.4.0/clikt-linuxx64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-linuxx64",
        "version": "4.4.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-linuxx64/4.4.0/clikt-linuxx64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-linuxx64",
        "version": "4.4.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-macosarm64/4.4.0/clikt-macosarm64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-macosarm64",
        "version": "4.4.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-macosarm64/4.4.0/clikt-macosarm64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-macosarm64",
        "version": "4.4.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-macosarm64/4.4.0/clikt-macosarm64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-macosarm64",
        "version": "4.4.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-macosx64/4.4.0/clikt-macosx64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-macosx64",
        "version": "4.4.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-macosx64/4.4.0/clikt-macosx64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-macosx64",
        "version": "4.4.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-macosx64/4.4.0/clikt-macosx64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-macosx64",
        "version": "4.4.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-mingwx64/4.4.0/clikt-mingwx64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-mingwx64",
        "version": "4.4.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../clikt-mingwx64/4.4.0/clikt-mingwx64-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-mingwx64",
        "version": "4.4.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../clikt-wasm-js/4.4.0/clikt-wasm-js-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-wasm-js",
        "version": "4.4.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../clikt-wasm-js/4.4.0/clikt-wasm-js-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-wasm-js",
        "version": "4.4.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../clikt-wasm-js/4.4.0/clikt-wasm-js-4.4.0.module",
        "group": "com.github.ajalt.clikt",
        "module": "clikt-wasm-js",
        "version": "4.4.0"
      }
    }
  ]
}
