{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13624135"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.5.2-multiplatform-sources.jar",
          "url": "sqlite-framework-2.5.2-multiplatform-sources.jar",
          "size": 28399,
          "sha512": "ab4263df1edb35a00607e887083ac9c7bda10d73382fd8bbe926bdddd74c452b58e93b93088b53ab7ba52059c11a948d8a7e156ee5e64e85dfc97b814a0a2105",
          "sha256": "28ee54bdccf5a3dcafe866a014b26f0796997eb7c0a7f20581e745775d8bf8be",
          "sha1": "cd0ab28c144f50f4a20b2e246909cf84f513b0ce",
          "md5": "0e278083ca617f3b9b504b6194dd2bd5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "sqlite-framework-2.5.2-versionMetadata.json",
          "size": 483,
          "sha512": "ddec4d63df95c6cc0ee066e88fd1b6d93a6082373e3ddab0986aa26f647d8ea343ad2ba124b726b3fce56c5db1a50ee4e52c7294802aa261b98b3851157cd1b3",
          "sha256": "d48e94716e0096ac94608637deb949f091b7e718f3c0e44fd5d1cb4d8610448e",
          "sha1": "a25739169f0784f024e0adbb19653c5c484fe15b",
          "md5": "b11afaa8eb1e311d167976028170d472"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-metadata-2.5.2.jar",
          "url": "sqlite-framework-2.5.2.jar",
          "size": 36210,
          "sha512": "c42b39c61b25b4e8b0e3ef89c8c64bb4780b370836477d8fffec97fb8fccb7199c47f5481c022fef44a426f6f8c599ded515dcb60dbf25ea81f1d80a3f33215e",
          "sha256": "1dc0e8f5338ce55d17f4b53b082f21b3889ef11d72854243357193d141bda7ae",
          "sha1": "dfd396155a3229c8d226c2efc06223516c5a05b4",
          "md5": "48404d6ab248396fb1ad51855e9f3d4a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-kotlin-2.5.2-sources.jar",
          "url": "sqlite-framework-2.5.2-sources.jar",
          "size": 10563,
          "sha512": "85c7c053fc686de9ada01a3d8338a8f63185dfa2fe383f58628709415f5b8769dad3466f389d7cf0bca41da1645a7a90b654a313d553a032f93f4d628095a705",
          "sha256": "74cbdd2258d07815021a0f7097801a773ba5cc058dc28d8f2b430de877e6688c",
          "sha1": "f025ae3e65ab2e827bc57759c4cdb4bd346c73ca",
          "md5": "83d0dbc35716120af0b1b35f5227507f"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sqlite-framework-android/2.5.2/sqlite-framework-android-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-android",
        "version": "2.5.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sqlite-framework-android/2.5.2/sqlite-framework-android-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-android",
        "version": "2.5.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sqlite-framework-android/2.5.2/sqlite-framework-android-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-android",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosarm64/2.5.2/sqlite-framework-iosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosarm64/2.5.2/sqlite-framework-iosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosarm64/2.5.2/sqlite-framework-iosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iossimulatorarm64/2.5.2/sqlite-framework-iossimulatorarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iossimulatorarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iossimulatorarm64/2.5.2/sqlite-framework-iossimulatorarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iossimulatorarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iossimulatorarm64/2.5.2/sqlite-framework-iossimulatorarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iossimulatorarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosx64/2.5.2/sqlite-framework-iosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosx64/2.5.2/sqlite-framework-iosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosx64/2.5.2/sqlite-framework-iosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-linuxarm64/2.5.2/sqlite-framework-linuxarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-linuxarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-linuxarm64/2.5.2/sqlite-framework-linuxarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-linuxarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-linuxx64/2.5.2/sqlite-framework-linuxx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-linuxx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-linuxx64/2.5.2/sqlite-framework-linuxx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-linuxx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosarm64/2.5.2/sqlite-framework-macosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosarm64/2.5.2/sqlite-framework-macosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosarm64/2.5.2/sqlite-framework-macosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosx64/2.5.2/sqlite-framework-macosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosx64/2.5.2/sqlite-framework-macosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosx64/2.5.2/sqlite-framework-macosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosx64",
        "version": "2.5.2"
      }
    }
  ]
}