{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-report-txt",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-report-txt-1.23.7.jar",
          "url": "detekt-report-txt-1.23.7.jar",
          "size": 3480,
          "sha512": "63cce16fe8593b0bb88412d7a7a24e380d06baa8b3d0599e134bd13a86a8d32fc5eea38e5daeffabf72a2fc427abdc77f0ced6e5faf77f6a70df8808418367de",
          "sha256": "34a7bee9da3c414bb69547b72ceaeab799b98a63b082b2c826460b5421c64c70",
          "sha1": "d4ea3492c42dc7c94eb3ffaf172e8eb90ce4440a",
          "md5": "5b79f8d4d13761c74b09ac7966d172f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-report-txt-1.23.7.jar",
          "url": "detekt-report-txt-1.23.7.jar",
          "size": 3480,
          "sha512": "63cce16fe8593b0bb88412d7a7a24e380d06baa8b3d0599e134bd13a86a8d32fc5eea38e5daeffabf72a2fc427abdc77f0ced6e5faf77f6a70df8808418367de",
          "sha256": "34a7bee9da3c414bb69547b72ceaeab799b98a63b082b2c826460b5421c64c70",
          "sha1": "d4ea3492c42dc7c94eb3ffaf172e8eb90ce4440a",
          "md5": "5b79f8d4d13761c74b09ac7966d172f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-report-txt-1.23.7-sources.jar",
          "url": "detekt-report-txt-1.23.7-sources.jar",
          "size": 1730,
          "sha512": "ed2e1575dc4f1288021348f3de041f3d8ac441cf5a3d600de40014629e17165ab30a1693d585dcf7c3ae492e67a55be8187ddb61ecde2c26fb2760b9267eb8bf",
          "sha256": "8d7a3cafe7fb20a363e4f88afeb0af95093a222770a5376625824b5a2f083e5c",
          "sha1": "f8e0d5cdb7f39a979d75d504f518002f7ccc9608",
          "md5": "f778b29870005b888c2eeb3479387c7b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-report-txt-1.23.7-javadoc.jar",
          "url": "detekt-report-txt-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "431e6cead14fc7e89fac0ea690136d7d79d81b9d5013036fa58e6ca687a1d5a4c1f8d387a33391009f1606eeb63993fe863952ced2be81c1705525652d4a86c4",
          "sha256": "ad4604708f3a05d27f80c40669203f1f94cf2ef0a7f6da50e9eb710f0e73f01a",
          "sha1": "b24a695db5fa6bba8a7382edb5b8c6416830f470",
          "md5": "5ce60b8dc25017fc78b227b282c04018"
        }
      ]
    }
  ]
}
