{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-ktx",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-ktx-1.1.0.aar",
          "url": "tracing-ktx-1.1.0.aar",
          "size": 4749,
          "sha512": "6b9677edb7f069c7e18f0792e06135bed7057689db8d748dbe36e72547e621e7443a8edf69bbb1d84c003cf5b544ad0e9b7785c0ccdbbc6b9b9fc94e81b38267",
          "sha256": "914d8c83aa16455d431b5b3af306cef0eb0a0bfd6550d097e39ad475435bf56c",
          "sha1": "5a3f6958126cabf68ad687c4a2b16c82dc99a719",
          "md5": "152c61c428a5c03a8ca07f1b21191839"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-ktx-1.1.0.aar",
          "url": "tracing-ktx-1.1.0.aar",
          "size": 4749,
          "sha512": "6b9677edb7f069c7e18f0792e06135bed7057689db8d748dbe36e72547e621e7443a8edf69bbb1d84c003cf5b544ad0e9b7785c0ccdbbc6b9b9fc94e81b38267",
          "sha256": "914d8c83aa16455d431b5b3af306cef0eb0a0bfd6550d097e39ad475435bf56c",
          "sha1": "5a3f6958126cabf68ad687c4a2b16c82dc99a719",
          "md5": "152c61c428a5c03a8ca07f1b21191839"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracing-ktx-1.1.0-sources.jar",
          "url": "tracing-ktx-1.1.0-sources.jar",
          "size": 1334,
          "sha512": "738301256779bb65be0b14423db1932c998b8503c43927bd30902ec6aaadb68067eeac5df583f5dd822d6d7c90c1030eb97ad702d7c0b0f985a2f162a976365f",
          "sha256": "cf07a2971dddd5915763036d8e201d4204e3ce133d02d0f56c1ea8f8910e1fcf",
          "sha1": "93ffc4caaa93928bb7af504476d3144ca57947f9",
          "md5": "3c7bd1ac753e2e66dcb6e7598c525e1b"
        }
      ]
    }
  ]
}