{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-io-bytestring",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-bytestring-metadata-0.3.3.jar",
          "url": "kotlinx-io-bytestring-0.3.3.jar",
          "size": 10118,
          "sha512": "4f37c43353208fb9dd0890fbbde9d2ad60881391bbb780591d1a6a9f3255fb31f84edc52103282ff2e5b7942114552dc98bf4f04c75d8bd5fd85867061f03ff7",
          "sha256": "a22b6173d12013133b774ed2ea4ff94be91125c277f8bc42a1598c5fa16b79b0",
          "sha1": "d4115561faebbcb0014fb4c9d40050d118f03210",
          "md5": "b9d21c8d3fa1a64c15ce178da0767d28"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-io-bytestring-kotlin-0.3.3-sources.jar",
          "url": "kotlinx-io-bytestring-0.3.3-sources.jar",
          "size": 11442,
          "sha512": "a6748f62971d03ef30651941d475c9dc44b9bcf83e8783ce03d4b3876a9487bebc6b3a53fe1061437a71794c67b567ec89985e58342251a1aa10da9fe2983c62",
          "sha256": "868b39fb56a0b6d87ff49329040e540de8044ed24c2f252e896433fa173d3acb",
          "sha1": "67c6ce4337dc9813e76d379ee796868f8590224a",
          "md5": "817511524571dedf7fc2724acdd8fcec"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativearm32/0.3.3/kotlinx-io-bytestring-androidnativearm32-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativearm32",
        "version": "0.3.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativearm32/0.3.3/kotlinx-io-bytestring-androidnativearm32-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativearm32",
        "version": "0.3.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativearm64/0.3.3/kotlinx-io-bytestring-androidnativearm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativearm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativearm64/0.3.3/kotlinx-io-bytestring-androidnativearm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativearm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativex64/0.3.3/kotlinx-io-bytestring-androidnativex64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativex64",
        "version": "0.3.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativex64/0.3.3/kotlinx-io-bytestring-androidnativex64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativex64",
        "version": "0.3.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativex86/0.3.3/kotlinx-io-bytestring-androidnativex86-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativex86",
        "version": "0.3.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativex86/0.3.3/kotlinx-io-bytestring-androidnativex86-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativex86",
        "version": "0.3.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosarm64/0.3.3/kotlinx-io-bytestring-iosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosarm64/0.3.3/kotlinx-io-bytestring-iosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosarm64/0.3.3/kotlinx-io-bytestring-iosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iossimulatorarm64/0.3.3/kotlinx-io-bytestring-iossimulatorarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iossimulatorarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iossimulatorarm64/0.3.3/kotlinx-io-bytestring-iossimulatorarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iossimulatorarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iossimulatorarm64/0.3.3/kotlinx-io-bytestring-iossimulatorarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iossimulatorarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosx64/0.3.3/kotlinx-io-bytestring-iosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosx64/0.3.3/kotlinx-io-bytestring-iosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosx64/0.3.3/kotlinx-io-bytestring-iosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-js/0.3.3/kotlinx-io-bytestring-js-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-js",
        "version": "0.3.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-js/0.3.3/kotlinx-io-bytestring-js-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-js",
        "version": "0.3.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-js/0.3.3/kotlinx-io-bytestring-js-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-js",
        "version": "0.3.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-jvm/0.3.3/kotlinx-io-bytestring-jvm-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-jvm",
        "version": "0.3.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-jvm/0.3.3/kotlinx-io-bytestring-jvm-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-jvm",
        "version": "0.3.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-jvm/0.3.3/kotlinx-io-bytestring-jvm-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-jvm",
        "version": "0.3.3"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-linuxarm64/0.3.3/kotlinx-io-bytestring-linuxarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-linuxarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-linuxarm64/0.3.3/kotlinx-io-bytestring-linuxarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-linuxarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-linuxx64/0.3.3/kotlinx-io-bytestring-linuxx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-linuxx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-linuxx64/0.3.3/kotlinx-io-bytestring-linuxx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-linuxx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosarm64/0.3.3/kotlinx-io-bytestring-macosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosarm64/0.3.3/kotlinx-io-bytestring-macosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosarm64/0.3.3/kotlinx-io-bytestring-macosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosx64/0.3.3/kotlinx-io-bytestring-macosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosx64/0.3.3/kotlinx-io-bytestring-macosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosx64/0.3.3/kotlinx-io-bytestring-macosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-mingwx64/0.3.3/kotlinx-io-bytestring-mingwx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-mingwx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-mingwx64/0.3.3/kotlinx-io-bytestring-mingwx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-mingwx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosarm64/0.3.3/kotlinx-io-bytestring-tvosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosarm64/0.3.3/kotlinx-io-bytestring-tvosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosarm64/0.3.3/kotlinx-io-bytestring-tvosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvossimulatorarm64/0.3.3/kotlinx-io-bytestring-tvossimulatorarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvossimulatorarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvossimulatorarm64/0.3.3/kotlinx-io-bytestring-tvossimulatorarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvossimulatorarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvossimulatorarm64/0.3.3/kotlinx-io-bytestring-tvossimulatorarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvossimulatorarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosx64/0.3.3/kotlinx-io-bytestring-tvosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosx64/0.3.3/kotlinx-io-bytestring-tvosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosx64/0.3.3/kotlinx-io-bytestring-tvosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-js/0.3.3/kotlinx-io-bytestring-wasm-js-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-js",
        "version": "0.3.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-js/0.3.3/kotlinx-io-bytestring-wasm-js-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-js",
        "version": "0.3.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-js/0.3.3/kotlinx-io-bytestring-wasm-js-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-js",
        "version": "0.3.3"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-wasi/0.3.3/kotlinx-io-bytestring-wasm-wasi-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-wasi",
        "version": "0.3.3"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-wasi/0.3.3/kotlinx-io-bytestring-wasm-wasi-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-wasi",
        "version": "0.3.3"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-wasi/0.3.3/kotlinx-io-bytestring-wasm-wasi-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-wasi",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm32/0.3.3/kotlinx-io-bytestring-watchosarm32-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm32",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm32/0.3.3/kotlinx-io-bytestring-watchosarm32-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm32",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm32/0.3.3/kotlinx-io-bytestring-watchosarm32-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm32",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm64/0.3.3/kotlinx-io-bytestring-watchosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm64/0.3.3/kotlinx-io-bytestring-watchosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm64/0.3.3/kotlinx-io-bytestring-watchosarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosdevicearm64/0.3.3/kotlinx-io-bytestring-watchosdevicearm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosdevicearm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosdevicearm64/0.3.3/kotlinx-io-bytestring-watchosdevicearm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosdevicearm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosdevicearm64/0.3.3/kotlinx-io-bytestring-watchosdevicearm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosdevicearm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchossimulatorarm64/0.3.3/kotlinx-io-bytestring-watchossimulatorarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchossimulatorarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchossimulatorarm64/0.3.3/kotlinx-io-bytestring-watchossimulatorarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchossimulatorarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchossimulatorarm64/0.3.3/kotlinx-io-bytestring-watchossimulatorarm64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchossimulatorarm64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosx64/0.3.3/kotlinx-io-bytestring-watchosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosx64/0.3.3/kotlinx-io-bytestring-watchosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosx64",
        "version": "0.3.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosx64/0.3.3/kotlinx-io-bytestring-watchosx64-0.3.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosx64",
        "version": "0.3.3"
      }
    }
  ]
}
