{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-cli-reporter-checkstyle",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-checkstyle-1.3.1.jar",
          "url": "ktlint-cli-reporter-checkstyle-1.3.1.jar",
          "size": 7361,
          "sha512": "ac8e5f8988627f7b1d6fa65d40936839b326294441d080436e8a00441182fa50c76ebea0ff5bc144135ebcc05fdb6f9432bb9f2af31137166fb527188ed828a7",
          "sha256": "25afaffea3ed5d300715972eedfc13e1fe66cf81a796c8ec9aeea55964f9f48a",
          "sha1": "9db310271088e386535e6744ff5da40bb163a1d9",
          "md5": "353b36dc92b61dfdd52bc85015f4c967"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-checkstyle-1.3.1.jar",
          "url": "ktlint-cli-reporter-checkstyle-1.3.1.jar",
          "size": 7361,
          "sha512": "ac8e5f8988627f7b1d6fa65d40936839b326294441d080436e8a00441182fa50c76ebea0ff5bc144135ebcc05fdb6f9432bb9f2af31137166fb527188ed828a7",
          "sha256": "25afaffea3ed5d300715972eedfc13e1fe66cf81a796c8ec9aeea55964f9f48a",
          "sha1": "9db310271088e386535e6744ff5da40bb163a1d9",
          "md5": "353b36dc92b61dfdd52bc85015f4c967"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-checkstyle-1.3.1-sources.jar",
          "url": "ktlint-cli-reporter-checkstyle-1.3.1-sources.jar",
          "size": 2723,
          "sha512": "88c154fb3d3070db7811a2cf92cc564006f3cbba5ff8fc5bd0ed0b851558d573a5a8a372f3bfef2802cd41803d8d60448fe226ab48a32992eb7d150a7837bdba",
          "sha256": "4bcb1b4c1d6603816b70d0708d0f7934ba2543280eb67f116dc0d586c283aa61",
          "sha1": "f6ddea404513cebe134b591609cf257510930704",
          "md5": "a827af04e0c1eeb37784ac776d2a655f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-checkstyle-1.3.1-javadoc.jar",
          "url": "ktlint-cli-reporter-checkstyle-1.3.1-javadoc.jar",
          "size": 412683,
          "sha512": "e2acb09d7f2f733c83bca592b7f70171e5a702d006a189b846de315c67f10ad7d94d23c72c3125624e430eb2ee04889d3b30841e710696e9a1e8a01c85432e03",
          "sha256": "afa48b521fc2ad4b5729fc9aedab2cb60a8454b71104f949a0655b0378cdb6b6",
          "sha1": "c7d118da6978450c41405501d643be2c425449c3",
          "md5": "878666c46c1cb773d427a99580dd2a19"
        }
      ]
    }
  ]
}
