{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-report-sarif",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-report-sarif-1.23.7.jar",
          "url": "detekt-report-sarif-1.23.7.jar",
          "size": 17887,
          "sha512": "2bc52f76853f70f15b209fbb661569ed09c8226e34ba781d770280748b6644942815b19a3a4f166f86b57b35f8e3696f2bd54b4326ea89bd9a34b973bf881950",
          "sha256": "0bb1ecf6dd43758d193d99dd02333da3afc2bfc21238139fe319f586714b9b1d",
          "sha1": "e61f34106354a854f9b4b12618ab9a5125b888d8",
          "md5": "d409dc7c72777677a41d9ca6c582e5f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.detekt.sarif4k",
          "module": "sarif4k",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-report-sarif-1.23.7.jar",
          "url": "detekt-report-sarif-1.23.7.jar",
          "size": 17887,
          "sha512": "2bc52f76853f70f15b209fbb661569ed09c8226e34ba781d770280748b6644942815b19a3a4f166f86b57b35f8e3696f2bd54b4326ea89bd9a34b973bf881950",
          "sha256": "0bb1ecf6dd43758d193d99dd02333da3afc2bfc21238139fe319f586714b9b1d",
          "sha1": "e61f34106354a854f9b4b12618ab9a5125b888d8",
          "md5": "d409dc7c72777677a41d9ca6c582e5f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-report-sarif-1.23.7-sources.jar",
          "url": "detekt-report-sarif-1.23.7-sources.jar",
          "size": 4541,
          "sha512": "b5f9c424cc06516a39d709a9bfe665dcb207c6ec17f10a8a3773eab3d9b7f9f8e5e91d8ffd905b0c3c946da9c6351719feabf8b6880ea6f085c9c07968738d80",
          "sha256": "990bc0a2d973b7ffab01c218cc428504d93dacb76e668d58ad0d23da156276d3",
          "sha1": "53f7fd90d78b8da3adc507680db3befc1534c0bf",
          "md5": "1e582c7df8ff461b2523bd63fd3dd55c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-report-sarif-1.23.7-javadoc.jar",
          "url": "detekt-report-sarif-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "431e6cead14fc7e89fac0ea690136d7d79d81b9d5013036fa58e6ca687a1d5a4c1f8d387a33391009f1606eeb63993fe863952ced2be81c1705525652d4a86c4",
          "sha256": "ad4604708f3a05d27f80c40669203f1f94cf2ef0a7f6da50e9eb710f0e73f01a",
          "sha1": "b24a695db5fa6bba8a7382edb5b8c6416830f470",
          "md5": "5ce60b8dc25017fc78b227b282c04018"
        }
      ]
    }
  ]
}
