{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-core",
    "version": "5.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-api",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-metadata-5.9.1.jar",
          "url": "kotest-assertions-core-5.9.1.jar",
          "size": 50429,
          "sha512": "7ee9a4a55c37a2f43533aa6a45323d60db230bd769c8f9abc28e209f75baa70524a928ec07d8120cb156dec4d925bcc0f3fc550e357eb39dcedca849bdd32050",
          "sha256": "fc49ba2f9cf573e9c570eca31e41f4666e48f459e62f3a419c9d1efe8b9b1927",
          "sha1": "4d52ed7b702f9d57797564a879aec72170d5ea1d",
          "md5": "45a1a9a83befd636dc55666c13cc03c0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-core-kotlin-5.9.1-sources.jar",
          "url": "kotest-assertions-core-5.9.1-sources.jar",
          "size": 92786,
          "sha512": "2f2ddb4ee644a92c851b8d8ae1b847df324a12da3f9d8f9853cb7c82ba91b42950533f6bba9f7aef851a381780beff46b505590bf45b6d8d202dbbdfb990c903",
          "sha256": "27cb0aafeeb5fc78bf8228d70925176aa99feb9f1ac5574ce655795748bb4343",
          "sha1": "1436c77d273565ea2862e67a3907c0b3bdb9a114",
          "md5": "a4b30ed8aaaec32cbdad608723623268"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm32/5.9.1/kotest-assertions-core-androidnativearm32-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm32",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm32/5.9.1/kotest-assertions-core-androidnativearm32-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm32",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm64/5.9.1/kotest-assertions-core-androidnativearm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm64/5.9.1/kotest-assertions-core-androidnativearm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex64/5.9.1/kotest-assertions-core-androidnativex64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex64",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex64/5.9.1/kotest-assertions-core-androidnativex64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex64",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex86/5.9.1/kotest-assertions-core-androidnativex86-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex86",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex86/5.9.1/kotest-assertions-core-androidnativex86-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex86",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosarm64/5.9.1/kotest-assertions-core-iosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosarm64/5.9.1/kotest-assertions-core-iosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosarm64/5.9.1/kotest-assertions-core-iosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iossimulatorarm64/5.9.1/kotest-assertions-core-iossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iossimulatorarm64/5.9.1/kotest-assertions-core-iossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iossimulatorarm64/5.9.1/kotest-assertions-core-iossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosx64/5.9.1/kotest-assertions-core-iosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosx64/5.9.1/kotest-assertions-core-iosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosx64/5.9.1/kotest-assertions-core-iosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-js/5.9.1/kotest-assertions-core-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-js/5.9.1/kotest-assertions-core-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-js/5.9.1/kotest-assertions-core-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-jvm/5.9.1/kotest-assertions-core-jvm-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-jvm",
        "version": "5.9.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-jvm/5.9.1/kotest-assertions-core-jvm-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-jvm",
        "version": "5.9.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-jvm/5.9.1/kotest-assertions-core-jvm-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-jvm",
        "version": "5.9.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-linuxarm64/5.9.1/kotest-assertions-core-linuxarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-linuxarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-linuxarm64/5.9.1/kotest-assertions-core-linuxarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-linuxarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-linuxx64/5.9.1/kotest-assertions-core-linuxx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-linuxx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-linuxx64/5.9.1/kotest-assertions-core-linuxx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-linuxx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosarm64/5.9.1/kotest-assertions-core-macosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosarm64/5.9.1/kotest-assertions-core-macosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosarm64/5.9.1/kotest-assertions-core-macosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosx64/5.9.1/kotest-assertions-core-macosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosx64/5.9.1/kotest-assertions-core-macosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosx64/5.9.1/kotest-assertions-core-macosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-mingwx64/5.9.1/kotest-assertions-core-mingwx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-mingwx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-mingwx64/5.9.1/kotest-assertions-core-mingwx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-mingwx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosarm64/5.9.1/kotest-assertions-core-tvosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosarm64/5.9.1/kotest-assertions-core-tvosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosarm64/5.9.1/kotest-assertions-core-tvosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvossimulatorarm64/5.9.1/kotest-assertions-core-tvossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvossimulatorarm64/5.9.1/kotest-assertions-core-tvossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvossimulatorarm64/5.9.1/kotest-assertions-core-tvossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosx64/5.9.1/kotest-assertions-core-tvosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosx64/5.9.1/kotest-assertions-core-tvosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosx64/5.9.1/kotest-assertions-core-tvosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-js/5.9.1/kotest-assertions-core-wasm-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-js/5.9.1/kotest-assertions-core-wasm-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-js/5.9.1/kotest-assertions-core-wasm-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm32/5.9.1/kotest-assertions-core-watchosarm32-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm32",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm32/5.9.1/kotest-assertions-core-watchosarm32-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm32",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm32/5.9.1/kotest-assertions-core-watchosarm32-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm32",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm64/5.9.1/kotest-assertions-core-watchosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm64/5.9.1/kotest-assertions-core-watchosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm64/5.9.1/kotest-assertions-core-watchosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosdevicearm64/5.9.1/kotest-assertions-core-watchosdevicearm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosdevicearm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosdevicearm64/5.9.1/kotest-assertions-core-watchosdevicearm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosdevicearm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosdevicearm64/5.9.1/kotest-assertions-core-watchosdevicearm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosdevicearm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchossimulatorarm64/5.9.1/kotest-assertions-core-watchossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchossimulatorarm64/5.9.1/kotest-assertions-core-watchossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchossimulatorarm64/5.9.1/kotest-assertions-core-watchossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosx64/5.9.1/kotest-assertions-core-watchosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosx64/5.9.1/kotest-assertions-core-watchosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosx64/5.9.1/kotest-assertions-core-watchosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosx64",
        "version": "5.9.1"
      }
    }
  ]
}
