{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-agent-android",
    "version": "1.13.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-android-1.13.13.aar",
          "url": "mockk-agent-android-1.13.13.aar",
          "size": 1511950,
          "sha512": "4676fbdffcc13848ce3bf04d5031e998af5649abf572d1a58016e521ef8791e6c6a705d51ad15c9cd867bb94b88e66ee8b77247f028fad4c23dc37f2b9e4c9f3",
          "sha256": "09ecaedf5fef5abf1a78573f1e8ac64bf034be3a32a6d9e6c09d93bac24fdf3b",
          "sha1": "83312c18c2b4ac0e5c3a8863b859b2474aab846c",
          "md5": "32e1ecd3434d60850a01051fbdf72438"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-core",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.linkedin.dexmaker",
          "module": "dexmaker",
          "version": {
            "requires": "2.28.3"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-android-1.13.13.aar",
          "url": "mockk-agent-android-1.13.13.aar",
          "size": 1511950,
          "sha512": "4676fbdffcc13848ce3bf04d5031e998af5649abf572d1a58016e521ef8791e6c6a705d51ad15c9cd867bb94b88e66ee8b77247f028fad4c23dc37f2b9e4c9f3",
          "sha256": "09ecaedf5fef5abf1a78573f1e8ac64bf034be3a32a6d9e6c09d93bac24fdf3b",
          "sha1": "83312c18c2b4ac0e5c3a8863b859b2474aab846c",
          "md5": "32e1ecd3434d60850a01051fbdf72438"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mockk-agent-android-1.13.13-sources.jar",
          "url": "mockk-agent-android-1.13.13-sources.jar",
          "size": 40521,
          "sha512": "baf6129c70034dada3068994cce64e5eb4bb135c246fdd5e3184c1d1d98ba634825c53d1c80801fbeddafeff0a8f4867d307009be7a3b51e6bc33fdd45ec6581",
          "sha256": "5aeb2179487ddcb3ab4826fc4d7db7f20b6c35ad2a629e83189da3c71c1da6bc",
          "sha1": "8244e8ed96aaffd706c89eca2e090e969a229878",
          "md5": "6d1cf4f24865d004e91f7ffe4882e096"
        }
      ]
    }
  ]
}
