{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget-testing",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-1.1.1-sources.jar",
          "url": "glance-appwidget-testing-1.1.1-sources.jar",
          "size": 10895,
          "sha512": "2c5c2949793898c66a22badabbe83e7fa3136efd4bb52769f81f07f95280f9bf0d066fd1cce95cbc12ac19596e69dda43efac60c5dbf2d400f044d6ddea0e4e8",
          "sha256": "cafa7a9dad1aee3e38775a3a77ed4ed0b21706fbbc9fd489cc76df90926972b1",
          "sha1": "b821fcd4522993df222ddadfb8b7ca03ee8b967a",
          "md5": "dfcc967a52539dd67ecc01799906c2c1"
        },
        {
          "name": "glance-appwidget-testing-1.1.1-samples-sources.jar",
          "url": "glance-appwidget-testing-1.1.1-samples-sources.jar",
          "size": 2215,
          "sha512": "37958345ae3514af9f0f49d0f3156e0e081a1832a1fc69ab3e6a2f7822b15660a0a6bad068841cd0a5c2f61ee04fcb4070079174ae1b98b30d07fa34c2072ce8",
          "sha256": "7b23681810036e258476c1b234de669d24ea252d9ffd157bb4a95802d2393de3",
          "sha1": "688704d1b3d925ff9ccc89af28694043308aba40",
          "md5": "6eaae4193c27d8b7a6186cf622626dec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-1.1.1.aar",
          "url": "glance-appwidget-testing-1.1.1.aar",
          "size": 58289,
          "sha512": "fc9d546f9a091a6c963246b3b8ac3a7c5e050e7cc56a1fc9fe422f79bc0079ebffe5ef805161890cb4624a290534645b96df53f43e8d482b64124c539755fe2b",
          "sha256": "57445aa80b02ffc2401c0f4e008e38046391126df0412fb06a91dbca27658c8a",
          "sha1": "40ac9946be841a9981d9794c81ac3ca9553a7565",
          "md5": "c873dfdec62260f8c5e89760f9d4b9de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-1.1.1.aar",
          "url": "glance-appwidget-testing-1.1.1.aar",
          "size": 58289,
          "sha512": "fc9d546f9a091a6c963246b3b8ac3a7c5e050e7cc56a1fc9fe422f79bc0079ebffe5ef805161890cb4624a290534645b96df53f43e8d482b64124c539755fe2b",
          "sha256": "57445aa80b02ffc2401c0f4e008e38046391126df0412fb06a91dbca27658c8a",
          "sha1": "40ac9946be841a9981d9794c81ac3ca9553a7565",
          "md5": "c873dfdec62260f8c5e89760f9d4b9de"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-1.1.1-versionMetadata.json",
          "url": "glance-appwidget-testing-1.1.1-versionMetadata.json",
          "size": 4994,
          "sha512": "f795fcc7a9690bb73454251f978f39893baf98fc5f1facfc78829b2c99bf85fd8cdc78b359649abc9c35f70e31ed8ad4323d7e32df5d5d54ec0109f4465f06dc",
          "sha256": "d78f450d2449a3902b14e122bb8418d1d86df52d7cb4c9f00bea5702c2fe2a0b",
          "sha1": "443c86fdec8f60821eb82fb243eec5d758697943",
          "md5": "df4c7b52420d0ba81cf3eb6ed5c0cc02"
        }
      ]
    }
  ]
}