{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-tooling",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-tooling-1.23.7.jar",
          "url": "detekt-tooling-1.23.7.jar",
          "size": 94699,
          "sha512": "c45092d0bd3d854879ca8e892fe34f2ed61a553b36078f828cb04079881016f5a36067fd904e27131a46e38cbf566901afce352dcfca71c610384e9285832bd2",
          "sha256": "7a148ecfd983ee258a67eb8bb194bda7d628a3b85fa9283a29c5b1d4a7e9d02d",
          "sha1": "cadeb9c20ee8c9f9c3b5497d148488a7dfba48d6",
          "md5": "4c735d143d1eff7b26779c7168060454"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-tooling-1.23.7.jar",
          "url": "detekt-tooling-1.23.7.jar",
          "size": 94699,
          "sha512": "c45092d0bd3d854879ca8e892fe34f2ed61a553b36078f828cb04079881016f5a36067fd904e27131a46e38cbf566901afce352dcfca71c610384e9285832bd2",
          "sha256": "7a148ecfd983ee258a67eb8bb194bda7d628a3b85fa9283a29c5b1d4a7e9d02d",
          "sha1": "cadeb9c20ee8c9f9c3b5497d148488a7dfba48d6",
          "md5": "4c735d143d1eff7b26779c7168060454"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-tooling-1.23.7-sources.jar",
          "url": "detekt-tooling-1.23.7-sources.jar",
          "size": 19546,
          "sha512": "b84982ea58b1628f313481353436c5b6a413360d42d2fc927c64a5fe0af2fc4b14509526dede8e286bb607696167562df34172d4c527cdd950d57fca180c27ca",
          "sha256": "a2296d8657dd69986ea30353a9e173f2c4902df63a0e6ecabe82f6af8593606e",
          "sha1": "294eedf9cdb11307247fb4e33616ce6ccf068ba4",
          "md5": "87b1f01c9739ed7914239677b6e276b3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-tooling-1.23.7-javadoc.jar",
          "url": "detekt-tooling-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "431e6cead14fc7e89fac0ea690136d7d79d81b9d5013036fa58e6ca687a1d5a4c1f8d387a33391009f1606eeb63993fe863952ced2be81c1705525652d4a86c4",
          "sha256": "ad4604708f3a05d27f80c40669203f1f94cf2ef0a7f6da50e9eb710f0e73f01a",
          "sha1": "b24a695db5fa6bba8a7382edb5b8c6416830f470",
          "md5": "5ce60b8dc25017fc78b227b282c04018"
        }
      ]
    }
  ]
}
