{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite/2.5.2/sqlite-2.5.2.module",
    "group": "androidx.sqlite",
    "module": "sqlite",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13624135"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-release.aar",
          "url": "sqlite-android-2.5.2.aar",
          "size": 39449,
          "sha512": "c403691aef86761d08e72dfe3d9c7c57a39494ce8d76374acd566f412ae95353adf9f397b1190b8ae44c6f8c22f1069e79e5376196d7d04b1e72444e6fd55e3d",
          "sha256": "0f68f9d9ffd6fb88c3a7d14bb98484cd939d6a312c2f73ae77ff74ae83d239ee",
          "sha1": "7aac7c51982c21450608c7cee0e0b88e687e5407",
          "md5": "a1b2b9001091fc492a1bec2e52646712"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-release.aar",
          "url": "sqlite-android-2.5.2.aar",
          "size": 39449,
          "sha512": "c403691aef86761d08e72dfe3d9c7c57a39494ce8d76374acd566f412ae95353adf9f397b1190b8ae44c6f8c22f1069e79e5376196d7d04b1e72444e6fd55e3d",
          "sha256": "0f68f9d9ffd6fb88c3a7d14bb98484cd939d6a312c2f73ae77ff74ae83d239ee",
          "sha1": "7aac7c51982c21450608c7cee0e0b88e687e5407",
          "md5": "a1b2b9001091fc492a1bec2e52646712"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-android-2.5.2-sources.jar",
          "url": "sqlite-android-2.5.2-sources.jar",
          "size": 30929,
          "sha512": "2c9c84963bf14734d9afe60c62884cd6dd7fe242f10eb8585b2eae1b33836a51e4a816d3437c3a85eaabfe2161516c9b696a52cb029d7123c9667fa4a525e647",
          "sha256": "4c16014ac7f20b390ec2705b505521e270198bf86109582abb31552396a8dda1",
          "sha1": "8c7d5473ac321276f82817f2c3725d9a4209015b",
          "md5": "bb333fd5be4ebb99b75fc15a8e32f28b"
        }
      ]
    }
  ]
}