{
  "formatVersion": "1.1",
  "component": {
    "url": "../../markdown/0.7.0/markdown-0.7.0.module",
    "group": "org.jetbrains",
    "module": "markdown",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil-core",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "markdown-jvm-0.7.0.jar",
          "url": "markdown-jvm-0.7.0.jar",
          "size": 549818,
          "sha512": "6bd49930585fbce0a4a8dcff60d0d44f74337a4c25a0fcaeb394a61f4fc6909e09057e95f231bb2dddc20dcf94fb379370a208989f1fc145632750105ac8e1e1",
          "sha256": "c8b44be338598912e8bb8a4998b017df7dd198152cceffef01cf128a9900139e",
          "sha1": "c8b49c1837fbaf1403a8e63e3510ce8018aa720a",
          "md5": "bf1a239275e09bfc530445fbd1466f69"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil-core",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "markdown-jvm-0.7.0.jar",
          "url": "markdown-jvm-0.7.0.jar",
          "size": 549818,
          "sha512": "6bd49930585fbce0a4a8dcff60d0d44f74337a4c25a0fcaeb394a61f4fc6909e09057e95f231bb2dddc20dcf94fb379370a208989f1fc145632750105ac8e1e1",
          "sha256": "c8b44be338598912e8bb8a4998b017df7dd198152cceffef01cf128a9900139e",
          "sha1": "c8b49c1837fbaf1403a8e63e3510ce8018aa720a",
          "md5": "bf1a239275e09bfc530445fbd1466f69"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "markdown-jvm-0.7.0-sources.jar",
          "url": "markdown-jvm-0.7.0-sources.jar",
          "size": 190094,
          "sha512": "aad9b10b19c085b9b70a8670c30828f0544ee74fa46864b7a3f57f86ea285525548978506c74f49a8f8cba932939c0ca4c925da8da89e96ec878e748b1fe7ae9",
          "sha256": "a036bd540d24bbb246bd3d9e19afc28493f10bb04657e11c8006b9ff6559544f",
          "sha1": "89ed9b1512448c896cd44211c8c45375d7ece1a1",
          "md5": "25452bb4d9a3567a4ab5e46636dbded8"
        }
      ]
    }
  ]
}
