{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0-sources.jar",
          "url": "work-runtime-2.10.0-sources.jar",
          "size": 303376,
          "sha512": "ef5bdf1eb46835c88d24c0e4ef32ae2d8ea77d625b034fd67350cb309f2dba49eb8719eefc58ca99f159498650aa8a746e2552870dfdc3018ea1a8871203ce6a",
          "sha256": "98ed08ca5adf7aaaa25c4fff67058f151d0622d8af098a71d095618deae5f22b",
          "sha1": "9654bb1f20f83973b55a8830c5677c5e2898861f",
          "md5": "3ec59efaae325061edb01e8b7357827d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0.aar",
          "url": "work-runtime-2.10.0.aar",
          "size": 2013569,
          "sha512": "029bdfa8b9615b290024a7b2849ec7da280576d97b8afd3e0bae308d93ab48244a2ce4a382601738e20c979b8695342e2caabb3bb468afeeb151242c1411e513",
          "sha256": "2ee10cd3345a7e6e37d50898fd0ebdd91e4a59267aa928effa8e507dae85c88b",
          "sha1": "021650ae67cd0ea71cc92103b94758848f908f9a",
          "md5": "96478744f5c0b6f2430e7adba2897331"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0.aar",
          "url": "work-runtime-2.10.0.aar",
          "size": 2013569,
          "sha512": "029bdfa8b9615b290024a7b2849ec7da280576d97b8afd3e0bae308d93ab48244a2ce4a382601738e20c979b8695342e2caabb3bb468afeeb151242c1411e513",
          "sha256": "2ee10cd3345a7e6e37d50898fd0ebdd91e4a59267aa928effa8e507dae85c88b",
          "sha1": "021650ae67cd0ea71cc92103b94758848f908f9a",
          "md5": "96478744f5c0b6f2430e7adba2897331"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0-versionMetadata.json",
          "url": "work-runtime-2.10.0-versionMetadata.json",
          "size": 37017,
          "sha512": "7b90f8542b7c869e96442cb23c58bb6b20ae4632740b1dee4219d1877f84ede36b7166ed268f24ce7e7a59fe662167d510cfa572b775602708e741fbad02f256",
          "sha256": "c1544bf0b0b21a2b93a2347eb1d35efc03b962197355db4f5c3b9596bea7d397",
          "sha1": "c6f5ae24d535c67d7496ed52ba8244acf2ba5fe6",
          "md5": "d0c5f137643c34c0c57e73b1c18b407c"
        }
      ]
    }
  ]
}