{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test",
    "version": "1.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-1.7.6-multiplatform-sources.jar",
          "url": "ui-test-1.7.6-multiplatform-sources.jar",
          "size": 153012,
          "sha512": "74de25fc76d49cf2475e8e1f444590eb2edea35eb4253f178e0069b4ffad358c31ff261063a6da5e1244fea44087bfa4e50e565f786b7d6f35462ca24ae3b6ce",
          "sha256": "8c498654f0ce2faa0497f5c2226e038c3a40e10563074d3f8ee08526956c3b5b",
          "sha1": "171bd7d6147647aaeaffb4bf1f959c18b7b80bf6",
          "md5": "799d3995275ce8ca79bfc3072da2717a"
        },
        {
          "name": "ui-test-1.7.6-samples-sources.jar",
          "url": "ui-test-1.7.6-samples-sources.jar",
          "size": 10807,
          "sha512": "c9380659eef04092ab16f7c636d189941ad1e74a66ec870eaf456613b069ab651f2d0b91f31540b18ac4c78a0aa02e3d559f160d086c0f70a8439278a43e84c0",
          "sha256": "250db98324b9e788680fa58c23433bb1fb7b1bc39271fd0a2d5199d2956302fb",
          "sha1": "0ec98d8dbf4ae795292324fa14c21a1bea93e942",
          "md5": "33eeed5b493691ade1929acde75c8666"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-test-1.7.6-versionMetadata.json",
          "size": 45328,
          "sha512": "96ca83ff2e0a55844acb20a9b6c2848f949192160459ac77d9346344074f183a4f5a26515644cf72aabdf3bab75d0d7617d8a3bfb09ea52a32ed3818065306bc",
          "sha256": "af2afa283571b7d11128104fbbc7394a067fadcbd9e36447f959f5d16176cd46",
          "sha1": "6e470384e9b986ff648bfa3eaddba47cfcc598e1",
          "md5": "a70bffa2fa42b0ee924aa56327f640e0"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-metadata-1.7.6.jar",
          "url": "ui-test-1.7.6.jar",
          "size": 28417,
          "sha512": "abd9d9625cdd34a0551568f1c6a71bcfb2546275904d9f682755cef3ea79a5cd0c36003912b5f7ad224fc2ce3b9e469114ea43cb787adc0cc0102ea80d065a1d",
          "sha256": "a79ffab96e477d235ff6f30b3b6db8afc7a22134b9e20165696943f09b42f609",
          "sha1": "56a93f441e55eae34df65a9fa42f75db593ff028",
          "md5": "77ed07dba5bdd806c41e993671705da6"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.6"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-kotlin-1.7.6-sources.jar",
          "url": "ui-test-1.7.6-sources.jar",
          "size": 109541,
          "sha512": "f52388ddcd20ea697f5e8cba30e86425656104554f6e444fdc4dd4d54fa11f37481ba27330e37ece75841794ab338b60b7d38531b4a73c22678fd7dbd931bc2f",
          "sha256": "b9acec4cc968022368db1cb19149bd1cd9e7da6814568e77f19955c0beec093f",
          "sha1": "49aea968e53be7262008eb243ce7b91f1da91c7a",
          "md5": "bb5b88691c0353bbd87bd9216f63019f"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-test-android/1.7.6/ui-test-android-1.7.6.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-android",
        "version": "1.7.6"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-test-android/1.7.6/ui-test-android-1.7.6.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-android",
        "version": "1.7.6"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-test-android/1.7.6/ui-test-android-1.7.6.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-android",
        "version": "1.7.6"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-test-jvmstubs/1.7.6/ui-test-jvmstubs-1.7.6.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-jvmstubs",
        "version": "1.7.6"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-test-jvmstubs/1.7.6/ui-test-jvmstubs-1.7.6.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-jvmstubs",
        "version": "1.7.6"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-test-jvmstubs/1.7.6/ui-test-jvmstubs-1.7.6.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-jvmstubs",
        "version": "1.7.6"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-test-linuxx64stubs/1.7.6/ui-test-linuxx64stubs-1.7.6.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-linuxx64stubs",
        "version": "1.7.6"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-test-linuxx64stubs/1.7.6/ui-test-linuxx64stubs-1.7.6.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-linuxx64stubs",
        "version": "1.7.6"
      }
    }
  ]
}