{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drewhamilton.poko",
    "module": "poko-annotations",
    "version": "0.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "poko-annotations-metadata-0.17.2.jar",
          "url": "poko-annotations-0.17.2.jar",
          "size": 3514,
          "sha512": "29f5d8a2b59a630f63ed833db9c9230083d1ce043e86ef1175db54c35b27c8d91b81bcfcba85379fff431f9c5cc7b1b88c502b2ff4ca2eff6a1395d5dd4dd34d",
          "sha256": "9ec5e06f010139f4d1ddb311d5a203dc7e9ccf713c7325aeeb59d7fad2f71a2e",
          "sha1": "a146de1d4d36324c856f9cb5ab676233f0752ccc",
          "md5": "7b3df813d3aaea53a260091de592d233"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "poko-annotations-kotlin-0.17.2-sources.jar",
          "url": "poko-annotations-0.17.2-sources.jar",
          "size": 2834,
          "sha512": "25e89d73c8cedb70eed78f19e8c6048cc8134a750e09e89784019be559beb0978af2955de96284eb1571252eff102caa56e9a08dc0be4778d56c3111ad97f8c7",
          "sha256": "889b62379f4b7eba51b96827828e96dc5efc8f5a4fc587e758969e0f77dd76ad",
          "sha1": "e8128fcec7cb8e71ce8eea84ce9b5c44dd47e253",
          "md5": "fd4427cfda1bb6821f5edecdc21900d1"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativearm32/0.17.2/poko-annotations-androidnativearm32-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativearm32",
        "version": "0.17.2"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativearm32/0.17.2/poko-annotations-androidnativearm32-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativearm32",
        "version": "0.17.2"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativearm64/0.17.2/poko-annotations-androidnativearm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativearm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativearm64/0.17.2/poko-annotations-androidnativearm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativearm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativex64/0.17.2/poko-annotations-androidnativex64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativex64",
        "version": "0.17.2"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativex64/0.17.2/poko-annotations-androidnativex64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativex64",
        "version": "0.17.2"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativex86/0.17.2/poko-annotations-androidnativex86-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativex86",
        "version": "0.17.2"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativex86/0.17.2/poko-annotations-androidnativex86-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativex86",
        "version": "0.17.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosarm64/0.17.2/poko-annotations-iosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosarm64/0.17.2/poko-annotations-iosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosarm64/0.17.2/poko-annotations-iosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iossimulatorarm64/0.17.2/poko-annotations-iossimulatorarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iossimulatorarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iossimulatorarm64/0.17.2/poko-annotations-iossimulatorarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iossimulatorarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iossimulatorarm64/0.17.2/poko-annotations-iossimulatorarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iossimulatorarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosx64/0.17.2/poko-annotations-iosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosx64/0.17.2/poko-annotations-iosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosx64/0.17.2/poko-annotations-iosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-js/0.17.2/poko-annotations-js-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-js",
        "version": "0.17.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-js/0.17.2/poko-annotations-js-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-js",
        "version": "0.17.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-js/0.17.2/poko-annotations-js-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-js",
        "version": "0.17.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../poko-annotations-jvm/0.17.2/poko-annotations-jvm-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-jvm",
        "version": "0.17.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../poko-annotations-jvm/0.17.2/poko-annotations-jvm-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-jvm",
        "version": "0.17.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../poko-annotations-jvm/0.17.2/poko-annotations-jvm-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-jvm",
        "version": "0.17.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-linuxarm64/0.17.2/poko-annotations-linuxarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-linuxarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-linuxarm64/0.17.2/poko-annotations-linuxarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-linuxarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-linuxx64/0.17.2/poko-annotations-linuxx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-linuxx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-linuxx64/0.17.2/poko-annotations-linuxx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-linuxx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosarm64/0.17.2/poko-annotations-macosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosarm64/0.17.2/poko-annotations-macosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosarm64/0.17.2/poko-annotations-macosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosx64/0.17.2/poko-annotations-macosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosx64/0.17.2/poko-annotations-macosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosx64/0.17.2/poko-annotations-macosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-mingwx64/0.17.2/poko-annotations-mingwx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-mingwx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-mingwx64/0.17.2/poko-annotations-mingwx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-mingwx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosarm64/0.17.2/poko-annotations-tvosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosarm64/0.17.2/poko-annotations-tvosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosarm64/0.17.2/poko-annotations-tvosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvossimulatorarm64/0.17.2/poko-annotations-tvossimulatorarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvossimulatorarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvossimulatorarm64/0.17.2/poko-annotations-tvossimulatorarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvossimulatorarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvossimulatorarm64/0.17.2/poko-annotations-tvossimulatorarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvossimulatorarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosx64/0.17.2/poko-annotations-tvosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosx64/0.17.2/poko-annotations-tvosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosx64/0.17.2/poko-annotations-tvosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-js/0.17.2/poko-annotations-wasm-js-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-js",
        "version": "0.17.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-js/0.17.2/poko-annotations-wasm-js-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-js",
        "version": "0.17.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-js/0.17.2/poko-annotations-wasm-js-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-js",
        "version": "0.17.2"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-wasi/0.17.2/poko-annotations-wasm-wasi-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-wasi",
        "version": "0.17.2"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-wasi/0.17.2/poko-annotations-wasm-wasi-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-wasi",
        "version": "0.17.2"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-wasi/0.17.2/poko-annotations-wasm-wasi-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-wasi",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm32/0.17.2/poko-annotations-watchosarm32-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm32",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm32/0.17.2/poko-annotations-watchosarm32-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm32",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm32/0.17.2/poko-annotations-watchosarm32-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm32",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm64/0.17.2/poko-annotations-watchosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm64/0.17.2/poko-annotations-watchosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm64/0.17.2/poko-annotations-watchosarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosdevicearm64/0.17.2/poko-annotations-watchosdevicearm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosdevicearm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosdevicearm64/0.17.2/poko-annotations-watchosdevicearm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosdevicearm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosdevicearm64/0.17.2/poko-annotations-watchosdevicearm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosdevicearm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchossimulatorarm64/0.17.2/poko-annotations-watchossimulatorarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchossimulatorarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchossimulatorarm64/0.17.2/poko-annotations-watchossimulatorarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchossimulatorarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchossimulatorarm64/0.17.2/poko-annotations-watchossimulatorarm64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchossimulatorarm64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosx64/0.17.2/poko-annotations-watchosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosx64/0.17.2/poko-annotations-watchosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosx64",
        "version": "0.17.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosx64/0.17.2/poko-annotations-watchosx64-0.17.2.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosx64",
        "version": "0.17.2"
      }
    }
  ]
}
