{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-android",
    "version": "1.13.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-android",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-android-1.13.13.aar",
          "url": "mockk-android-1.13.13.aar",
          "size": 747,
          "sha512": "3d6c765839ac3c0a45ce666e7b565ce345f8be7bc57ea79b597efa54d1f7acd45313192a9aa37e8780ebc6c0e0116a60e091504e987b7fcc783b82affcbee777",
          "sha256": "1cb0955c9d49f1e72f0728dcfb79ca8a951056470253f30850cbd0fc634771ce",
          "sha1": "7f663cd0d20de1c9476d67b5c113d68f1f427dbe",
          "md5": "58c61f76ca4251a8e33ab2702f2da7e9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-android",
          "version": {
            "requires": "1.13.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-android-1.13.13.aar",
          "url": "mockk-android-1.13.13.aar",
          "size": 747,
          "sha512": "3d6c765839ac3c0a45ce666e7b565ce345f8be7bc57ea79b597efa54d1f7acd45313192a9aa37e8780ebc6c0e0116a60e091504e987b7fcc783b82affcbee777",
          "sha256": "1cb0955c9d49f1e72f0728dcfb79ca8a951056470253f30850cbd0fc634771ce",
          "sha1": "7f663cd0d20de1c9476d67b5c113d68f1f427dbe",
          "md5": "58c61f76ca4251a8e33ab2702f2da7e9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mockk-android-1.13.13-sources.jar",
          "url": "mockk-android-1.13.13-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
