{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-psi-utils",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-psi-utils-1.23.7.jar",
          "url": "detekt-psi-utils-1.23.7.jar",
          "size": 78722,
          "sha512": "6c201fd2976f6521d88253c951aa1b8ea29c98bf4f2c59d713fa8a8b44eb7447dcdaef01ceea3a89cbd7c1b08cd70ca7c69be8ab26c79629ed3ff4d22d4c4170",
          "sha256": "6a054c91da27aac77db3ed509ff9f408c45410e1a5e989dc380aae3c09d7fb6e",
          "sha1": "d0e305af681a90e3921a47406c6ceb6ba358969d",
          "md5": "d953ecfb94a309e90194f23b381f2704"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-psi-utils-1.23.7.jar",
          "url": "detekt-psi-utils-1.23.7.jar",
          "size": 78722,
          "sha512": "6c201fd2976f6521d88253c951aa1b8ea29c98bf4f2c59d713fa8a8b44eb7447dcdaef01ceea3a89cbd7c1b08cd70ca7c69be8ab26c79629ed3ff4d22d4c4170",
          "sha256": "6a054c91da27aac77db3ed509ff9f408c45410e1a5e989dc380aae3c09d7fb6e",
          "sha1": "d0e305af681a90e3921a47406c6ceb6ba358969d",
          "md5": "d953ecfb94a309e90194f23b381f2704"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-psi-utils-1.23.7-sources.jar",
          "url": "detekt-psi-utils-1.23.7-sources.jar",
          "size": 17870,
          "sha512": "1bd493cb56e1c01bc3539b6a4c3cae8c7ceb7b07a85e8f2da831cd9a0d5a9401e699e30dddb2e90baa61f7ecad9f9f76286159a2e5e9a15b8a54180c502f27e6",
          "sha256": "ff4aadbeeee6b6bcdeda8a2ef01d7fd34d4d667c2bb047c4a24c19218aebf695",
          "sha1": "354eaa3deb98b5c8c539269621b8fd2c6ef915c2",
          "md5": "035cd463aaaf1dec188e031e71693548"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-psi-utils-1.23.7-javadoc.jar",
          "url": "detekt-psi-utils-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "890e3021d30859f7954055249f21b5880ddac3b13843d03b3fd2fc97ed3a596e881619934c03a7786c154965f885c292b6aebc2f0ff2c9d8f328dd39458c6750",
          "sha256": "000422088dab561ded3ca3b38f5d0787aaa42ce034a26330003bd3f082fa152b",
          "sha1": "87077aab9d24bbd2479bd12a83f7f639faf5710d",
          "md5": "c120a0ced59b54cd0c579b47b7ace0a3"
        }
      ]
    }
  ]
}
