{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-cli",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-1.3.1.jar",
          "url": "ktlint-cli-1.3.1.jar",
          "size": 155549,
          "sha512": "fe0d59f44ee756d1bda67df9832c95df0ade0a2a904b77a16b92613ca08ec535ea7c1d1cc76ba21d33c912eb292bd2069c5414216e72320e85dfe04e7bb31f71",
          "sha256": "e94e1c0e7c90ae395ddd2355d5042fb3f2be6d6cd99f5d3c25834320f4cd08c7",
          "sha1": "881e5ec4f72ec82ff73e13da9ae8731d6216a54b",
          "md5": "a8c443cf589c2cf8723150f1bc6abb76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-logger",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-baseline",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-plain",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-rule-engine",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-ruleset-standard",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.14"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-checkstyle",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-json",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-format",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-html",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-plain-summary",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-sarif",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-1.3.1.jar",
          "url": "ktlint-cli-1.3.1.jar",
          "size": 155549,
          "sha512": "fe0d59f44ee756d1bda67df9832c95df0ade0a2a904b77a16b92613ca08ec535ea7c1d1cc76ba21d33c912eb292bd2069c5414216e72320e85dfe04e7bb31f71",
          "sha256": "e94e1c0e7c90ae395ddd2355d5042fb3f2be6d6cd99f5d3c25834320f4cd08c7",
          "sha1": "881e5ec4f72ec82ff73e13da9ae8731d6216a54b",
          "md5": "a8c443cf589c2cf8723150f1bc6abb76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-1.3.1-sources.jar",
          "url": "ktlint-cli-1.3.1-sources.jar",
          "size": 22347,
          "sha512": "4217f45cfcc5b095441d4f37134bb8702850fae0e3dfb9e16ba7234bb1f43b88a8f09c564e8ae581728468a132fcbbb47a3e11f411d3eaafaa50fae5c63ec6a8",
          "sha256": "7282cd8b3d0f56d395864a3c5e675571f639a23fab6a3ca6ab6629f0294816f8",
          "sha1": "943e31ffae1973654ef668461b578aa038db5285",
          "md5": "3c1807c0f020e7f73b278438391074fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-1.3.1-javadoc.jar",
          "url": "ktlint-cli-1.3.1-javadoc.jar",
          "size": 402937,
          "sha512": "24fda0156859cd58beb03baf504256f27929dbc04e2974ce874b66df49f26808d1279ac1e9a446cc445392fb443a2a17b34a6869ac210e2293853df08177d4b1",
          "sha256": "07ceaebb170096d3d8df8be805a02cafb71dc59927fb6cbc39d10dc89e18365e",
          "sha1": "883a05353defb902c86ad70b1406c33f976f1622",
          "md5": "fe9ac7d6f1e997b990ac0070076cf8e6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-1.3.1-all.jar",
          "url": "ktlint-cli-1.3.1-all.jar",
          "size": 80471993,
          "sha512": "82c0ae9efb4cb96e00d11e78d29d09c7880f6f2037ad05a605ca76e88a0bbf0f0f9ad5f852dfd8536ce3495ca87bad0985956f7efc0c7702f3665bec106a9a8a",
          "sha256": "ea7590217143ce897584f067826a2f75bd639f00547f7bd9d0eb8bf4498af061",
          "sha1": "373d8909a19bdf5302425a7d61248a17fb63cb7d",
          "md5": "ead76ff6b82ef6f9df73f2d9d4e5704c"
        }
      ]
    }
  ]
}
