{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-testing",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-testing-1.1.1-sources.jar",
          "url": "glance-testing-1.1.1-sources.jar",
          "size": 18306,
          "sha512": "da546b838c2b2c5c6406536e08c0b02a05ad2868eeeea88e490d29f3e7e875dcff0735d714c40bc7cf249138e306f40891e3c55bd75b994924d5bfa5ab0b64e5",
          "sha256": "9e94cda80b3a9e94799b01f6a53b8ab51def1932704c787885ca1a1dc9f4ee83",
          "sha1": "794d09bddd836b8a29265b1a9b2ac455787e4184",
          "md5": "b703dcc8f58a6f0be21d0ca03555877e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-testing-1.1.1.aar",
          "url": "glance-testing-1.1.1.aar",
          "size": 59604,
          "sha512": "f0ace172443dd23fc7ef4f3a8d7b8c9a85f16eefbcebeb2ed17b76817b0aa326ac0ed3dae03755c68867d4ce08977684202891bebcc687fdf236b062cad48f8d",
          "sha256": "b2e3543df9b39c1c2cf95d03a71af321a2ff14ab64a16ee67889ce87f3cc8386",
          "sha1": "fed83decdf16a31f87cdc4e3821e1862a9ef49cb",
          "md5": "7f1dcff10d87d37e87f40c0970a0094f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-testing-1.1.1.aar",
          "url": "glance-testing-1.1.1.aar",
          "size": 59604,
          "sha512": "f0ace172443dd23fc7ef4f3a8d7b8c9a85f16eefbcebeb2ed17b76817b0aa326ac0ed3dae03755c68867d4ce08977684202891bebcc687fdf236b062cad48f8d",
          "sha256": "b2e3543df9b39c1c2cf95d03a71af321a2ff14ab64a16ee67889ce87f3cc8386",
          "sha1": "fed83decdf16a31f87cdc4e3821e1862a9ef49cb",
          "md5": "7f1dcff10d87d37e87f40c0970a0094f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-testing is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-testing-1.1.1-versionMetadata.json",
          "url": "glance-testing-1.1.1-versionMetadata.json",
          "size": 5425,
          "sha512": "c25e33112d1322b6d3c31c0973c28a55f4ceb865c113dbe9285abf37594d3cf9c5a45a5ced8dd361c80d78441b9101a88d34567494f17d7eea74e3174cb270a4",
          "sha256": "299b16f721bb9ebf65af2aaf881e81db76c5816f0a3da460769b7e98d7bdda4d",
          "sha1": "de5d8b1aa7ae321c233d14da0058874cc58a94e2",
          "md5": "2efc9604a4e3240fc62ff8d2a24b63e1"
        }
      ]
    }
  ]
}