{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-cli-reporter-core",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-core-1.3.1.jar",
          "url": "ktlint-cli-reporter-core-1.3.1.jar",
          "size": 8183,
          "sha512": "eeb652893e07e1b15f24cb4a433946480ac7a36c33fb7526ebb875b27e0f5d43fa7accc445493661dc3465d0981119990a56e27a5cf8a3e466d9862da4214500",
          "sha256": "d12b5891c338cafc0c790116c14cb3bbb8218d21ea2f5aa886556466f39893a9",
          "sha1": "ce21c2aa906385199b3ee1387b3000fc62f3c0e8",
          "md5": "06a1a6f18b47f43cbeb841763c3b7511"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-core-1.3.1.jar",
          "url": "ktlint-cli-reporter-core-1.3.1.jar",
          "size": 8183,
          "sha512": "eeb652893e07e1b15f24cb4a433946480ac7a36c33fb7526ebb875b27e0f5d43fa7accc445493661dc3465d0981119990a56e27a5cf8a3e466d9862da4214500",
          "sha256": "d12b5891c338cafc0c790116c14cb3bbb8218d21ea2f5aa886556466f39893a9",
          "sha1": "ce21c2aa906385199b3ee1387b3000fc62f3c0e8",
          "md5": "06a1a6f18b47f43cbeb841763c3b7511"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-core-1.3.1-sources.jar",
          "url": "ktlint-cli-reporter-core-1.3.1-sources.jar",
          "size": 3891,
          "sha512": "a12fc3317d0dcd8894cd37e780a46fa10162a61853b6eb96ff07555a04692e52ce5bcbd98d6dff40ed3356fbdb5863fa4cd02f56ed57d502da4d55fb160c18df",
          "sha256": "df519e5bc3bc9578afb0126ef4063df7643bb4d9e8c92380ad075867f6af4e35",
          "sha1": "cd734042e8753d0ed00c3080e6185ed21f047793",
          "md5": "f47df139667aadda5f3b435b847cbd39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-core-1.3.1-javadoc.jar",
          "url": "ktlint-cli-reporter-core-1.3.1-javadoc.jar",
          "size": 434717,
          "sha512": "43427579bf65e685db90ab5f09e9fa37b39c8cf76e1163b0b8758a63c7679a6b474e8eab640a8dd98941a27d0a64e95980e51e55339f30ec09a1345562879061",
          "sha256": "c95ffa3518d4f3531c4778c9cec164d6ac105facb63b24a134a314bf2632ebe0",
          "sha1": "41b0445ce3d0a56481ec62ac7413c9ba76fe90aa",
          "md5": "06bd02caee8bc313d2641b5b53302d4d"
        }
      ]
    }
  ]
}
