{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "5.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-api",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-metadata-5.9.1.jar",
          "url": "kotest-assertions-shared-5.9.1.jar",
          "size": 48449,
          "sha512": "a7e300efe9e5ec17bd653cd8c0bb6c72c2e0a7993f50f7eb44b45b006514568f3f3f9acf798ae30efe161a9ba6a5b967157020aa0cb5f0305c954f1f5728355e",
          "sha256": "880d4dab576a5ce4930cd07abb1825b7b1e7099bdc5dfe6c8868c5db963c0249",
          "sha1": "228195ddf3a9edc7a65755c17fbc4d3a3f2a57ff",
          "md5": "35768998446893e6ba5faea53df35900"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-kotlin-5.9.1-sources.jar",
          "url": "kotest-assertions-shared-5.9.1-sources.jar",
          "size": 75224,
          "sha512": "e0c765d88198f532e99449df4ab5f3f1a4b643eb3df3b6f7ba4f673a9350643080d36983531fddec0f54d845ff60a11e8cdfdcbc08404e3a69d7262128a225a6",
          "sha256": "47adcded19823acb2e8e4eb2cac7dfb97d3edf50e99bed8085ef941eba41be0a",
          "sha1": "64c6888ea44e8efa50b90c2f01b29a62d8606f7b",
          "md5": "20bacc181e8a173dadb1ca5765e2ec64"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativearm32/5.9.1/kotest-assertions-shared-androidnativearm32-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativearm32",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativearm32/5.9.1/kotest-assertions-shared-androidnativearm32-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativearm32",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativearm64/5.9.1/kotest-assertions-shared-androidnativearm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativearm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativearm64/5.9.1/kotest-assertions-shared-androidnativearm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativearm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativex64/5.9.1/kotest-assertions-shared-androidnativex64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativex64",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativex64/5.9.1/kotest-assertions-shared-androidnativex64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativex64",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativex86/5.9.1/kotest-assertions-shared-androidnativex86-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativex86",
        "version": "5.9.1"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativex86/5.9.1/kotest-assertions-shared-androidnativex86-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativex86",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosarm64/5.9.1/kotest-assertions-shared-iosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosarm64/5.9.1/kotest-assertions-shared-iosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosarm64/5.9.1/kotest-assertions-shared-iosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iossimulatorarm64/5.9.1/kotest-assertions-shared-iossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iossimulatorarm64/5.9.1/kotest-assertions-shared-iossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iossimulatorarm64/5.9.1/kotest-assertions-shared-iossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosx64/5.9.1/kotest-assertions-shared-iosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosx64/5.9.1/kotest-assertions-shared-iosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosx64/5.9.1/kotest-assertions-shared-iosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-js/5.9.1/kotest-assertions-shared-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-js/5.9.1/kotest-assertions-shared-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-js/5.9.1/kotest-assertions-shared-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-jvm/5.9.1/kotest-assertions-shared-jvm-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-jvm",
        "version": "5.9.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-jvm/5.9.1/kotest-assertions-shared-jvm-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-jvm",
        "version": "5.9.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-jvm/5.9.1/kotest-assertions-shared-jvm-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-jvm",
        "version": "5.9.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-linuxarm64/5.9.1/kotest-assertions-shared-linuxarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-linuxarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-linuxarm64/5.9.1/kotest-assertions-shared-linuxarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-linuxarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-linuxx64/5.9.1/kotest-assertions-shared-linuxx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-linuxx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-linuxx64/5.9.1/kotest-assertions-shared-linuxx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-linuxx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosarm64/5.9.1/kotest-assertions-shared-macosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosarm64/5.9.1/kotest-assertions-shared-macosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosarm64/5.9.1/kotest-assertions-shared-macosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosx64/5.9.1/kotest-assertions-shared-macosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosx64/5.9.1/kotest-assertions-shared-macosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosx64/5.9.1/kotest-assertions-shared-macosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-mingwx64/5.9.1/kotest-assertions-shared-mingwx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-mingwx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-mingwx64/5.9.1/kotest-assertions-shared-mingwx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-mingwx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosarm64/5.9.1/kotest-assertions-shared-tvosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosarm64/5.9.1/kotest-assertions-shared-tvosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosarm64/5.9.1/kotest-assertions-shared-tvosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvossimulatorarm64/5.9.1/kotest-assertions-shared-tvossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvossimulatorarm64/5.9.1/kotest-assertions-shared-tvossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvossimulatorarm64/5.9.1/kotest-assertions-shared-tvossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosx64/5.9.1/kotest-assertions-shared-tvosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosx64/5.9.1/kotest-assertions-shared-tvosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosx64/5.9.1/kotest-assertions-shared-tvosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-wasm-js/5.9.1/kotest-assertions-shared-wasm-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-wasm-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-wasm-js/5.9.1/kotest-assertions-shared-wasm-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-wasm-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-wasm-js/5.9.1/kotest-assertions-shared-wasm-js-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-wasm-js",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm32/5.9.1/kotest-assertions-shared-watchosarm32-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm32",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm32/5.9.1/kotest-assertions-shared-watchosarm32-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm32",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm32/5.9.1/kotest-assertions-shared-watchosarm32-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm32",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm64/5.9.1/kotest-assertions-shared-watchosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm64/5.9.1/kotest-assertions-shared-watchosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm64/5.9.1/kotest-assertions-shared-watchosarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosdevicearm64/5.9.1/kotest-assertions-shared-watchosdevicearm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosdevicearm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosdevicearm64/5.9.1/kotest-assertions-shared-watchosdevicearm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosdevicearm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosdevicearm64/5.9.1/kotest-assertions-shared-watchosdevicearm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosdevicearm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchossimulatorarm64/5.9.1/kotest-assertions-shared-watchossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchossimulatorarm64/5.9.1/kotest-assertions-shared-watchossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchossimulatorarm64/5.9.1/kotest-assertions-shared-watchossimulatorarm64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchossimulatorarm64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosx64/5.9.1/kotest-assertions-shared-watchosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosx64/5.9.1/kotest-assertions-shared-watchosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosx64",
        "version": "5.9.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosx64/5.9.1/kotest-assertions-shared-watchosx64-5.9.1.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosx64",
        "version": "5.9.1"
      }
    }
  ]
}
