{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-cli-ruleset-core",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-rule-engine-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-ruleset-core-1.3.1.jar",
          "url": "ktlint-cli-ruleset-core-1.3.1.jar",
          "size": 2315,
          "sha512": "f55aa1464cd4109579bfd83e47a5fc94f4f5aebc435182384c173b2f298f32a5622d9a6a98f4304f98f8ae39da8817d0e6a5f747df59d0790db0901cf493bee7",
          "sha256": "722a9ae9afddd317460e7838b731507bd0eb42f769dc4d36ead70c49bc2a41b0",
          "sha1": "e6e564c8b99881c67769196f0e0326cfc4fca365",
          "md5": "ec50243790097701eb67c0f696b4532c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-rule-engine-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-ruleset-core-1.3.1.jar",
          "url": "ktlint-cli-ruleset-core-1.3.1.jar",
          "size": 2315,
          "sha512": "f55aa1464cd4109579bfd83e47a5fc94f4f5aebc435182384c173b2f298f32a5622d9a6a98f4304f98f8ae39da8817d0e6a5f747df59d0790db0901cf493bee7",
          "sha256": "722a9ae9afddd317460e7838b731507bd0eb42f769dc4d36ead70c49bc2a41b0",
          "sha1": "e6e564c8b99881c67769196f0e0326cfc4fca365",
          "md5": "ec50243790097701eb67c0f696b4532c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-ruleset-core-1.3.1-sources.jar",
          "url": "ktlint-cli-ruleset-core-1.3.1-sources.jar",
          "size": 1916,
          "sha512": "1bad1a00dbf9507596b19f4d2f2df301eac60f3aed853db4752780f7fe34f6c397967fa6a8306fd65f6af74317fb1b9afda469dbcfcdb6f947a3fe358d6bb1b8",
          "sha256": "dec4577feff78ddbec6a2979258a48450b8ee4fb853783792d6cdadc77bc27d7",
          "sha1": "038717f467b5d570fc723c0f1df0999926f1adf7",
          "md5": "d8f87b091a0a65c43cd287c3456e9d4e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-ruleset-core-1.3.1-javadoc.jar",
          "url": "ktlint-cli-ruleset-core-1.3.1-javadoc.jar",
          "size": 406477,
          "sha512": "859da985c74684d8ab4a1a4080da3afedcd5c0beeb280af9a13be926e128fa7db216b8aa6f629be52a685b86a3920e5aa615b13b5f470f3030ab8413ad1945d8",
          "sha256": "1212e65344fbbc1902c7f76cea99438263367ea4ebd28e9a8c543dedd83fb97a",
          "sha1": "1b10d62821819143a8f9fb1e24f2b38e24305ce4",
          "md5": "51badc751533d078538f9ccee0cfe20e"
        }
      ]
    }
  ]
}
