{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-shared/5.9.1/kotest-assertions-shared-5.9.1.module",
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "5.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-api",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-jvm-5.9.1.jar",
          "url": "kotest-assertions-shared-jvm-5.9.1.jar",
          "size": 642372,
          "sha512": "cb79ff8fda8617c31e0bbda245efbd3b985a5085b6e616730c676e5a198a6fdefe00fc6d6680015b22769cd6cb13c62907e243b583338de5e527bce07f9cb757",
          "sha256": "c7da7ed66e25b59406349facd4bb43537ca48589a74aa3d883eb412c9caac60a",
          "sha1": "58621dfd37d40668def8919b603528d54c1b1bd7",
          "md5": "ade453c173cb0a613f529fd14adb2825"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-api",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.github.java-diff-utils",
          "module": "java-diff-utils",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-jvm-5.9.1.jar",
          "url": "kotest-assertions-shared-jvm-5.9.1.jar",
          "size": 642372,
          "sha512": "cb79ff8fda8617c31e0bbda245efbd3b985a5085b6e616730c676e5a198a6fdefe00fc6d6680015b22769cd6cb13c62907e243b583338de5e527bce07f9cb757",
          "sha256": "c7da7ed66e25b59406349facd4bb43537ca48589a74aa3d883eb412c9caac60a",
          "sha1": "58621dfd37d40668def8919b603528d54c1b1bd7",
          "md5": "ade453c173cb0a613f529fd14adb2825"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-jvm-5.9.1-sources.jar",
          "url": "kotest-assertions-shared-jvm-5.9.1-sources.jar",
          "size": 78048,
          "sha512": "fd4c69cfa8e23ce83c2cd17f9d95e995097a7c41b26d43af100bc7298551bdf298e9e99430c93b187991e14aaf93b3b90fdb1b1360571d76759f6d3253114a71",
          "sha256": "14b0c73c06a18f80c7d624d700e30e858a990de5e9e31d6a699ce158dc36d15b",
          "sha1": "09804c33b3ad460362402b305e1c1df8bb64ec4c",
          "md5": "52d9f8dab5245b57a9e8669a02025cd0"
        }
      ]
    }
  ]
}
