{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.layoutlib",
    "module": "layoutlib-runtime",
    "version": "14.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.11.jar",
          "url": "layoutlib-runtime-14.0.11.jar",
          "size": 92824169,
          "sha512": "fa768d17ed6de65363f85d4457f79c28ef446fa0dfae9c0191af61f30bfcaf242eadb955aedf0bc6996b3d5574de7298d0aa3cdf18842213fdd31d2a7b4a3ad2",
          "sha256": "1c1cf2e05d5b952c9d1888a8b2821726bfcd59d535249f8a0cc16e703ac6196d",
          "sha1": "0be2f6d97cbec1dd0d6295bc05964896a1a8d4f8",
          "md5": "b21bae57fbff14496303dc90835977a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.11.jar",
          "url": "layoutlib-runtime-14.0.11.jar",
          "size": 92824169,
          "sha512": "fa768d17ed6de65363f85d4457f79c28ef446fa0dfae9c0191af61f30bfcaf242eadb955aedf0bc6996b3d5574de7298d0aa3cdf18842213fdd31d2a7b4a3ad2",
          "sha256": "1c1cf2e05d5b952c9d1888a8b2821726bfcd59d535249f8a0cc16e703ac6196d",
          "sha1": "0be2f6d97cbec1dd0d6295bc05964896a1a8d4f8",
          "md5": "b21bae57fbff14496303dc90835977a1"
        }
      ]
    },
    {
      "name": "linux",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.operatingSystem": "linux",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.11-linux.jar",
          "url": "layoutlib-runtime-14.0.11-linux.jar",
          "size": 76695759,
          "sha512": "36c60b85696eddb50220a11de5851bbf290ae691f7545806ace4bd22d675940bf29aeefbef60c1c4520d4ece2def3188080177ca65c84c4300a07d8be7deaa2b",
          "sha256": "3811fac81ad279ac1b7c998d199ff62cace4a36b10fc259b80eb4da40f8b0aea",
          "sha1": "ecd0e1be5624fde6ecd17fdc7e1e262abfc6a5ed",
          "md5": "8162685d2f655fe3197f8195c0ad80eb"
        }
      ]
    },
    {
      "name": "windows",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.operatingSystem": "windows",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.11-win.jar",
          "url": "layoutlib-runtime-14.0.11-win.jar",
          "size": 75218785,
          "sha512": "9d6e76ef8cdcf108ba9f3a8f2a0db53eb714519998973cf31a7200a9ee73b5fa2052413864df435573dd950dd5ddb34c20c818762e669d9bd1a78dbed43174d9",
          "sha256": "3e26acb000bd2c10bf44da72303622e059febbdd5f9facb461ea77f4151e63bd",
          "sha1": "3cc4a873234057dc58b2a50d5c8f87b463a6de2c",
          "md5": "f5d38e5c076ec7fe4758d94cd5df8951"
        }
      ]
    },
    {
      "name": "macX86",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.operatingSystem": "macos",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.11-mac.jar",
          "url": "layoutlib-runtime-14.0.11-mac.jar",
          "size": 75978348,
          "sha512": "12b8b81873aa2e02104990fc002c7e09f99af1ffd2db1ee90feff9e3346d4fa748762249c9fa0b85ccca12adb045b0fc6660c39c57acda996f7f15ff975f8ccd",
          "sha256": "651f03ec93ca87b6a34500ddf280484215bef1221fb027c75fd013ea01bcef4c",
          "sha1": "b88a5870afcf111de1ba398a0c95c64a15f10d18",
          "md5": "0f5163f31db34e6d429ca557a913f4b6"
        }
      ]
    },
    {
      "name": "macArm",
      "attributes": {
        "org.gradle.native.architecture": "aarch64",
        "org.gradle.native.operatingSystem": "macos",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.11-mac-arm.jar",
          "url": "layoutlib-runtime-14.0.11-mac-arm.jar",
          "size": 75527902,
          "sha512": "e5d239816bda2e49835bddaa49c0caf26c1d9db5509f38ea98644f6c56a2a1788eed590122711da6b784c8d99e9a3fc0f13df30f7ca92792ea2fd7f96cb3d86a",
          "sha256": "df612670906b649c5537dee76062147468770e2696386c9bab2f46e6e35c5e29",
          "sha1": "7f9b87268fcbab0c243bfd52dac56cce5ad38f48",
          "md5": "faf153c87b7618a2bbf196d75f5f601f"
        }
      ]
    }
  ]
}
