{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-remoteviews",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-remoteviews-1.1.0-sources.jar",
          "url": "core-remoteviews-1.1.0-sources.jar",
          "size": 20535,
          "sha512": "d5b5ecd2b9e650b7617bd25aab20c02b45e87dcf1330de792376cc2afaccf27cea2164661dfbf39b3ca6834a03412c9dcb62c8814d505399b30ab826bc0d0f07",
          "sha256": "5e6910ad65721efb5f7a15f01ee5bb72930c888f8f4e3d820c18a9df1e36c171",
          "sha1": "ae14ce9088957093d4dba47f3580717b4e85c546",
          "md5": "10ef61fc594a3e9976e21291dfe072e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteviews-1.1.0.aar",
          "url": "core-remoteviews-1.1.0.aar",
          "size": 54483,
          "sha512": "5ae970b60f6131de3db306adb72753671068c1ed1b681c0a21d2b248e5f04d7df7e3aeeefa778799219aee46d0756895cc80818b5d14306aa834a0e3ecc13a7c",
          "sha256": "571fa872d3c86b21b4cd0078a980cea76834151fc4958a4af3178f4ba8eb3aba",
          "sha1": "eed9f50972899dc2e51001c79c0094de7ff85d53",
          "md5": "62bf1006d1ffb6ce2d5b4c2d4eb82357"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteviews-1.1.0.aar",
          "url": "core-remoteviews-1.1.0.aar",
          "size": 54483,
          "sha512": "5ae970b60f6131de3db306adb72753671068c1ed1b681c0a21d2b248e5f04d7df7e3aeeefa778799219aee46d0756895cc80818b5d14306aa834a0e3ecc13a7c",
          "sha256": "571fa872d3c86b21b4cd0078a980cea76834151fc4958a4af3178f4ba8eb3aba",
          "sha1": "eed9f50972899dc2e51001c79c0094de7ff85d53",
          "md5": "62bf1006d1ffb6ce2d5b4c2d4eb82357"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-remoteviews-1.1.0-versionMetadata.json",
          "url": "core-remoteviews-1.1.0-versionMetadata.json",
          "size": 28056,
          "sha512": "c138f2a0531b0b003e6faed04a49a913cbdfd7b85307509a3cddcc313b1b980261f3421475f461528ee90fdd1625b51964497f26d5cf0c96f64d418be9407947",
          "sha256": "268dfc74cd1e65c1d11e2d395243301d8cbf87a42d06526072db9f62d6211fa9",
          "sha1": "4f9db05b8075b71e329d7058c2c66fb324eceeef",
          "md5": "004664c9215f108e5cf22c172bf87ec5"
        }
      ]
    }
  ]
}