{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mannodermaus.gradle.plugins",
    "module": "android-junit5",
    "version": "1.11.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-junit5-1.11.2.0.jar",
          "url": "android-junit5-1.11.2.0.jar",
          "size": 116743,
          "sha512": "10735d338c554734151af73d87b250001d3c2e2fead2a409268f8a63a63a2fd20c6b44b498ff87933ffcea4854078dafa907ff6f945300cb0c30e9c194991fe8",
          "sha256": "18028f22aad5d59c780e10f9465839e47a6e742f1e89e67b885252bf90519001",
          "sha1": "ac33128bb2b5ba5fdfe339e159877e6beb234825",
          "md5": "77495ad692b01b58fe7b11f50edcbe5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.11.2"
          }
        }
      ],
      "files": [
        {
          "name": "android-junit5-1.11.2.0.jar",
          "url": "android-junit5-1.11.2.0.jar",
          "size": 116743,
          "sha512": "10735d338c554734151af73d87b250001d3c2e2fead2a409268f8a63a63a2fd20c6b44b498ff87933ffcea4854078dafa907ff6f945300cb0c30e9c194991fe8",
          "sha256": "18028f22aad5d59c780e10f9465839e47a6e742f1e89e67b885252bf90519001",
          "sha1": "ac33128bb2b5ba5fdfe339e159877e6beb234825",
          "md5": "77495ad692b01b58fe7b11f50edcbe5a"
        }
      ]
    }
  ]
}
