{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-rules-exceptions",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-rules-exceptions-1.23.7.jar",
          "url": "detekt-rules-exceptions-1.23.7.jar",
          "size": 82493,
          "sha512": "c6013ff3d1db8537070ece7383a7e1de447912a55c54b77385bd0d8585fc6cc8d0b47dbc45c198756ca245301eb4f013113db5646503c85367ab18a809c33d08",
          "sha256": "02c715b2107a7223f203405bb8e4b5b418c3643e264029c750e7a3e504c1be78",
          "sha1": "28bebf3279d1e784bfdd92bcefd4ad8217befcd2",
          "md5": "8fbdda53ecadb9a704c539b3e112cd6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-rules-exceptions-1.23.7.jar",
          "url": "detekt-rules-exceptions-1.23.7.jar",
          "size": 82493,
          "sha512": "c6013ff3d1db8537070ece7383a7e1de447912a55c54b77385bd0d8585fc6cc8d0b47dbc45c198756ca245301eb4f013113db5646503c85367ab18a809c33d08",
          "sha256": "02c715b2107a7223f203405bb8e4b5b418c3643e264029c750e7a3e504c1be78",
          "sha1": "28bebf3279d1e784bfdd92bcefd4ad8217befcd2",
          "md5": "8fbdda53ecadb9a704c539b3e112cd6b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-rules-exceptions-1.23.7-sources.jar",
          "url": "detekt-rules-exceptions-1.23.7-sources.jar",
          "size": 18793,
          "sha512": "9a7835e5f107ac8238819d798df79e280106478be0d8cb6ec500a193387c678a76a0fadc1db1e8c436bb6fe744276cb4df8d687aef5492aa696a771113930099",
          "sha256": "8835895ed4be4d5a28a280604eda473b90966fb9b9dd4068fb935665c52dbc8c",
          "sha1": "006dc08ad2c614b8aef394998ef2ff197b55428a",
          "md5": "b7938253e4cf3576308b3237491e3007"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-rules-exceptions-1.23.7-javadoc.jar",
          "url": "detekt-rules-exceptions-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "890e3021d30859f7954055249f21b5880ddac3b13843d03b3fd2fc97ed3a596e881619934c03a7786c154965f885c292b6aebc2f0ff2c9d8f328dd39458c6750",
          "sha256": "000422088dab561ded3ca3b38f5d0787aaa42ce034a26330003bd3f082fa152b",
          "sha1": "87077aab9d24bbd2479bd12a83f7f639faf5710d",
          "md5": "c120a0ced59b54cd0c579b47b7ace0a3"
        }
      ]
    }
  ]
}
