{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-cli-reporter-baseline",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-baseline-1.3.1.jar",
          "url": "ktlint-cli-reporter-baseline-1.3.1.jar",
          "size": 24704,
          "sha512": "1600bcf1b65531c2e47667571ad60d1881b19388661d449b5d5a0169a16870db0e2a21d62024d585273315b94b5c85f4a5571b688d52998314139962b5898af0",
          "sha256": "e419edc06f6bf4504b001f7eb00d90f88742f2b99dc620b54daa13b346e74f7e",
          "sha1": "9689246b2c6c95a324575617752c499426eec190",
          "md5": "081b305e67c8d7722c3b23844a16730f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-logger",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-rule-engine-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-baseline-1.3.1.jar",
          "url": "ktlint-cli-reporter-baseline-1.3.1.jar",
          "size": 24704,
          "sha512": "1600bcf1b65531c2e47667571ad60d1881b19388661d449b5d5a0169a16870db0e2a21d62024d585273315b94b5c85f4a5571b688d52998314139962b5898af0",
          "sha256": "e419edc06f6bf4504b001f7eb00d90f88742f2b99dc620b54daa13b346e74f7e",
          "sha1": "9689246b2c6c95a324575617752c499426eec190",
          "md5": "081b305e67c8d7722c3b23844a16730f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-baseline-1.3.1-sources.jar",
          "url": "ktlint-cli-reporter-baseline-1.3.1-sources.jar",
          "size": 5436,
          "sha512": "7ced9adbf1216d52ccb06c8bffeb871fc72b495926edb5586945ec868b5ee9d688d57f50373e0a922766c2729782c81f8c38ecfcd1128a124b154b0fe2763352",
          "sha256": "e46883394202dd9463bb7195edbe126e32d2ab161ae5809c5d12171ee70d4b81",
          "sha1": "f82de87597905a185b1986a8ef4f28625c4c1b28",
          "md5": "b3400ed8b88dc72defcb8cc52cdc8f23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-baseline-1.3.1-javadoc.jar",
          "url": "ktlint-cli-reporter-baseline-1.3.1-javadoc.jar",
          "size": 448611,
          "sha512": "3e47155943b0d57e5a6d0bbcaea1196c3274e857f39348027fd61735fec593104bbca816bd9156fda352fe5b69dc6e25e65a3c7010f5639043c17b9aa2fa9a39",
          "sha256": "ff224829e1f9d10c82d368df09ed3855d4bbf58144900d96e9fb636952cf5d08",
          "sha1": "039ab4ad8d2b8bdb6a4ce08b0b382475eec5ceda",
          "md5": "d76f7f09030b41c64ebeed063453107c"
        }
      ]
    }
  ]
}
