{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-rule-engine-core",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.ec4j.core",
          "module": "ec4j-core",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-rule-engine-core-1.3.1.jar",
          "url": "ktlint-rule-engine-core-1.3.1.jar",
          "size": 137047,
          "sha512": "ba8190062914f7ac4d9a72f8088ee0684385b6f5aef59d239f4dec465bc99c2cf8d9b8495a908f897b14f46b806c263c38c654affbee29fd8065908ef4e96c35",
          "sha256": "dd4094808cb06e2e886b100e1b6917d37cc5b8de057fff1db81bac8d2967f0be",
          "sha1": "981ccd2d2fbc77ffadc78faf4425e01c9c679474",
          "md5": "22205c45f4a525d04ac12542c57874d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-logger",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.ec4j.core",
          "module": "ec4j-core",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-rule-engine-core-1.3.1.jar",
          "url": "ktlint-rule-engine-core-1.3.1.jar",
          "size": 137047,
          "sha512": "ba8190062914f7ac4d9a72f8088ee0684385b6f5aef59d239f4dec465bc99c2cf8d9b8495a908f897b14f46b806c263c38c654affbee29fd8065908ef4e96c35",
          "sha256": "dd4094808cb06e2e886b100e1b6917d37cc5b8de057fff1db81bac8d2967f0be",
          "sha1": "981ccd2d2fbc77ffadc78faf4425e01c9c679474",
          "md5": "22205c45f4a525d04ac12542c57874d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-rule-engine-core-1.3.1-sources.jar",
          "url": "ktlint-rule-engine-core-1.3.1-sources.jar",
          "size": 32400,
          "sha512": "186a19c63567f8ccd22fcadc23a7f5ced1389830a719b0051956c13d0a7f0ee8c8da8d7ab2aa6ba61d0f731a132a533fbb261fbce8abacea0520f4ab26bb0d88",
          "sha256": "4a0591895fb1ec62382c825c0c0c8ad6bbacc0837c528996d487ce73daff320c",
          "sha1": "06c9c9a169843d88e92dca357c8f82fe743b7261",
          "md5": "5b05ae1275a908c3a1f9bf3cba18193b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-rule-engine-core-1.3.1-javadoc.jar",
          "url": "ktlint-rule-engine-core-1.3.1-javadoc.jar",
          "size": 633356,
          "sha512": "8af36239ac09a76809b47a287a8839eaa41cbe7af53580bf13258b4f90bbd4326f23d6dd2c8cad548ebe16ec2accdc4e6dd1624ccacd9e30a0430cf358db2399",
          "sha256": "c80078f09b805c67e9630763d9bcee61598fa719f0f2e82084ad2487a4cdac4b",
          "sha1": "441412b77cd299c2d1ddfd3108e3d49c051adb11",
          "md5": "d5c993a1ff91ad5c52dc1bd5e3eb0748"
        }
      ]
    }
  ]
}
