{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-gradle-plugin",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "detekt-gradle-plugin-1.23.7.jar",
          "url": "detekt-gradle-plugin-1.23.7.jar",
          "size": 174100,
          "sha512": "9b77f07bc515b428d398046b4049ff51274602f6bd4dad7f8ce8962e44660317d41a24729843736e91366066c193e6c4deb626d13cacc8de4e49f79804f1f25a",
          "sha256": "64953a1d81e9062ca2ec96841c0844cb58f2a1591c7bfea92a4275d392417805",
          "sha1": "0b106238ad6b7b2055e380d51076a9851e72670d",
          "md5": "e1624bbc491f1075f3ce058262daf0db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "detekt-gradle-plugin-1.23.7.jar",
          "url": "detekt-gradle-plugin-1.23.7.jar",
          "size": 174100,
          "sha512": "9b77f07bc515b428d398046b4049ff51274602f6bd4dad7f8ce8962e44660317d41a24729843736e91366066c193e6c4deb626d13cacc8de4e49f79804f1f25a",
          "sha256": "64953a1d81e9062ca2ec96841c0844cb58f2a1591c7bfea92a4275d392417805",
          "sha1": "0b106238ad6b7b2055e380d51076a9851e72670d",
          "md5": "e1624bbc491f1075f3ce058262daf0db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-gradle-plugin-1.23.7-sources.jar",
          "url": "detekt-gradle-plugin-1.23.7-sources.jar",
          "size": 31413,
          "sha512": "4d1b6c4fe23ba72bc769d34ca71f24f22e49635f0c6062f46a74b0188d08dbaa00a1848e71d6fba4fde4d51826324b623206d0fa38a28b04e9e1b0ff5971d9fe",
          "sha256": "19f4c324d8e48b38df7639aa5c508a61dd38c14a97982fdcbf50c93fa47f8253",
          "sha1": "68919c5c8a8b4db6e1296bb0905a59fad71bcafd",
          "md5": "2b0e5609f97c2eafd591618c0359e416"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-gradle-plugin-1.23.7-javadoc.jar",
          "url": "detekt-gradle-plugin-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "890e3021d30859f7954055249f21b5880ddac3b13843d03b3fd2fc97ed3a596e881619934c03a7786c154965f885c292b6aebc2f0ff2c9d8f328dd39458c6750",
          "sha256": "000422088dab561ded3ca3b38f5d0787aaa42ce034a26330003bd3f082fa152b",
          "sha1": "87077aab9d24bbd2479bd12a83f7f639faf5710d",
          "md5": "c120a0ced59b54cd0c579b47b7ace0a3"
        }
      ]
    }
  ]
}
