{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-cli-reporter-html",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-html-1.3.1.jar",
          "url": "ktlint-cli-reporter-html-1.3.1.jar",
          "size": 16976,
          "sha512": "c246e1f94cfefce9dc4588fa9ee38a395b61037f936a1f1226556519be0c80608652f69d13ca171d4b5f756f240cc2e4014361cf35a41fb6f1c0ccaa6867291e",
          "sha256": "67acfb5361d5aabcafeb1eb32cb22c899679099f81bf316b3cf3386a9d22dbd6",
          "sha1": "c79d91d91ebde82fbf788e883682e3a1c3d1f75a",
          "md5": "279d36d5636c056735c9784a86c78f53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-html-1.3.1.jar",
          "url": "ktlint-cli-reporter-html-1.3.1.jar",
          "size": 16976,
          "sha512": "c246e1f94cfefce9dc4588fa9ee38a395b61037f936a1f1226556519be0c80608652f69d13ca171d4b5f756f240cc2e4014361cf35a41fb6f1c0ccaa6867291e",
          "sha256": "67acfb5361d5aabcafeb1eb32cb22c899679099f81bf316b3cf3386a9d22dbd6",
          "sha1": "c79d91d91ebde82fbf788e883682e3a1c3d1f75a",
          "md5": "279d36d5636c056735c9784a86c78f53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-html-1.3.1-sources.jar",
          "url": "ktlint-cli-reporter-html-1.3.1-sources.jar",
          "size": 4315,
          "sha512": "8bf824644f3fecd5f05fa3b81628d02148f81283b69bfc0c40beb74ec0e83ead00adac08fa2e8e863ae6bd73cf3ed974120103f085c5a38a24ee66f161ff0856",
          "sha256": "d3e2ccc7bcbcce29029e0c3f5f46b2b90dff5a4e9ae620672efec422cb8f0ce3",
          "sha1": "f7ca86e6be4416cb7ad2b525bba3249ee955ab36",
          "md5": "7c26890e3cdfa4f97928f6bfb9ff38c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-html-1.3.1-javadoc.jar",
          "url": "ktlint-cli-reporter-html-1.3.1-javadoc.jar",
          "size": 414114,
          "sha512": "726b6b2b272efed73e0e87d95eb2f4adcce8dff3ba802cb3f83843b9ac9b09f9f458258e7438dc4e8a73a1f82ba6e5a8a69823891b6899e58d0436df898769c5",
          "sha256": "4a42badbc6c21838c962ddfb6d2e4b440b9d97f9acaa52fbac8ae375b5669c02",
          "sha1": "44d5d8cb4baa305ee9d3b97e029382150c701b2d",
          "md5": "bfbcbce0a3e4a3f1c9a93ebd88b12c41"
        }
      ]
    }
  ]
}
