{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget-proto",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-proto-1.1.1.jar",
          "url": "glance-appwidget-proto-1.1.1.jar",
          "size": 45115,
          "sha512": "18bbf9bfdd1a81ef4b25db2eeed2375b7b5471e8b89d935eb36353f9d9fb6a1e264ed9ca756179795a03224b19b5cd1bbabad18004f0fcd84e185fc686ef9dcb",
          "sha256": "00f31fabdbb9cf773478d374504b8937303e25699ba622a70d37b1027e5a1f78",
          "sha1": "a509ef84a63e2584c5afae6e1d5a757e1bae4418",
          "md5": "db4fc19a3d2c592883cf1e033630ca1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-proto-1.1.1.jar",
          "url": "glance-appwidget-proto-1.1.1.jar",
          "size": 45115,
          "sha512": "18bbf9bfdd1a81ef4b25db2eeed2375b7b5471e8b89d935eb36353f9d9fb6a1e264ed9ca756179795a03224b19b5cd1bbabad18004f0fcd84e185fc686ef9dcb",
          "sha256": "00f31fabdbb9cf773478d374504b8937303e25699ba622a70d37b1027e5a1f78",
          "sha1": "a509ef84a63e2584c5afae6e1d5a757e1bae4418",
          "md5": "db4fc19a3d2c592883cf1e033630ca1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-proto-1.1.1-sources.jar",
          "url": "glance-appwidget-proto-1.1.1-sources.jar",
          "size": 10899,
          "sha512": "b923f51b2478f8828e4ea0399ee2ff3e4d801fd6f0a86954a2b2b9dc439b81384c7201d0a278f16c1d774c78195429e6a48de2a84ceb0baeccf4940a1e9a049c",
          "sha256": "568fbced99ad329d8a7fe3e4411c033a9bee4f4a07d6f113f281aadafa6bafc9",
          "sha1": "6267f9b9682bdd3355e72fc01c6bca1d990ea036",
          "md5": "5ea4579d3e0e99c851a95d6e147c6731"
        }
      ]
    }
  ]
}