{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-bundled/2.5.2/sqlite-bundled-2.5.2.module",
    "group": "androidx.sqlite",
    "module": "sqlite-bundled",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13624135"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-jvm-2.5.2.jar",
          "url": "sqlite-bundled-jvm-2.5.2.jar",
          "size": 5664317,
          "sha512": "f1351bf99555eed81b547d57630bc05624f46d23d2667e1070112655adea7600b8cf7cf8194e0ed020f313bfb779f50cb4f742459989690579b6186ad3203e03",
          "sha256": "518d032204065c45f20e2e0e55f8de9fcf9fccf6d6439df8f0f97b63463b9e5a",
          "sha1": "f22b58b09135ad6f985fa380a0f9dc27e8e9d2ee",
          "md5": "a7443e582f2d1727a37493ae01e5524a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-jvm-2.5.2.jar",
          "url": "sqlite-bundled-jvm-2.5.2.jar",
          "size": 5664317,
          "sha512": "f1351bf99555eed81b547d57630bc05624f46d23d2667e1070112655adea7600b8cf7cf8194e0ed020f313bfb779f50cb4f742459989690579b6186ad3203e03",
          "sha256": "518d032204065c45f20e2e0e55f8de9fcf9fccf6d6439df8f0f97b63463b9e5a",
          "sha1": "f22b58b09135ad6f985fa380a0f9dc27e8e9d2ee",
          "md5": "a7443e582f2d1727a37493ae01e5524a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-jvm-2.5.2-sources.jar",
          "url": "sqlite-bundled-jvm-2.5.2-sources.jar",
          "size": 17694,
          "sha512": "c8998400519997c12344902d9b4fb3b4733fa8d4327e3591c36143b0a4fc5e7d0b73a03b153c5b405521302b1104a81e8df03c906ec7498806e5ab3d9712fb7f",
          "sha256": "225cfa5db28f9e17e5c6bde754331e8a511fe31be19b7a31fd1b7623ee960358",
          "sha1": "41e255728bcf212de3a84e5b53093761312d7edb",
          "md5": "c543c375ba7874224966debe5fb2b65a"
        }
      ]
    }
  ]
}