{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.7.6/material-ripple-1.7.6.module",
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.6"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.7.6.aar",
          "size": 96135,
          "sha512": "29819b1d064b48d3c8f3d47fb340e043ef897c941ac6f7e64d61e95bb2f5d9883791344ebaeffa366caa4c25944cf8a9e51caf059df5ef17d0a8544da93d4df7",
          "sha256": "4f4b176d09191141e43023c85bb9f5a7de8f519efdd90c3d0a7dc953b3b2a8da",
          "sha1": "2f71eac652d6dd6ce4a67b7a5e5161d3b1fcbd45",
          "md5": "c2c4148fbb178b4d25a918ce7ff315c7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.7.6.aar",
          "size": 96135,
          "sha512": "29819b1d064b48d3c8f3d47fb340e043ef897c941ac6f7e64d61e95bb2f5d9883791344ebaeffa366caa4c25944cf8a9e51caf059df5ef17d0a8544da93d4df7",
          "sha256": "4f4b176d09191141e43023c85bb9f5a7de8f519efdd90c3d0a7dc953b3b2a8da",
          "sha1": "2f71eac652d6dd6ce4a67b7a5e5161d3b1fcbd45",
          "md5": "c2c4148fbb178b4d25a918ce7ff315c7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material-ripple-android-1.7.6-sources.jar",
          "url": "material-ripple-android-1.7.6-sources.jar",
          "size": 26493,
          "sha512": "cf75021625684728c83771b88735b3c52e328994c7adca1b415f16d3a433253c8775f06626aa791bfaa025a992577e661fd2645eab2fa4ad264e86352921ec52",
          "sha256": "ef8710a7152243363ce61099827c5e07618dd2911032311da38b0275cdebea4e",
          "sha1": "7850da88009864d77e29340230e91bcb270656d9",
          "md5": "fb144e81bbdee600bd3575d47e6c4d76"
        }
      ]
    }
  ]
}