{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-framework-engine/5.9.1/kotest-framework-engine-5.9.1.module",
    "group": "io.kotest",
    "module": "kotest-framework-engine",
    "version": "5.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.classgraph",
          "module": "classgraph",
          "version": {
            "requires": "4.8.172"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-discovery",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "mordant",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-api",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-jvm-5.9.1.jar",
          "url": "kotest-framework-engine-jvm-5.9.1.jar",
          "size": 1002890,
          "sha512": "3ed4f1d51aba44a107d0c261ea5b089c7a2a9744a4d5c4583063270758c91f2fe2da4c50b7b9b226e69a66afdd2a5ba85762cfc3d1a1053cbaa5953a20edaf09",
          "sha256": "f9747af8921542cc7063e0f27c20a5e842c46a8ae5ad3cf0296e0d187d2a0cce",
          "sha1": "e269e651f8dd98c28b308c8121a315800f6e5b9e",
          "md5": "272d5173efa2ec18a489b817e1aace82"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.classgraph",
          "module": "classgraph",
          "version": {
            "requires": "4.8.172"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-discovery",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "mordant",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-api",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-debug",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-jvm-5.9.1.jar",
          "url": "kotest-framework-engine-jvm-5.9.1.jar",
          "size": 1002890,
          "sha512": "3ed4f1d51aba44a107d0c261ea5b089c7a2a9744a4d5c4583063270758c91f2fe2da4c50b7b9b226e69a66afdd2a5ba85762cfc3d1a1053cbaa5953a20edaf09",
          "sha256": "f9747af8921542cc7063e0f27c20a5e842c46a8ae5ad3cf0296e0d187d2a0cce",
          "sha1": "e269e651f8dd98c28b308c8121a315800f6e5b9e",
          "md5": "272d5173efa2ec18a489b817e1aace82"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-framework-engine-jvm-5.9.1-sources.jar",
          "url": "kotest-framework-engine-jvm-5.9.1-sources.jar",
          "size": 145959,
          "sha512": "d082ccdddc0face88336df0c55bfd25ceafa07b2ac8a6e816d758dc84baf056e95e51395a62393a111c844d5fe7462246bba5d0bd4b096ad56ed06e7d251e463",
          "sha256": "dd0bff3fc60d27ae2717247abb33c8ded8807f76dee6ce110ba90d6b597faa72",
          "sha1": "47e980b15b47f56a9528c572df1775233bb2fd0a",
          "md5": "364b35e15c5a0c9f349e51349a7f0828"
        }
      ]
    }
  ]
}
