{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto-binary",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0.aar",
          "url": "tracing-perfetto-binary-1.0.0.aar",
          "size": 4340343,
          "sha512": "a73e25a6d8b30814a066553c146d3f36a102b5be5414d384bb24cc0860e6433934f96a0e4c77fd6a2aa5ecdef72b9c03f7c9ed28444c86c19aed0f6218bd5291",
          "sha256": "e36809d054202758488687ec60ed81a3cbd87bd027a87f05aa3f64451e6d3098",
          "sha1": "292f4d9975794b5d77f2eec902512b2db8230c84",
          "md5": "4302c7b6c00596e028b40e6fdb889b12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0.aar",
          "url": "tracing-perfetto-binary-1.0.0.aar",
          "size": 4340343,
          "sha512": "a73e25a6d8b30814a066553c146d3f36a102b5be5414d384bb24cc0860e6433934f96a0e4c77fd6a2aa5ecdef72b9c03f7c9ed28444c86c19aed0f6218bd5291",
          "sha256": "e36809d054202758488687ec60ed81a3cbd87bd027a87f05aa3f64451e6d3098",
          "sha1": "292f4d9975794b5d77f2eec902512b2db8230c84",
          "md5": "4302c7b6c00596e028b40e6fdb889b12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0-sources.jar",
          "url": "tracing-perfetto-binary-1.0.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0-versionMetadata.json",
          "url": "tracing-perfetto-binary-1.0.0-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}