{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-cli-reporter-sarif",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-sarif-1.3.1.jar",
          "url": "ktlint-cli-reporter-sarif-1.3.1.jar",
          "size": 7900,
          "sha512": "6f0bf6547fd19257299dc862dbc7237f6fb85c7a0396cf7b0be56a08e156dd79f24e7394d7abecfd0da622ac1b28717be0471a3e9a228eb48c8e23d6ea95cdb1",
          "sha256": "b67bccdb596be8559ba6ddacf8673e09c9ca71f2925f805edf0a589d94409aa0",
          "sha1": "28cdb46eecba4850d6745099abba1d51947a4600",
          "md5": "fd7389343149757e2328060d7990b722"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli-reporter-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.detekt.sarif4k",
          "module": "sarif4k",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-cli-reporter-sarif-1.3.1.jar",
          "url": "ktlint-cli-reporter-sarif-1.3.1.jar",
          "size": 7900,
          "sha512": "6f0bf6547fd19257299dc862dbc7237f6fb85c7a0396cf7b0be56a08e156dd79f24e7394d7abecfd0da622ac1b28717be0471a3e9a228eb48c8e23d6ea95cdb1",
          "sha256": "b67bccdb596be8559ba6ddacf8673e09c9ca71f2925f805edf0a589d94409aa0",
          "sha1": "28cdb46eecba4850d6745099abba1d51947a4600",
          "md5": "fd7389343149757e2328060d7990b722"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-sarif-1.3.1-sources.jar",
          "url": "ktlint-cli-reporter-sarif-1.3.1-sources.jar",
          "size": 3147,
          "sha512": "aaa58217e6faf7a4f41da03ad70f66c89140bc4f3bc676d5bfd04236f46e76dae6caafd22ad2dffe2a452c61b9f567b206969870b5a66fb5753bb6c549627797",
          "sha256": "63d325253b5389b065dfcce776d9dfea920225d2bceb3247be03b189c9e0e142",
          "sha1": "03869bf77e9d651dfd3b1433efb0ec7b4e39a7b9",
          "md5": "63eb05add8d9ad66f041a5b64cfb26b4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-cli-reporter-sarif-1.3.1-javadoc.jar",
          "url": "ktlint-cli-reporter-sarif-1.3.1-javadoc.jar",
          "size": 414250,
          "sha512": "6a323899e074f58e4a5c35ab6b72669ae6c6956d44743f0e938429de2fc73a7d8b9915f59815d0e78a5a01eaa4d231b8ca0d9b8dd47b2c139b6461b94f2a2a21",
          "sha256": "6eea4349fb16e1c5e4d18a160db38cfd3965070f09c2c52e64d341202e2de3f2",
          "sha1": "b4aa58bcd11eacc38bc8f995647a5dc9362f8d06",
          "md5": "1fea106d078868e2e6956cbf550a15f3"
        }
      ]
    }
  ]
}
