{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.paparazzi",
    "module": "paparazzi-gradle-plugin",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "paparazzi-gradle-plugin-1.3.5.jar",
          "url": "paparazzi-gradle-plugin-1.3.5.jar",
          "size": 114602,
          "sha512": "3f707cd1a2a2abd01450dc8d630991a38a04bbdb14b8e7fcf19c8728155c388f7457c11d5058a7bcb02760f1ef90b6d53cca26d13056ad168bec26d51457f3c7",
          "sha256": "7271964599266bf81ddb0483d57c2dfa65990204d616897a63ff1f33242b9eb5",
          "sha1": "c4fd35868339e28f03107aaeffceb987a32ad770",
          "md5": "ed0f01ec2d4800d37765a7374176efa3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.4.2"
          },
          "reason": "SymbolUtils.getPackageNameFromManifest removed in AGP 7.0.  Replace?"
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "paparazzi-gradle-plugin-1.3.5.jar",
          "url": "paparazzi-gradle-plugin-1.3.5.jar",
          "size": 114602,
          "sha512": "3f707cd1a2a2abd01450dc8d630991a38a04bbdb14b8e7fcf19c8728155c388f7457c11d5058a7bcb02760f1ef90b6d53cca26d13056ad168bec26d51457f3c7",
          "sha256": "7271964599266bf81ddb0483d57c2dfa65990204d616897a63ff1f33242b9eb5",
          "sha1": "c4fd35868339e28f03107aaeffceb987a32ad770",
          "md5": "ed0f01ec2d4800d37765a7374176efa3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paparazzi-gradle-plugin-1.3.5-sources.jar",
          "url": "paparazzi-gradle-plugin-1.3.5-sources.jar",
          "size": 26476,
          "sha512": "877a1228cef6ea773ec64482663a9b0cc25c64a29ea3208e75b4d454f40ffa5bb5cb587d34ab53477c74380dd6f5642821694665de73434f39b29b5cf7cf267a",
          "sha256": "b2b1ec022cbb1008c99cf92a53ede7722aa003911af1612df3325352e6da1694",
          "sha1": "f91318db81096524993b6fd74b1235d7d3c73eab",
          "md5": "ef302b90641bb986ecf4f42bffd91ce3"
        }
      ]
    }
  ]
}
