{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-rule-engine",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-rule-engine-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.ec4j.core",
          "module": "ec4j-core",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-rule-engine-1.3.1.jar",
          "url": "ktlint-rule-engine-1.3.1.jar",
          "size": 297957,
          "sha512": "cedc8835239911d876e0f6b0fbfc34e8f89be2c332b47afda7771568b6784bc8141fe7d5b63e0c254a5d9d922361364a7359f7a094edd295db8afcec3f011d11",
          "sha256": "72a2b8e0f3e412ec5af5a208df691a68c56c4742d5f0f1faf21a79d33170f9eb",
          "sha1": "866dcd6e0a88123b037e678ad90b00e10a66753f",
          "md5": "83edc78fae7791f2aa519c118673f88f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-logger",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-rule-engine-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.ec4j.core",
          "module": "ec4j-core",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-rule-engine-1.3.1.jar",
          "url": "ktlint-rule-engine-1.3.1.jar",
          "size": 297957,
          "sha512": "cedc8835239911d876e0f6b0fbfc34e8f89be2c332b47afda7771568b6784bc8141fe7d5b63e0c254a5d9d922361364a7359f7a094edd295db8afcec3f011d11",
          "sha256": "72a2b8e0f3e412ec5af5a208df691a68c56c4742d5f0f1faf21a79d33170f9eb",
          "sha1": "866dcd6e0a88123b037e678ad90b00e10a66753f",
          "md5": "83edc78fae7791f2aa519c118673f88f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-rule-engine-1.3.1-sources.jar",
          "url": "ktlint-rule-engine-1.3.1-sources.jar",
          "size": 52562,
          "sha512": "991aa9d507312f6415b9a2d8f1e7298342174d785a6d51e30a8ea310ad7e1a1bc78f6cc9f38bd883689dc9914049219f0586a1bb629d02578f18067205c460e5",
          "sha256": "410afb09672f5736acc257d1055ee3d4c561d3328c513adac4c0a90ef371f75c",
          "sha1": "3f9176a532228f211556b593a6df2ee5b6693971",
          "md5": "f5cecb393b34172b011b7ff1fa6dab07"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-rule-engine-1.3.1-javadoc.jar",
          "url": "ktlint-rule-engine-1.3.1-javadoc.jar",
          "size": 506854,
          "sha512": "3401063ee69f76b9ae0a6a2df6a5e148a9e3f8fd7d299e98ba2dc32ebe7edb7114f531b4da5404d1339f6a159a4d254c5f78318f6545ffa2a14727de71d3e543",
          "sha256": "37c15a9e6e055bdd7786209cb64f29de53b18715b24ca4bca0163426e797f86e",
          "sha1": "7bd3056a5736e938b173c7934ff6fcfaf8fad123",
          "md5": "9d38ba2cdc3ad2ebc9beda62a0f7353c"
        }
      ]
    }
  ]
}
