{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-test/1.10.1/kotlinx-coroutines-test-1.10.1.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-test",
    "version": "1.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-jvm-1.10.1.jar",
          "url": "kotlinx-coroutines-test-jvm-1.10.1.jar",
          "size": 136778,
          "sha512": "92165ee17bb8e9be28681b0a08ff1858c6eaa00a8fd8a642a671dc7a1f17ee4ac6ea6cb68acc32bb06143005d5c436aa498eee4677262db0a04088f1fad0b4ec",
          "sha256": "ac3f456c9e25c3fc01542dc208655d0583cd37b5f72c35856267b74bd1664ab6",
          "sha1": "59e227710a85e0a8bbca177990970d9d847b22de",
          "md5": "4190b64eb48261dc1cf6d2795403db41"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-jvm-1.10.1.jar",
          "url": "kotlinx-coroutines-test-jvm-1.10.1.jar",
          "size": 136778,
          "sha512": "92165ee17bb8e9be28681b0a08ff1858c6eaa00a8fd8a642a671dc7a1f17ee4ac6ea6cb68acc32bb06143005d5c436aa498eee4677262db0a04088f1fad0b4ec",
          "sha256": "ac3f456c9e25c3fc01542dc208655d0583cd37b5f72c35856267b74bd1664ab6",
          "sha1": "59e227710a85e0a8bbca177990970d9d847b22de",
          "md5": "4190b64eb48261dc1cf6d2795403db41"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-test-jvm-1.10.1-sources.jar",
          "url": "kotlinx-coroutines-test-jvm-1.10.1-sources.jar",
          "size": 33669,
          "sha512": "99113e2038d284234531d00895918b9e0f64627ca1a91708d690d918ba50ed575c157315a56e3ccfe03753cf1297f91e2b7b1f235812ec1142be9909af7139ad",
          "sha256": "89847b3d36bcbb75f3f4dedc674937dae5f0d5c59f9e6fef0313cbe15a8f3617",
          "sha1": "a6659b6ab5c36f88d04c3b835c2e61276a8877b1",
          "md5": "65453c1bfd206c1fe640ae3db2508563"
        }
      ]
    }
  ]
}
