{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt.coil3",
    "module": "coil-compose-core",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-core-metadata-3.1.0.jar",
          "url": "coil-compose-core-3.1.0.jar",
          "size": 19279,
          "sha512": "0753f58122342adfee05383843604a92b47ffc6b148e860c402774a930f086fcb1e0d865e7ff50a99df8707c1acc19c2b473774a53b51cfa0c588729fbac09fe",
          "sha256": "85e8947b02a4f3fcc641176a83ab498228e9607d483201226b4b98ad0ca7ca4c",
          "sha1": "cdb68f03a1029e1583830c0e8184d9f64276c702",
          "md5": "d4f21756d594ee5dd4263b78bab09aef"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "coil-compose-core-kotlin-3.1.0-sources.jar",
          "url": "coil-compose-core-3.1.0-sources.jar",
          "size": 24788,
          "sha512": "0475ba4b58159f8a8021bfea95fd3d869d0e900def72c1b591bd2710e2231cf2c2b468cbd76cb3a4a1d8f64eadd83a796c8f1d41a41aeb3567e8b11ca0d50fd4",
          "sha256": "20bbfae0c7d92dfde4049e7af102e30e7e4cd488072843b11d894b3134bc83b1",
          "sha1": "a3e3dc481de5f9dc1121f79b2833b31587116e63",
          "md5": "5bea45303a8f40ca85b27c53499b9d09"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-android/3.1.0/coil-compose-core-android-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-android",
        "version": "3.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-android/3.1.0/coil-compose-core-android-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-android",
        "version": "3.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-android/3.1.0/coil-compose-core-android-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-android",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosarm64/3.1.0/coil-compose-core-iosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosarm64/3.1.0/coil-compose-core-iosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosarm64/3.1.0/coil-compose-core-iosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosarm64/3.1.0/coil-compose-core-iosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iossimulatorarm64/3.1.0/coil-compose-core-iossimulatorarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iossimulatorarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iossimulatorarm64/3.1.0/coil-compose-core-iossimulatorarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iossimulatorarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iossimulatorarm64/3.1.0/coil-compose-core-iossimulatorarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iossimulatorarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iossimulatorarm64/3.1.0/coil-compose-core-iossimulatorarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iossimulatorarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosx64/3.1.0/coil-compose-core-iosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosx64/3.1.0/coil-compose-core-iosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosx64/3.1.0/coil-compose-core-iosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosx64/3.1.0/coil-compose-core-iosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-js/3.1.0/coil-compose-core-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-js/3.1.0/coil-compose-core-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-js/3.1.0/coil-compose-core-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-js/3.1.0/coil-compose-core-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-jvm/3.1.0/coil-compose-core-jvm-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-jvm",
        "version": "3.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-jvm/3.1.0/coil-compose-core-jvm-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-jvm",
        "version": "3.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-jvm/3.1.0/coil-compose-core-jvm-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-jvm",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosarm64/3.1.0/coil-compose-core-macosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosarm64/3.1.0/coil-compose-core-macosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosarm64/3.1.0/coil-compose-core-macosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosarm64/3.1.0/coil-compose-core-macosarm64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosarm64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosx64/3.1.0/coil-compose-core-macosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosx64/3.1.0/coil-compose-core-macosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosx64/3.1.0/coil-compose-core-macosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosx64/3.1.0/coil-compose-core-macosx64-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosx64",
        "version": "3.1.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-wasm-js/3.1.0/coil-compose-core-wasm-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-wasm-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-wasm-js/3.1.0/coil-compose-core-wasm-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-wasm-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-wasm-js/3.1.0/coil-compose-core-wasm-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-wasm-js",
        "version": "3.1.0"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-wasm-js/3.1.0/coil-compose-core-wasm-js-3.1.0.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-wasm-js",
        "version": "3.1.0"
      }
    }
  ]
}
