{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.4.1/kotlinx-serialization-json-1.4.1.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.4.1.jar",
          "url": "kotlinx-serialization-json-jvm-1.4.1.jar",
          "size": 230125,
          "sha512": "a47c35e4c9a92044b7f54f3fd0cf208ceae08a3513b3d519e17387a0ab05390c8210e5b13853e21c6d0c8797cbc667143777cedee060f16964ff9ec353760f13",
          "sha256": "af604c46737121d4225fdb60ef0e17766a3c94b7c1c9ef76b4e3a5c7733d557e",
          "sha1": "e6430b33f06dcdff88998abfcb2e78bc3cd0a1f6",
          "md5": "9c0d33c9b12c371a5d8934c97466eb70"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.4.1.jar",
          "url": "kotlinx-serialization-json-jvm-1.4.1.jar",
          "size": 230125,
          "sha512": "a47c35e4c9a92044b7f54f3fd0cf208ceae08a3513b3d519e17387a0ab05390c8210e5b13853e21c6d0c8797cbc667143777cedee060f16964ff9ec353760f13",
          "sha256": "af604c46737121d4225fdb60ef0e17766a3c94b7c1c9ef76b4e3a5c7733d557e",
          "sha1": "e6430b33f06dcdff88998abfcb2e78bc3cd0a1f6",
          "md5": "9c0d33c9b12c371a5d8934c97466eb70"
        }
      ]
    }
  ]
}
