{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-rules-coroutines",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-rules-coroutines-1.23.7.jar",
          "url": "detekt-rules-coroutines-1.23.7.jar",
          "size": 41902,
          "sha512": "f073bae7a6609479571977a6d0b8f43c0315e8350579c61c3f2591944b853f5c1611ab6df109f48f3ffec82df370f174e429f559d90902b791c1be71c2aef437",
          "sha256": "c5123c9fbcbe4ed494ea8826ec3102285a4e479e1c0ddbb8071bbe4984524402",
          "sha1": "678d4412b3769fba98f03fa0e2ecfc464d39cd3d",
          "md5": "d837951bfa367054889bb1828ef9aada"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-rules-coroutines-1.23.7.jar",
          "url": "detekt-rules-coroutines-1.23.7.jar",
          "size": 41902,
          "sha512": "f073bae7a6609479571977a6d0b8f43c0315e8350579c61c3f2591944b853f5c1611ab6df109f48f3ffec82df370f174e429f559d90902b791c1be71c2aef437",
          "sha256": "c5123c9fbcbe4ed494ea8826ec3102285a4e479e1c0ddbb8071bbe4984524402",
          "sha1": "678d4412b3769fba98f03fa0e2ecfc464d39cd3d",
          "md5": "d837951bfa367054889bb1828ef9aada"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-rules-coroutines-1.23.7-sources.jar",
          "url": "detekt-rules-coroutines-1.23.7-sources.jar",
          "size": 13311,
          "sha512": "dd34f2d91ccfde42856a2c7dacb8f29ec3a89dd9c06cfaf6c4c26619c10132342435a7c5b6816773d35a8e01bdfd95f0819050b077897e00af3e6cc00c422ade",
          "sha256": "e9dff7f43704793d247534d1c9d8e82193a8d3d8c2e666c2454008ec5248e6ef",
          "sha1": "13af777985860f413c382b211c8645e6c29034a8",
          "md5": "e09d6a5ec4a555f9c11ac5c940a57559"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-rules-coroutines-1.23.7-javadoc.jar",
          "url": "detekt-rules-coroutines-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "890e3021d30859f7954055249f21b5880ddac3b13843d03b3fd2fc97ed3a596e881619934c03a7786c154965f885c292b6aebc2f0ff2c9d8f328dd39458c6750",
          "sha256": "000422088dab561ded3ca3b38f5d0787aaa42ce034a26330003bd3f082fa152b",
          "sha1": "87077aab9d24bbd2479bd12a83f7f639faf5710d",
          "md5": "c120a0ced59b54cd0c579b47b7ace0a3"
        }
      ]
    }
  ]
}
