{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-multiprocess",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-multiprocess-2.10.0-sources.jar",
          "url": "work-multiprocess-2.10.0-sources.jar",
          "size": 56122,
          "sha512": "78c52eec463ac9b591fcafeae9a1b533f84712873b8f0336e480e6698bd4e2f75fef1c68a22d4aa4a7d9e88ed740a8b79803ae2895dca99e7fee0ac5402d0853",
          "sha256": "00ea6eb667f786cc4b9cad95e70d6e5b9045972273b5cd1a03cb2ba77ec2dee9",
          "sha1": "f50e9fba409cefb626d632c3a978704b7c806a58",
          "md5": "472ee72514faa60cef075c113703449f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "work-multiprocess-2.10.0.aar",
          "url": "work-multiprocess-2.10.0.aar",
          "size": 128702,
          "sha512": "4db77841317bc757e612298f26a67a58024a5b7602544de956bad39efd2fa063b4a5840bb03258f830f6374d857f2c8ac5ae04811e81b4ceacdd002e1af29475",
          "sha256": "968afd2ec27b4c832a36bb463cd611a3a976d2aacb2124a34eafa2760c28fe85",
          "sha1": "b9d906ae501df91af191ac9fb6ec637e2a086e80",
          "md5": "2eaa7f36319543698b0544670ea091dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "work-multiprocess-2.10.0.aar",
          "url": "work-multiprocess-2.10.0.aar",
          "size": 128702,
          "sha512": "4db77841317bc757e612298f26a67a58024a5b7602544de956bad39efd2fa063b4a5840bb03258f830f6374d857f2c8ac5ae04811e81b4ceacdd002e1af29475",
          "sha256": "968afd2ec27b4c832a36bb463cd611a3a976d2aacb2124a34eafa2760c28fe85",
          "sha1": "b9d906ae501df91af191ac9fb6ec637e2a086e80",
          "md5": "2eaa7f36319543698b0544670ea091dc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "work-multiprocess is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-multiprocess-2.10.0-versionMetadata.json",
          "url": "work-multiprocess-2.10.0-versionMetadata.json",
          "size": 1613,
          "sha512": "240503325cf17090dbe22526ca4578863c068ab40fa345101960ba9a0df11f950c97030faf4f22ab5e637caaa58637bb4598877fbcc282c341b576999490aec4",
          "sha256": "fab1da784dc21600527089e6e218738d185e1717aefa3741af3e757af7dc8463",
          "sha1": "4b80343f4547fd97cac5215d27f160d934bcdba2",
          "md5": "0df32b83af7bc48f51539bbe8a356fff"
        }
      ]
    }
  ]
}