{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-core/1.7.6/material-icons-core-1.7.6.module",
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-release.aar",
          "url": "material-icons-core-android-1.7.6.aar",
          "size": 823515,
          "sha512": "4ea563408bd5f4b64c4c5f31d4bcfa88dae6f3c7f68d6b8ca5652993422dd6aed38d713377f84630208950b19e0e449ea815ade304046bdcec70a03145087512",
          "sha256": "48d182051236b1dfec829b33bf4d3fd06d03c2876d532208e3f7490159d65c46",
          "sha1": "57538d4c99063937529d9daa0746247b6f90bd1c",
          "md5": "5194b078f74bae94503d25f5ff3ead36"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "material-icons-core-release.aar",
          "url": "material-icons-core-android-1.7.6.aar",
          "size": 823515,
          "sha512": "4ea563408bd5f4b64c4c5f31d4bcfa88dae6f3c7f68d6b8ca5652993422dd6aed38d713377f84630208950b19e0e449ea815ade304046bdcec70a03145087512",
          "sha256": "48d182051236b1dfec829b33bf4d3fd06d03c2876d532208e3f7490159d65c46",
          "sha1": "57538d4c99063937529d9daa0746247b6f90bd1c",
          "md5": "5194b078f74bae94503d25f5ff3ead36"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material-icons-core-1.7.6-samples-sources.jar",
          "url": "material-icons-core-android-1.7.6-samples-sources.jar",
          "size": 1849,
          "sha512": "5e82b6fc611569270b0a77b159588b3d249a31627630b5e8a1eeb18b462eca347a9a9dfd07bac984a4b1b3df6d71fd490fda7a6f07995b5fcaaee4c2f038ec6c",
          "sha256": "262d79cf95faf69f89988b01d568d48b69742a95b0959b9238e2e797457938fa",
          "sha1": "578ff7394b718fb34c333c24bcfade35ccba41c5",
          "md5": "6dfd44933714f319df97b87cf801f994"
        },
        {
          "name": "material-icons-core-android-1.7.6-sources.jar",
          "url": "material-icons-core-android-1.7.6-sources.jar",
          "size": 284048,
          "sha512": "2803312f6e4dfb1b2501b44f47eb72fd02212e41a18c5dcbec7b7e280612b486d23b72d50688a2fb3776b1582ae63ec923fd3f39bdbc4e951a779dc133495f64",
          "sha256": "b3f1be7fda4d13a6d938bb918275ddc143e9d6a2007727f284778480526f5f16",
          "sha1": "e518df0d8a19c3833f72a24ff667853015e340fd",
          "md5": "6f8dfe229b864de0e1deaa71ad0c1434"
        }
      ]
    }
  ]
}