{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drewhamilton.poko",
    "module": "poko-annotations",
    "version": "0.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "poko-annotations-metadata-0.15.3.jar",
          "url": "poko-annotations-0.15.3.jar",
          "size": 3831,
          "sha512": "934e9d578e35c457d09324586dafb0b2b43f95e38fdaefee40bb5fd41b6f33cc09cac01088c70c633a50afae2522091088acae7f84a0872506e11a3b07527eb7",
          "sha256": "430098378622145474056356e2a0e266505900a287256a06afc68aeec3b8eee7",
          "sha1": "59ab9d718c452582d3294e8449e941b277cfa798",
          "md5": "20dfb4381084789188c6ff8032603e76"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "poko-annotations-kotlin-0.15.3-sources.jar",
          "url": "poko-annotations-0.15.3-sources.jar",
          "size": 2809,
          "sha512": "fe9d680b373ead51295415d70160c35164bd40609fd93a31315d4131d8e28c92aa6db57a204c6874342f7b8b8386fad6e8d46b3a7715dfab7adaca88bbe6b4e1",
          "sha256": "7a735dde85bad254b3b48a1e272de91640c80cf855fafbeee569ba66edeced6d",
          "sha1": "21646c1cdea5fe1bad4634aa5e3d33cb5f4f5be4",
          "md5": "e989b70fef1e1dd433377f6bf32012b4"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativearm32/0.15.3/poko-annotations-androidnativearm32-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativearm32",
        "version": "0.15.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativearm32/0.15.3/poko-annotations-androidnativearm32-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativearm32",
        "version": "0.15.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativearm64/0.15.3/poko-annotations-androidnativearm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativearm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativearm64/0.15.3/poko-annotations-androidnativearm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativearm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativex64/0.15.3/poko-annotations-androidnativex64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativex64",
        "version": "0.15.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativex64/0.15.3/poko-annotations-androidnativex64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativex64",
        "version": "0.15.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativex86/0.15.3/poko-annotations-androidnativex86-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativex86",
        "version": "0.15.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-androidnativex86/0.15.3/poko-annotations-androidnativex86-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-androidnativex86",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosarm64/0.15.3/poko-annotations-iosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosarm64/0.15.3/poko-annotations-iosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosarm64/0.15.3/poko-annotations-iosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iossimulatorarm64/0.15.3/poko-annotations-iossimulatorarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iossimulatorarm64/0.15.3/poko-annotations-iossimulatorarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iossimulatorarm64/0.15.3/poko-annotations-iossimulatorarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosx64/0.15.3/poko-annotations-iosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosx64/0.15.3/poko-annotations-iosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-iosx64/0.15.3/poko-annotations-iosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-iosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-js/0.15.3/poko-annotations-js-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-js",
        "version": "0.15.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-js/0.15.3/poko-annotations-js-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-js",
        "version": "0.15.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-js/0.15.3/poko-annotations-js-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-js",
        "version": "0.15.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../poko-annotations-jvm/0.15.3/poko-annotations-jvm-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-jvm",
        "version": "0.15.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../poko-annotations-jvm/0.15.3/poko-annotations-jvm-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-jvm",
        "version": "0.15.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../poko-annotations-jvm/0.15.3/poko-annotations-jvm-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-jvm",
        "version": "0.15.3"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-linuxarm64/0.15.3/poko-annotations-linuxarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-linuxarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-linuxarm64/0.15.3/poko-annotations-linuxarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-linuxarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-linuxx64/0.15.3/poko-annotations-linuxx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-linuxx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-linuxx64/0.15.3/poko-annotations-linuxx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-linuxx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosarm64/0.15.3/poko-annotations-macosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosarm64/0.15.3/poko-annotations-macosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosarm64/0.15.3/poko-annotations-macosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosx64/0.15.3/poko-annotations-macosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosx64/0.15.3/poko-annotations-macosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-macosx64/0.15.3/poko-annotations-macosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-macosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-mingwx64/0.15.3/poko-annotations-mingwx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-mingwx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-mingwx64/0.15.3/poko-annotations-mingwx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-mingwx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosarm64/0.15.3/poko-annotations-tvosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosarm64/0.15.3/poko-annotations-tvosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosarm64/0.15.3/poko-annotations-tvosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvossimulatorarm64/0.15.3/poko-annotations-tvossimulatorarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvossimulatorarm64/0.15.3/poko-annotations-tvossimulatorarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvossimulatorarm64/0.15.3/poko-annotations-tvossimulatorarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosx64/0.15.3/poko-annotations-tvosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosx64/0.15.3/poko-annotations-tvosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-tvosx64/0.15.3/poko-annotations-tvosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-tvosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-js/0.15.3/poko-annotations-wasm-js-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-js",
        "version": "0.15.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-js/0.15.3/poko-annotations-wasm-js-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-js",
        "version": "0.15.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-js/0.15.3/poko-annotations-wasm-js-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-js",
        "version": "0.15.3"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-wasi/0.15.3/poko-annotations-wasm-wasi-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-wasi",
        "version": "0.15.3"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-wasi/0.15.3/poko-annotations-wasm-wasi-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-wasi",
        "version": "0.15.3"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../poko-annotations-wasm-wasi/0.15.3/poko-annotations-wasm-wasi-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-wasm-wasi",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm32/0.15.3/poko-annotations-watchosarm32-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm32",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm32/0.15.3/poko-annotations-watchosarm32-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm32",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm32/0.15.3/poko-annotations-watchosarm32-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm32",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm64/0.15.3/poko-annotations-watchosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm64/0.15.3/poko-annotations-watchosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosarm64/0.15.3/poko-annotations-watchosarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosdevicearm64/0.15.3/poko-annotations-watchosdevicearm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosdevicearm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosdevicearm64/0.15.3/poko-annotations-watchosdevicearm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosdevicearm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosdevicearm64/0.15.3/poko-annotations-watchosdevicearm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosdevicearm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchossimulatorarm64/0.15.3/poko-annotations-watchossimulatorarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchossimulatorarm64/0.15.3/poko-annotations-watchossimulatorarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchossimulatorarm64/0.15.3/poko-annotations-watchossimulatorarm64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosx64/0.15.3/poko-annotations-watchosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosx64/0.15.3/poko-annotations-watchosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../poko-annotations-watchosx64/0.15.3/poko-annotations-watchosx64-0.15.3.module",
        "group": "dev.drewhamilton.poko",
        "module": "poko-annotations-watchosx64",
        "version": "0.15.3"
      }
    }
  ]
}
