{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-1.3.1-multiplatform-sources.jar",
          "url": "material3-1.3.1-multiplatform-sources.jar",
          "size": 526778,
          "sha512": "75008581e199188e5e980658c5346f61df1f399f835390e5eb78f5d0888f75083e05d48b193c03612221ceb3336f7a5f8779b92fc5ac838c6ef097eac80c411f",
          "sha256": "36c949194fb8ec8f730231fcc856edb8061cfbbefbebaaafe5f29ef4dd497201",
          "sha1": "3e43a91bad8886440fa29f3ef57bdb79bf96fe08",
          "md5": "4bf3cb689c9050de25937ba04089dcc0"
        },
        {
          "name": "material3-1.3.1-samples-sources.jar",
          "url": "material3-1.3.1-samples-sources.jar",
          "size": 58300,
          "sha512": "b70c1e94c6641a463bfa5bf9ed67e0972e4b8b44ef01e76c3a28880bf76996faa97157e9e64c4b2769d2f5ef5e7993c280dcacdd05b358573aed21b457a8a1e2",
          "sha256": "3329e1a97328bbeda1e9c4f8305037ef6c13ab227af31b8ea65f757c2e791162",
          "sha1": "785900bfcf93caf2c601e44d7194f12d13deddd7",
          "md5": "74345ebc9dc3ee902fc1b71b5afe36ea"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material3-1.3.1-versionMetadata.json",
          "size": 187552,
          "sha512": "dab904630b8380f59cff1b3a06d5ad9808ba652ab1fde7828efedf73241931a12138807d83640d49ceaf5bf3aae26ab7a24d8da0057efd030f8602ce518221ac",
          "sha256": "2a55b01000f338382d3238fc185b1034260bcf0384b6382c3c19a1963e45c02e",
          "sha1": "0f157040e45030f4540cae182c658ccdb4484ae3",
          "md5": "4b88b29e1eb107fd9106985aecf8b29d"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-metadata-1.3.1.jar",
          "url": "material3-1.3.1.jar",
          "size": 779,
          "sha512": "bb024903400e25f11e31b9d13575ae8870883aa974e193ff7f963be13ed55d095b38fa37be3e49a1458d699340bb6b41687b09d7573f85031ac0c209a482c88c",
          "sha256": "e2667048f898be236e8f3980d8137496bcafb626ebc4eedf32aa00f481f8fff7",
          "sha1": "441ff636812c1cad5bcfb3d084cc85d690d81144",
          "md5": "27a4d8fd017cf5c5b82a388b161e3539"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-kotlin-1.3.1-sources.jar",
          "url": "material3-1.3.1-sources.jar",
          "size": 452882,
          "sha512": "410a26ce22155b5bd330531f0effac29ee91b331b4c3b9bd4659cb3c563a2e5ce47fbe4bb38324aa0a6b35e0ba6628d797f4667ab2a5cabe1e6b2b8dfb681da5",
          "sha256": "55bb1ea8e66bcd44adb68524ebc5365fbe1ba26bd174ac93966ed1a1b0315aa4",
          "sha1": "630391aea5ec05766bd584c79465e4f56e471e28",
          "md5": "5d3a70add0918e64978e1df431e7e33c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.3.1/material3-android-1.3.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.3.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.3.1/material3-android-1.3.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.3.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.3.1/material3-android-1.3.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.3.1"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.3.1/material3-desktop-1.3.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.3.1"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.3.1/material3-desktop-1.3.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.3.1"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.3.1/material3-desktop-1.3.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.3.1"
      }
    }
  ]
}