{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget-external-protobuf",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-external-protobuf-1.1.1.jar",
          "url": "glance-appwidget-external-protobuf-1.1.1.jar",
          "size": 1041140,
          "sha512": "5686dfe9799575bf7a2b5a179b4db7dc52b94f0bb7c431e8fd799e0b6d2a541f729722b3efa27e11033046ff26d8b504372ae19d1b7c56037ec4af795ac75e92",
          "sha256": "10176c95e30d3f1069bfef661aae683c6eaa184dfbe4696f103fcad3c458aa96",
          "sha1": "6d2bcb8fb2d00a5513cf681bb2756be459d21b78",
          "md5": "a0177b041be13d8bb0e40953b9181c42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-external-protobuf-1.1.1.jar",
          "url": "glance-appwidget-external-protobuf-1.1.1.jar",
          "size": 1041140,
          "sha512": "5686dfe9799575bf7a2b5a179b4db7dc52b94f0bb7c431e8fd799e0b6d2a541f729722b3efa27e11033046ff26d8b504372ae19d1b7c56037ec4af795ac75e92",
          "sha256": "10176c95e30d3f1069bfef661aae683c6eaa184dfbe4696f103fcad3c458aa96",
          "sha1": "6d2bcb8fb2d00a5513cf681bb2756be459d21b78",
          "md5": "a0177b041be13d8bb0e40953b9181c42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-external-protobuf-1.1.1-sources.jar",
          "url": "glance-appwidget-external-protobuf-1.1.1-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-external-protobuf-1.1.1-versionMetadata.json",
          "url": "glance-appwidget-external-protobuf-1.1.1-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}