{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-report-xml",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-report-xml-1.23.7.jar",
          "url": "detekt-report-xml-1.23.7.jar",
          "size": 16692,
          "sha512": "8674792d9a42b3f40d3f197917248d3a5f217f5dca0734d4d5adb3136df94eb83e72a2ce74d66fb3ea1d203faa829f50e2cdd2ffa52e05a48c05daa948844617",
          "sha256": "c4b78909c4ef03f0dc1bbd807207aa4d75524f4a29e747ffeb4997d0f7c8e09b",
          "sha1": "e217cc79d42ab2b8df200b2807a9c8e6f239bdd4",
          "md5": "e7142182925e0b3d62106a07df1ce895"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-report-xml-1.23.7.jar",
          "url": "detekt-report-xml-1.23.7.jar",
          "size": 16692,
          "sha512": "8674792d9a42b3f40d3f197917248d3a5f217f5dca0734d4d5adb3136df94eb83e72a2ce74d66fb3ea1d203faa829f50e2cdd2ffa52e05a48c05daa948844617",
          "sha256": "c4b78909c4ef03f0dc1bbd807207aa4d75524f4a29e747ffeb4997d0f7c8e09b",
          "sha1": "e217cc79d42ab2b8df200b2807a9c8e6f239bdd4",
          "md5": "e7142182925e0b3d62106a07df1ce895"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-report-xml-1.23.7-sources.jar",
          "url": "detekt-report-xml-1.23.7-sources.jar",
          "size": 7062,
          "sha512": "9f1096794c51aa95253be982630718b7d6374811a923e91d861bae1649a9c782f07df51d4a14f2068869a935d670a2f5fe721c1378b7ea1a9c498c20fd1d97b4",
          "sha256": "7231252d9f5122885b86112470d837bd1c9454fb7eb776b24c228a7ccd7ca85b",
          "sha1": "d222f558a09c7eb9c93adee5b0d2e9da3c4b0f51",
          "md5": "e88324c142ab7e3cd8a67ca1fe40a84d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-report-xml-1.23.7-javadoc.jar",
          "url": "detekt-report-xml-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "890e3021d30859f7954055249f21b5880ddac3b13843d03b3fd2fc97ed3a596e881619934c03a7786c154965f885c292b6aebc2f0ff2c9d8f328dd39458c6750",
          "sha256": "000422088dab561ded3ca3b38f5d0787aaa42ce034a26330003bd3f082fa152b",
          "sha1": "87077aab9d24bbd2479bd12a83f7f639faf5710d",
          "md5": "c120a0ced59b54cd0c579b47b7ace0a3"
        }
      ]
    }
  ]
}
