{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.security",
    "module": "security-crypto-ktx",
    "version": "1.1.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "security-crypto-ktx-1.1.0-alpha06.aar",
          "url": "security-crypto-ktx-1.1.0-alpha06.aar",
          "size": 6415,
          "sha512": "db76310fa89280c500ea1e4ad25930f977b5030e8c3005fe75e6041f8a4bc8b2bde26a09d1ad3e6f70686418e8e11b7c5543d3b316c580731f24386e733879a9",
          "sha256": "70d71471c36c8d2e4485bfe3f351f1b652794bb80f26caeec062d3647d1db3e0",
          "sha1": "62589af5ee61a4d2706fc3da512071a8d4b6640e",
          "md5": "906d3496970b5c690409e09544e995e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "security-crypto-ktx-1.1.0-alpha06.aar",
          "url": "security-crypto-ktx-1.1.0-alpha06.aar",
          "size": 6415,
          "sha512": "db76310fa89280c500ea1e4ad25930f977b5030e8c3005fe75e6041f8a4bc8b2bde26a09d1ad3e6f70686418e8e11b7c5543d3b316c580731f24386e733879a9",
          "sha256": "70d71471c36c8d2e4485bfe3f351f1b652794bb80f26caeec062d3647d1db3e0",
          "sha1": "62589af5ee61a4d2706fc3da512071a8d4b6640e",
          "md5": "906d3496970b5c690409e09544e995e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-crypto-ktx-1.1.0-alpha06-sources.jar",
          "url": "security-crypto-ktx-1.1.0-alpha06-sources.jar",
          "size": 3488,
          "sha512": "4997a30e33080563bdbfdf0c6a23e4ac2ff95c29058a04e1ce04d436a06f4f5e0ec1b73ba6de17e819edd0e56e869329e6806d51f52ab65faf4d951685b1dc2e",
          "sha256": "4aa5f039a89700e2e4ae1bb53f202f85bc8373cd2ef3c1514bebabe0a561e12e",
          "sha1": "0e4e10ebaca8dc21405f383668c6f7f63c934b48",
          "md5": "41e39188dc80d80fc9e1cd91a07a49e6"
        }
      ]
    }
  ]
}