{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite-bundled",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13624135"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-2.5.2-multiplatform-sources.jar",
          "url": "sqlite-bundled-2.5.2-multiplatform-sources.jar",
          "size": 23709,
          "sha512": "929dcf09800f55ee3dd71a255fd0494d7515668a37aa47c6fe624ffea0d7d72919a635a72cc0be06a8ab28a9e7e214ab1a480527cc90339fd5aeff8df3979106",
          "sha256": "e0cd588f5062e966595694c78bfb0a4b41673d566a018b258a9c94856dddd29d",
          "sha1": "415867e2fc098357cff2bf3085714fe9ca705c2f",
          "md5": "31409f58bc27a7da19768e41708db818"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "sqlite-bundled-2.5.2-versionMetadata.json",
          "size": 822,
          "sha512": "748ef75cc77289eef982716fb874fac398ef4708cc1230ed057f3924aaf9acfa9a90ef32f3554a2a637d3f99ca3f1f346f9fa0ebf1b84284ea0eac91b5b95248",
          "sha256": "dcbd83a28d6a1e649cd020670b99afec0a592d0e7fce63717c5b76bd7cb7aea4",
          "sha1": "f5a84148d252c8a25d92c457e9ae94710415cc62",
          "md5": "e642706accf6c2cb56d2a7276af8768f"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-metadata-2.5.2.jar",
          "url": "sqlite-bundled-2.5.2.jar",
          "size": 17204,
          "sha512": "bfc60f45556c78e674110c2fc07a8df64778fbb2d0ad39a741893953ee781c28d14a05714c9a617d259a7b47f980950b030331ab24e33772976befe8e5613129",
          "sha256": "ae7593f62bd7880a596500d828a2899ae78c4f88669e5ac145dcea17f2a131a6",
          "sha1": "3c4beb0e0575b90693d97492790756618eaf6072",
          "md5": "6886cb66b7d1f1768d3e5bbad222a8dd"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-kotlin-2.5.2-sources.jar",
          "url": "sqlite-bundled-2.5.2-sources.jar",
          "size": 19289,
          "sha512": "d4456fe23b9bc883cde3867e324fd5b17fdebf24d7828e47b411873f165cf90043f047f11d1bed308cf8c8de9a3e5107ed6f5b8ad8d0a7bb7d97f929e45e9f9a",
          "sha256": "d3eba14820b0c94fb63228425ae6097492fd276bb13ded4e138b19df527d916d",
          "sha1": "4d9bf68a6bfe090a1069bcd874c61bb5b923e098",
          "md5": "99951bc2e7ea5ec87f1219b37fc1a771"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sqlite-bundled-android/2.5.2/sqlite-bundled-android-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-android",
        "version": "2.5.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sqlite-bundled-android/2.5.2/sqlite-bundled-android-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-android",
        "version": "2.5.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sqlite-bundled-android/2.5.2/sqlite-bundled-android-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-android",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-iosarm64/2.5.2/sqlite-bundled-iosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-iosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-iosarm64/2.5.2/sqlite-bundled-iosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-iosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-iosarm64/2.5.2/sqlite-bundled-iosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-iosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-iossimulatorarm64/2.5.2/sqlite-bundled-iossimulatorarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-iossimulatorarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-iossimulatorarm64/2.5.2/sqlite-bundled-iossimulatorarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-iossimulatorarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-iossimulatorarm64/2.5.2/sqlite-bundled-iossimulatorarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-iossimulatorarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-iosx64/2.5.2/sqlite-bundled-iosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-iosx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-iosx64/2.5.2/sqlite-bundled-iosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-iosx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-iosx64/2.5.2/sqlite-bundled-iosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-iosx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sqlite-bundled-jvm/2.5.2/sqlite-bundled-jvm-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-jvm",
        "version": "2.5.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sqlite-bundled-jvm/2.5.2/sqlite-bundled-jvm-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-jvm",
        "version": "2.5.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sqlite-bundled-jvm/2.5.2/sqlite-bundled-jvm-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-jvm",
        "version": "2.5.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-linuxarm64/2.5.2/sqlite-bundled-linuxarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-linuxarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-linuxarm64/2.5.2/sqlite-bundled-linuxarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-linuxarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-linuxx64/2.5.2/sqlite-bundled-linuxx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-linuxx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-linuxx64/2.5.2/sqlite-bundled-linuxx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-linuxx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-macosarm64/2.5.2/sqlite-bundled-macosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-macosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-macosarm64/2.5.2/sqlite-bundled-macosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-macosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-macosarm64/2.5.2/sqlite-bundled-macosarm64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-macosarm64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-macosx64/2.5.2/sqlite-bundled-macosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-macosx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-macosx64/2.5.2/sqlite-bundled-macosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-macosx64",
        "version": "2.5.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-bundled-macosx64/2.5.2/sqlite-bundled-macosx64-2.5.2.module",
        "group": "androidx.sqlite",
        "module": "sqlite-bundled-macosx64",
        "version": "2.5.2"
      }
    }
  ]
}