{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.moshi",
    "module": "moshi-kotlin-codegen",
    "version": "1.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "moshi-kotlin-codegen-1.15.2.jar",
          "url": "moshi-kotlin-codegen-1.15.2.jar",
          "size": 1682882,
          "sha512": "c6a61aef47ef0dbe95db9dcfb089e9af10400bc3669e3fb05d1fb4e27f7924a89664faf75670a46c40c11d5ed50986a010240d6fdf0cde04d1e944bd2ffa4f78",
          "sha256": "949ce943e0ee135bd41ba4abf08b3a1608d4378671de12388690b5432b4e8a3b",
          "sha1": "99d6b60ade906ff62a3fd793777b0908c95baed4",
          "md5": "cb3aa869ff97ff716cc8e3d91f646db8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "moshi-kotlin-codegen-1.15.2.jar",
          "url": "moshi-kotlin-codegen-1.15.2.jar",
          "size": 1682882,
          "sha512": "c6a61aef47ef0dbe95db9dcfb089e9af10400bc3669e3fb05d1fb4e27f7924a89664faf75670a46c40c11d5ed50986a010240d6fdf0cde04d1e944bd2ffa4f78",
          "sha256": "949ce943e0ee135bd41ba4abf08b3a1608d4378671de12388690b5432b4e8a3b",
          "sha1": "99d6b60ade906ff62a3fd793777b0908c95baed4",
          "md5": "cb3aa869ff97ff716cc8e3d91f646db8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moshi-kotlin-codegen-1.15.2.jar",
          "url": "moshi-kotlin-codegen-1.15.2.jar",
          "size": 1682882,
          "sha512": "c6a61aef47ef0dbe95db9dcfb089e9af10400bc3669e3fb05d1fb4e27f7924a89664faf75670a46c40c11d5ed50986a010240d6fdf0cde04d1e944bd2ffa4f78",
          "sha256": "949ce943e0ee135bd41ba4abf08b3a1608d4378671de12388690b5432b4e8a3b",
          "sha1": "99d6b60ade906ff62a3fd793777b0908c95baed4",
          "md5": "cb3aa869ff97ff716cc8e3d91f646db8"
        }
      ]
    }
  ]
}
