{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gitlab.arturbosch.detekt",
    "module": "detekt-report-md",
    "version": "1.23.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-report-md-1.23.7.jar",
          "url": "detekt-report-md-1.23.7.jar",
          "size": 15100,
          "sha512": "438e8b708d616ee5e3f5b4619fcc6da97ffde14ab517a4a6985c4e5cdffcf558b965f35784432589c22c4153d30af09afe92978962c21a693b7db4c757e2631f",
          "sha256": "7c3ad77113fb8821b5adde900d318bb39d4d2361eae30f0de2adbe8fea2ea648",
          "sha1": "412d8d4b5eb996b1a0935d9d35a19a257772939a",
          "md5": "7ae5e9220f62c46c681ebc38969fecce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-metrics",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-utils",
          "version": {
            "requires": "1.23.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "detekt-report-md-1.23.7.jar",
          "url": "detekt-report-md-1.23.7.jar",
          "size": 15100,
          "sha512": "438e8b708d616ee5e3f5b4619fcc6da97ffde14ab517a4a6985c4e5cdffcf558b965f35784432589c22c4153d30af09afe92978962c21a693b7db4c757e2631f",
          "sha256": "7c3ad77113fb8821b5adde900d318bb39d4d2361eae30f0de2adbe8fea2ea648",
          "sha1": "412d8d4b5eb996b1a0935d9d35a19a257772939a",
          "md5": "7ae5e9220f62c46c681ebc38969fecce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-report-md-1.23.7-sources.jar",
          "url": "detekt-report-md-1.23.7-sources.jar",
          "size": 3194,
          "sha512": "a904bccb5925775b7d84883d030b81ccacb3de56828e0fb62366f0f21b5fe331214270f6f9d287b29893a54ad549140197554ffdafcb73ff184b9b8d5f8c65db",
          "sha256": "83fff522d836360ea851c073b521a087cef7e8e8e64e9b390c65bc946eabe401",
          "sha1": "0dc371cb5ff457bd085d7ea22c98f815ffa6c656",
          "md5": "581d4282a0302c226b1d4b31d4ed8ea2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "detekt-report-md-1.23.7-javadoc.jar",
          "url": "detekt-report-md-1.23.7-javadoc.jar",
          "size": 303,
          "sha512": "431e6cead14fc7e89fac0ea690136d7d79d81b9d5013036fa58e6ca687a1d5a4c1f8d387a33391009f1606eeb63993fe863952ced2be81c1705525652d4a86c4",
          "sha256": "ad4604708f3a05d27f80c40669203f1f94cf2ef0a7f6da50e9eb710f0e73f01a",
          "sha1": "b24a695db5fa6bba8a7382edb5b8c6416830f470",
          "md5": "5ce60b8dc25017fc78b227b282c04018"
        }
      ]
    }
  ]
}
