{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-network-core/3.1.0/coil-network-core-3.1.0.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-network-core",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-core-release.aar",
          "url": "coil-network-core-android-3.1.0.aar",
          "size": 60834,
          "sha512": "d66799f68c3113efa0d0f521d3c4fecba22b9328003ea153b9fce1fd94b91db928e71d82ec8814f82c7cc5378e119661d22bad8a1a7c6cc622783fe4cef90812",
          "sha256": "e100353cea231981514b49d2b89bec10c2b8daee279a164c80ff850f4f6d8bf0",
          "sha1": "d682ca0a54a70e688f0759bb5f512c86686736c9",
          "md5": "faab99572cdb0b4cc1fa6ecc59fe6bf0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "coil-network-core-release.aar",
          "url": "coil-network-core-android-3.1.0.aar",
          "size": 60834,
          "sha512": "d66799f68c3113efa0d0f521d3c4fecba22b9328003ea153b9fce1fd94b91db928e71d82ec8814f82c7cc5378e119661d22bad8a1a7c6cc622783fe4cef90812",
          "sha256": "e100353cea231981514b49d2b89bec10c2b8daee279a164c80ff850f4f6d8bf0",
          "sha1": "d682ca0a54a70e688f0759bb5f512c86686736c9",
          "md5": "faab99572cdb0b4cc1fa6ecc59fe6bf0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "coil-network-core-android-3.1.0-sources.jar",
          "url": "coil-network-core-android-3.1.0-sources.jar",
          "size": 12315,
          "sha512": "88062939891df014b1327e2721ae2ab94e0774ce2783063dbdff922112f425f6390933c7ff3eee2c4f859224e96befae8f38b671a204a0f64a52d6b214eac0f6",
          "sha256": "b8d28d0dccbfac69b6e36dcaf09db58b95c108270182a8ce8fca7b58aa1d7fa2",
          "sha1": "9833368946adb7f614cba16bbe4aab5862bd4f59",
          "md5": "6b1f08051c3da3ba35040e7a3b8d28cb"
        }
      ]
    }
  ]
}
