{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-testing",
    "version": "2.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-testing-2.8.9-sources.jar",
          "url": "navigation-testing-2.8.9-sources.jar",
          "size": 11658,
          "sha512": "69b7b986c0f12dd62b9a59164f9d8470ec1353c74e2b042f7372e2ae4f6469ae568d4970db001b05982e1bece2dfceb77e2c09abb2a340d8f9d0d78c965857f8",
          "sha256": "19fd44c05589ccb3196ae70e404008f7b5ea800cc7b0bbb077a02655c2308abc",
          "sha1": "023092c5cfb5b8b1b9d9a0179d2ef5587e87faf3",
          "md5": "344b96a60487de08393fbd1c36a5b81a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-testing-2.8.9.aar",
          "url": "navigation-testing-2.8.9.aar",
          "size": 31815,
          "sha512": "2024ec162119802860672cfb7c8f8ef60d174cfc07fb43aca3d841f90303829207540c27b8661643d8bed343bee7d9d34e53df9092938ef92cbde0f61cc35760",
          "sha256": "1502f3c9074eaae9d1678fffba21d4710563f1b5489c0311728011b4598ca489",
          "sha1": "025ba8e92fbe8f7f9715377ed1e0243e107381d5",
          "md5": "2d6cf461df0ef4ee6ff39d217b1aef24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-testing-2.8.9.aar",
          "url": "navigation-testing-2.8.9.aar",
          "size": 31815,
          "sha512": "2024ec162119802860672cfb7c8f8ef60d174cfc07fb43aca3d841f90303829207540c27b8661643d8bed343bee7d9d34e53df9092938ef92cbde0f61cc35760",
          "sha256": "1502f3c9074eaae9d1678fffba21d4710563f1b5489c0311728011b4598ca489",
          "sha1": "025ba8e92fbe8f7f9715377ed1e0243e107381d5",
          "md5": "2d6cf461df0ef4ee6ff39d217b1aef24"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.9"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-testing-2.8.9-versionMetadata.json",
          "url": "navigation-testing-2.8.9-versionMetadata.json",
          "size": 1340,
          "sha512": "b929489dae3cfc63c662a3df1d952d6101c0f8d566fb1865e54bbad8f646c9ccbbc120e6b3fb7b0d63c19b63264cf7a8b7bda9277b817330dba455e464ecc6c8",
          "sha256": "8c1a477ac5b3d6cf7effda42f0e77d7b55c46c46a628c13c1dbc93f83c79b8e4",
          "sha1": "a99e697387b0c132e8ad1068c22c035edee832bf",
          "md5": "8f59a20217cfb2bfcb8dc9ed6363a512"
        }
      ]
    }
  ]
}