{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite-ktx",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13624135"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-ktx-2.5.2-sources.jar",
          "url": "sqlite-ktx-2.5.2-sources.jar",
          "size": 5623,
          "sha512": "914b5e6206a6879f5298f32a3d8ec15fa75ef2885d24e98a2a74cf2cfc65be8ec66965695f88a17422419905dff52e924414a399cbf422c52b3aacd47b1e8b09",
          "sha256": "beda326ca417a4322e0e3837f96bf08b3700d14ff0644b8c7929c28271f3bbae",
          "sha1": "b349d11b0411b96a25b874bbed7f8b3dbb99edf4",
          "md5": "49912c33f620632bab211f7707278859"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-ktx-2.5.2.aar",
          "url": "sqlite-ktx-2.5.2.aar",
          "size": 7267,
          "sha512": "ea7d63fce370f056685df4e0fdb8dc2f857d47980b5fe724489436dc59236a8e1cb278fc041d29024eba64e3dfec04451ce8d9f5b246531696c9be61ae86444c",
          "sha256": "e87c4c30fd8ad23d52e9719e44d77006d6f4f646a2f15431cb59a06f3fbc2c83",
          "sha1": "9f1a2f122f288866f5343f7a2e46fb1809fc207e",
          "md5": "7ddd0385434623b17aa94b8f2626a077"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-ktx-2.5.2.aar",
          "url": "sqlite-ktx-2.5.2.aar",
          "size": 7267,
          "sha512": "ea7d63fce370f056685df4e0fdb8dc2f857d47980b5fe724489436dc59236a8e1cb278fc041d29024eba64e3dfec04451ce8d9f5b246531696c9be61ae86444c",
          "sha256": "e87c4c30fd8ad23d52e9719e44d77006d6f4f646a2f15431cb59a06f3fbc2c83",
          "sha1": "9f1a2f122f288866f5343f7a2e46fb1809fc207e",
          "md5": "7ddd0385434623b17aa94b8f2626a077"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-ktx-2.5.2-versionMetadata.json",
          "url": "sqlite-ktx-2.5.2-versionMetadata.json",
          "size": 287,
          "sha512": "c7fa34656dc2af2d39785cb822d9bb5fb59273e1ba52411d56d046ec25984b7b997d544e5c46c26cc31fa43596b7b2f988492fb3fe5445ca2035328e413ecb0f",
          "sha256": "d97365d6760fdd7460e6e1cff1adac38063fec8b1a2f66c6a607ebc27055c190",
          "sha1": "adc59c7bac1346ce2809b96bdd250dd5068b0027",
          "md5": "d305c52e1028c247bd25be592c14b19d"
        }
      ]
    }
  ]
}