{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.ajalt.colormath",
    "module": "colormath",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "colormath-metadata.jar",
          "url": "colormath-3.5.0.jar",
          "size": 24991,
          "sha512": "0e5bafd391e6d8b577d997b3bd7a1b6685b470281a65b9e84b9bbb8e1f7ca059d185dc26002619d3cf3717a53252a6be182a06a5859cf4e1ff0dc557526b658e",
          "sha256": "bd229baf3bafd556d189de72471d9d17c29aa1f5d3244560270bef8e63a2319a",
          "sha1": "50d320eb2056de36f065f369f93f9311d2dd4757",
          "md5": "a3350628c8699187dc4c8a6ffd35fdf3"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "colormath-kotlin-sources.jar",
          "url": "colormath-3.5.0-sources.jar",
          "size": 68150,
          "sha512": "dd0cfdf16665437b044d43e0b758e7e83618ab6a558de0567cfb4e1d84fb4c39c66344ff56539b48dc8bc5e8d31ae4fc5eb4cb2573eccc65e47fc759e76b986f",
          "sha256": "cd4baaaa928f21ec45b0cbf78f7071a94be9830bf0e3ed8f320e851f47b32864",
          "sha1": "a0f43a207f4b991240cea93b9be5845e1cdcfde2",
          "md5": "15508a4f8879465963a985259b8f24d3"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-iosarm64/3.5.0/colormath-iosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-iosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-iosarm64/3.5.0/colormath-iosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-iosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-iosarm64/3.5.0/colormath-iosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-iosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-iossimulatorarm64/3.5.0/colormath-iossimulatorarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-iossimulatorarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-iossimulatorarm64/3.5.0/colormath-iossimulatorarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-iossimulatorarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-iossimulatorarm64/3.5.0/colormath-iossimulatorarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-iossimulatorarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-iosx64/3.5.0/colormath-iosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-iosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-iosx64/3.5.0/colormath-iosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-iosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-iosx64/3.5.0/colormath-iosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-iosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../colormath-js/3.5.0/colormath-js-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-js",
        "version": "3.5.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../colormath-js/3.5.0/colormath-js-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-js",
        "version": "3.5.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../colormath-js/3.5.0/colormath-js-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-js",
        "version": "3.5.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../colormath-jvm/3.5.0/colormath-jvm-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-jvm",
        "version": "3.5.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../colormath-jvm/3.5.0/colormath-jvm-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-jvm",
        "version": "3.5.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../colormath-jvm/3.5.0/colormath-jvm-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-jvm",
        "version": "3.5.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-linuxarm64/3.5.0/colormath-linuxarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-linuxarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-linuxarm64/3.5.0/colormath-linuxarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-linuxarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-linuxx64/3.5.0/colormath-linuxx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-linuxx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-linuxx64/3.5.0/colormath-linuxx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-linuxx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-macosarm64/3.5.0/colormath-macosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-macosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-macosarm64/3.5.0/colormath-macosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-macosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-macosarm64/3.5.0/colormath-macosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-macosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-macosx64/3.5.0/colormath-macosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-macosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-macosx64/3.5.0/colormath-macosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-macosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-macosx64/3.5.0/colormath-macosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-macosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-mingwx64/3.5.0/colormath-mingwx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-mingwx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-mingwx64/3.5.0/colormath-mingwx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-mingwx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-tvosarm64/3.5.0/colormath-tvosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-tvosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-tvosarm64/3.5.0/colormath-tvosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-tvosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-tvosarm64/3.5.0/colormath-tvosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-tvosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-tvossimulatorarm64/3.5.0/colormath-tvossimulatorarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-tvossimulatorarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-tvossimulatorarm64/3.5.0/colormath-tvossimulatorarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-tvossimulatorarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-tvossimulatorarm64/3.5.0/colormath-tvossimulatorarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-tvossimulatorarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-tvosx64/3.5.0/colormath-tvosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-tvosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-tvosx64/3.5.0/colormath-tvosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-tvosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-tvosx64/3.5.0/colormath-tvosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-tvosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../colormath-wasm-js/3.5.0/colormath-wasm-js-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-wasm-js",
        "version": "3.5.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../colormath-wasm-js/3.5.0/colormath-wasm-js-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-wasm-js",
        "version": "3.5.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../colormath-wasm-js/3.5.0/colormath-wasm-js-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-wasm-js",
        "version": "3.5.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-watchosarm64/3.5.0/colormath-watchosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-watchosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-watchosarm64/3.5.0/colormath-watchosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-watchosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-watchosarm64/3.5.0/colormath-watchosarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-watchosarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-watchossimulatorarm64/3.5.0/colormath-watchossimulatorarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-watchossimulatorarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-watchossimulatorarm64/3.5.0/colormath-watchossimulatorarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-watchossimulatorarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-watchossimulatorarm64/3.5.0/colormath-watchossimulatorarm64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-watchossimulatorarm64",
        "version": "3.5.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-watchosx64/3.5.0/colormath-watchosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-watchosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-watchosx64/3.5.0/colormath-watchosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-watchosx64",
        "version": "3.5.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../colormath-watchosx64/3.5.0/colormath-watchosx64-3.5.0.module",
        "group": "com.github.ajalt.colormath",
        "module": "colormath-watchosx64",
        "version": "3.5.0"
      }
    }
  ]
}
