{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.vectordrawable",
    "module": "vectordrawable-animated",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "vectordrawable-animated-1.2.0.aar",
          "url": "vectordrawable-animated-1.2.0.aar",
          "size": 34288,
          "sha512": "6ac2a303f6c4de8d482f56d1e73e13a40b68311a3cb734a02f9fe0681122fb76a65180a88dff217a6f432b54d5cd3cfb770f5a082bc9eb3fb869b2911678ba5d",
          "sha256": "a070bdd04222a040794e5e9fa4b778d575f7b8f4e84d06d9a38ec4d599770a69",
          "sha1": "a92c7071aaa19cb20de0191ef3ca5c4ca74ad9e2",
          "md5": "db73ca9b49231b72326df451939b5101"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "vectordrawable-animated-1.2.0.aar",
          "url": "vectordrawable-animated-1.2.0.aar",
          "size": 34288,
          "sha512": "6ac2a303f6c4de8d482f56d1e73e13a40b68311a3cb734a02f9fe0681122fb76a65180a88dff217a6f432b54d5cd3cfb770f5a082bc9eb3fb869b2911678ba5d",
          "sha256": "a070bdd04222a040794e5e9fa4b778d575f7b8f4e84d06d9a38ec4d599770a69",
          "sha1": "a92c7071aaa19cb20de0191ef3ca5c4ca74ad9e2",
          "md5": "db73ca9b49231b72326df451939b5101"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "vectordrawable-animated-1.2.0-versionMetadata.json",
          "url": "vectordrawable-animated-1.2.0-versionMetadata.json",
          "size": 2379,
          "sha512": "df8a79f9b2837301a24dab262b2d4f5a8ba61b8022ede5b44a237f03aa3c79aa60ba5d8c719efabfa1ddd6fb514377d643b064dd67be60fe36621b76695c9ff3",
          "sha256": "7daa5866007c304ccf89b4b06c154d2e1d1ab6356c7b7d53d5ba6c53634a2ae8",
          "sha1": "c606b463f55d2da130d1b9a3ece07d8b650764f2",
          "md5": "96630d3f640ad3de1bc6e3ffb91e22f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectordrawable-animated-1.2.0-sources.jar",
          "url": "vectordrawable-animated-1.2.0-sources.jar",
          "size": 24058,
          "sha512": "471ca0fc891a1192d31a580b63a66cb24e18697b2aa4c23bb74a22e1eef21588dd0612ec46f0383d91d3d3fc8649c2276d5dbca75846da4eb4a990e337cd5faa",
          "sha256": "c79f5b9da40a4611c1af79de6e48781060a9c50a2cdb5842c84e967abec89239",
          "sha1": "899ada6cdfdea4e0567063e6db3b3dafafed62cd",
          "md5": "771ccf8a78490255c2bf5ac3124eae58"
        }
      ]
    }
  ]
}